instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'motor_car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'motor_car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'motor_car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
studied_in('mental_health_of_jesus', 'psychopathology').
studied_in('health_effect', 'exposure_science').
studied_in('built_environment', 'built_environment_and_design_studies').
studied_in('built_environment', 'industrial_ecology').
studied_in('health_effects_from_noise', 'audiology').
studied_in('mental_health_of_jesus', 'psychopathology').
studied_in('health_effect', 'exposure_science').
studied_in('built_environment', 'built_environment_and_design_studies').
studied_in('built_environment', 'industrial_ecology').
studied_in('health_effects_from_noise', 'audiology').
studied_in('mental_health_of_jesus', 'psychopathology').
studied_in('health_effect', 'exposure_science').
studied_in('built_environment', 'built_environment_and_design_studies').
studied_in('built_environment', 'industrial_ecology').
studied_in('health_effects_from_noise', 'audiology').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('health_effects_of_pesticides', 'pesticide').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('health_effects_of_pesticides', 'pesticide').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('health_effects_of_pesticides', 'pesticide').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
