instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_joe_biden', 'concern').
instance_of('health_of_fr_d_ric_chopin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_charles_darwin', 'health').
instance_of('health_of_charles_darwin', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health_of_adolf_hitler', 'certain_aspects_of_a_person_s_life').
instance_of('possible_monorchism_of_adolf_hitler', 'monorchism').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health_of_jesus', 'certain_aspects_of_a_person_s_life').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health_of_abraham_lincoln', 'certain_aspects_of_a_person_s_life').
instance_of('claims_of_vladimir_putin_s_incapacity_and_death', 'certain_aspects_of_a_person_s_life').
instance_of('paralytic_illness_of_franklin_d__roosevelt', 'certain_aspects_of_a_person_s_life').
instance_of('terri_schiavo_timeline', 'timeline').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('asylum_confinement_of_christopher_smart', 'occurrence').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('age_and_health_concerns_about_donald_trump', 'certain_aspects_of_a_person_s_life').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('age_and_health_concerns_about_donald_trump', 'concern').
instance_of('health_of_vincent_van_gogh', 'certain_aspects_of_a_person_s_life').
instance_of('active_mobility', 'alternative_transportation').
instance_of('autobesity', 'condition').
instance_of('built_environment', 'field_of_study').
instance_of('built_environment', 'field_of_study').
instance_of('effects_of_climate_change', 'effect').
instance_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
instance_of('incarceration_and_health', 'social_determinants_of_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('refugee_health', 'social_determinants_of_health').
instance_of('health_effects_arising_from_the_september_11_attacks', 'health_effect').
instance_of('health_effects_arising_from_the_september_11_attacks', 'cause_of_death').
instance_of('social_determinants_of_obesity', 'social_determinants_of_health').
instance_of('health_and_environmental_effects_of_transport', 'environmental_effects').
instance_of('11_day_heart_camp', 'event').
instance_of('clinical_engineering', 'academic_discipline').
instance_of('convalescence', 'state').
instance_of('enema', 'medical_procedure_type').
instance_of('eurohealthnet', 'partnership').
instance_of('galderma', 'business').
instance_of('grade_approach', 'evaluation').
instance_of('health_care_provider', 'occupation').
instance_of('health_humanities', 'academic_discipline').
instance_of('health_literacy', 'literacy').
instance_of('health_policy', 'field_of_study').
instance_of('health_policy', 'academic_discipline').
instance_of('health_policy', 'field_of_study').
instance_of('health_policy', 'type_of_policy').
instance_of('health_system', 'type_of_system').
instance_of('healthcare_reform_in_china', 'aspect_in_a_geographic_region').
instance_of('health_insurance', 'insurance_type').
instance_of('iron_preparation', 'drug_class').
instance_of('mais_m_dicos', 'incentive_program').
instance_of('medical_device', 'legal_concept').
instance_of('medical_device', 'type_of_tool').
instance_of('oci_foundation_international', 'organization').
instance_of('paradromics', 'company').
instance_of('philosophy_of_healthcare', 'branch_of_philosophy').
instance_of('quality_of_life__healthcare_', 'magnitude').
instance_of('socialized_medicine', 'political_term').
instance_of('tolerated_illness', 'medical_concept').
instance_of('health_professional', 'profession').
instance_of('health_professional', 'occupation_group_according_to_isco_08').
instance_of('paraveterinary_worker', 'profession').
instance_of('paraveterinary_worker', 'q778000').
instance_of('everyday_health', 'business').
instance_of('everyday_health', 'public_company').
instance_of('incidents_at_six_flags_parks', 'wikimedia_list_article').
instance_of('historical_annual_reformulations_of_the_influenza_vaccine', 'vaccine_type').
instance_of('minister_of_health', 'position').
instance_of('minister_of_mental_health', 'position').
instance_of('outline_of_health', 'wikimedia_list_article').
instance_of('outline_of_smoking', 'wikimedia_outline_article').
instance_of('universal_health_care_by_country', 'wikimedia_list_article').
instance_of('unrest__2017_film_', 'film').
instance_of('asia_catalyst', 'nonprofit_organization').
instance_of('initiative_for_medicines__access__and_knowledge', 'organization').
instance_of('lincoln_hospital__bronx_', 'hospital').
instance_of('kate_rew', 'human').
instance_of('t1international', 'organization').
instance_of('animal_lead_poisoning', 'animal_disease').
instance_of('veterinary_pharmacy', 'pharmaceutical_sciences').
instance_of('outline_of_death', 'wikimedia_outline_article').
instance_of('apparent_death', 'animal_behavior').
instance_of('case_fatality_rate', 'ratio').
instance_of('dead_pool', 'game_of_chance').
instance_of('death_and_adjustment_hypotheses', 'theory').
instance_of('death_anxiety', 'phobia').
instance_of('death_drive', 'psychology_terminology').
instance_of('death_rattle', 'symptom').
instance_of('death_positive_movement', 'social_movement').
instance_of('death_positive_movement', 'philosophical_movement').
instance_of('dignified_death', 'right_to_die').
instance_of('lethality', 'ratio').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'motor_car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'motor_car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'motor_car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('age_and_health_concerns_about_joe_biden', 'joe_biden').
facet_of('health_of_fr_d_ric_chopin', 'fr_d_ric_chopin').
facet_of('health_of_charles_darwin', 'charles_darwin').
facet_of('health_of_adolf_hitler', 'adolf_hitler').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('mental_health_of_jesus', 'jesus').
facet_of('health_of_pope_john_paul_ii', 'john_paul_ii').
facet_of('health_of_samuel_johnson', 'samuel_johnson').
facet_of('health_of_abraham_lincoln', 'abraham_lincoln').
facet_of('health_and_appearance_of_michael_jackson', 'michael_jackson').
facet_of('mozart_and_smallpox', 'wolfgang_amadeus_mozart').
facet_of('claims_of_vladimir_putin_s_incapacity_and_death', 'vladimir_putin').
facet_of('paralytic_illness_of_franklin_d__roosevelt', 'franklin_delano_roosevelt').
facet_of('age_and_health_concerns_about_donald_trump', 'donald_trump').
facet_of('health_of_vincent_van_gogh', 'vincent_van_gogh').
facet_of('health_effect', 'health_risk').
facet_of('autobesity', 'automotive_industry').
facet_of('autobesity', 'car').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'public_health_in_the_united_kingdom').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'medicine').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'heat_wave').
facet_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change').
facet_of('effects_of_climate_change_on_human_health', 'health_effects_from_climate').
facet_of('health_and_environmental_impact_of_the_petroleum_industry', 'petroleum_industry').
facet_of('health_impact_of_light_rail_systems', 'light_rail_system').
facet_of('health_effects_from_noise', 'noise_pollution').
facet_of('effects_of_overtime', 'overtime').
facet_of('effects_of_overtime', 'mental_health').
facet_of('effects_of_overtime', 'occupational_health_and_safety').
facet_of('health_effects_arising_from_the_september_11_attacks', 'september_11_attacks').
facet_of('health_and_environmental_effects_of_transport', 'transportation_industry').
facet_of('decision_aids', 'medical_diagnosis').
facet_of('health_equity', 'right_to_health').
facet_of('health_equity', 'social_determinants_of_health').
facet_of('in_absentia_health_care', 'telemedicine').
facet_of('integrated_care', 'health_care').
facet_of('medical_desert', 'regional_health_planning').
facet_of('medical_desert', 'health_services_needs_and_demand').
facet_of('physician_engagement', 'health_care').
facet_of('point_of_care', 'health_care').
facet_of('quality_of_life__healthcare_', 'health_care').
facet_of('value_based_health_care', 'health_care').
facet_of('veterinary_pharmacy', 'veterinary_medicine').
facet_of('death', 'development_of_the_human_body').
facet_of('death', 'life').
facet_of('death_anxiety', 'mortality_salience').
facet_of('information_theoretic_death', 'bioethics').
facet_of('information_theoretic_death', 'philosophy_of_biology').
facet_of('mortality_salience', 'mortality').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'presidency_of_joe_biden').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('clinical_engineering', 'healthcare_technology_management').
part_of('clinical_engineering', 'biomedical_engineering').
part_of('convalescence', 'healing').
part_of('health_policy', 'health_system').
part_of('health_policy', 'politics').
part_of('health_insurance', 'health_system').
part_of('medical_device', 'health_technology').
part_of('health_professional', 'human_resources_for_health').
part_of('veterinary_pharmacy', 'veterinary_medicine').
part_of('veterinary_pharmacy', 'pharmacy').
part_of('apparent_death', 'psychology_terminology').
part_of('death_drive', 'drive_theory').
part_of('death_drive', 'psychology_terminology').
part_of('information_theoretic_death', 'death').
part_of('mortality_salience', 'psychology_terminology').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('death', 'dead').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('11_day_heart_camp', 'nepal').
country('eurohealthnet', 'belgium').
country('galderma', 'switzerland').
country('healthcare_reform_in_china', 'people_s_republic_of_china').
country('mais_m_dicos', 'brazil').
country('everyday_health', 'united_states').
country('asia_catalyst', 'united_states').
country('lincoln_hospital__bronx_', 'united_states').
country('patient_engagement_in_canada', 'canada').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('age_and_health_concerns_about_joe_biden', 'age_and_health_concerns_about_donald_trump').
partially_coincident_with('age_and_health_concerns_about_donald_trump', 'age_and_health_concerns_about_joe_biden').
partially_coincident_with('built_environment', 'q11962721').
partially_coincident_with('health_policy', 'drug_policy').
partially_coincident_with('medical_device', 'medical_equipment').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('possible_monorchism_of_adolf_hitler', 'possibility').
has_characteristic('health_care_provider', 'scope_of_practice').
has_characteristic('in_absentia_health_care', 'in_absentia').
has_characteristic('death', 'manner_of_death').
has_characteristic('death', 'cause_of_death').
has_characteristic('dignified_death', 'control').
has_characteristic('dignified_death', 'dignity').
has_characteristic('dignified_death', 'right_to_die').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'the_role_of_psychotic_disorders_in_religious_history_considered').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'on_the_mental_health_of_jesus_christ').
described_by_source('mental_health_of_jesus', 'psychobiography_of_jesus_christ_in_view_of_w_adys_aw_witwicki_s_theory_of_cratism').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('mental_health_of_jesus', 'q28281039').
described_by_source('mental_health_of_jesus', 'moderne_leben_jesu_forschung_unter_dem_einflusse_der_psychiatrie').
described_by_source('mental_health_of_jesus', 'q57568675').
described_by_source('mental_health_of_jesus', 'q60034179').
described_by_source('mental_health_of_jesus', 'the_good_news_according_to_matthew_and_mark').
described_by_source('enema', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('enema', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('enema', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('enema', 'collier_s_new_encyclopedia__1921').
described_by_source('enema', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('death', 'bible_encyclopedia_of_archimandrite_nicephorus').
described_by_source('death', 'explanatory_dictionary_of_the_living_great_russian_language').
described_by_source('death', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('death', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('death', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('death', 'desktop_encyclopedic_dictionary').
described_by_source('apparent_death', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('case_fatality_rate', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('lethality', 'encyclop_dia_britannica_11th_edition').
studied_in('mental_health_of_jesus', 'psychopathology').
studied_in('health_effect', 'exposure_science').
studied_in('built_environment', 'built_environment_and_design_studies').
studied_in('built_environment', 'industrial_ecology').
studied_in('health_effects_from_noise', 'audiology').
studied_in('mental_health_of_jesus', 'psychopathology').
studied_in('health_effect', 'exposure_science').
studied_in('built_environment', 'built_environment_and_design_studies').
studied_in('built_environment', 'industrial_ecology').
studied_in('health_effects_from_noise', 'audiology').
studied_in('mental_health_of_jesus', 'psychopathology').
studied_in('health_effect', 'exposure_science').
studied_in('built_environment', 'built_environment_and_design_studies').
studied_in('built_environment', 'industrial_ecology').
studied_in('health_effects_from_noise', 'audiology').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('health_of_samuel_johnson', 'writer').
occupation('kate_rew', 'writer').
occupation('kate_rew', 'swimmer').
occupation('kate_rew', 'journalist').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
participant('asylum_confinement_of_christopher_smart', 'christopher_smart').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('asylum_confinement_of_christopher_smart', 'st_luke_s_hospital_for_lunatics').
location('11_day_heart_camp', 'kathmandu').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('health_effect', 'effect').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('built_environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'health_in_the_united_kingdom').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('effects_of_overtime', 'health_effect').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('effects_of_sleep_deprivation_on_cognitive_performance', 'effect').
subclass_of('health_effects_of_sunlight_exposure', 'electromagnetic_radiation_and_health').
subclass_of('health_and_environmental_effects_of_transport', 'environmental_effects').
subclass_of('health_and_environmental_effects_of_transport', 'environmental_issue').
subclass_of('wireless_device_radiation_and_health', 'electromagnetic_radiation_and_health').
subclass_of('chronic_care', 'health_care').
subclass_of('clinical_engineering', 'engineering').
subclass_of('clinical_handover', 'continuity_of_patient_care').
subclass_of('clown_care', 'laughter_therapy').
subclass_of('decision_aids', 'decision_making').
subclass_of('enema', 'drug_administration').
subclass_of('enema', 'medical_procedure').
subclass_of('grade_approach', 'health_care_outcome_assessment').
subclass_of('health_advocacy', 'activism').
subclass_of('health_advocacy', 'advocacy').
subclass_of('health_care_provider', 'person_or_organization').
subclass_of('health_care_provider', 'business').
subclass_of('health_care_provider', 'service_provider').
subclass_of('health_equity', 'social_justice').
subclass_of('health_fair', 'temporary_exhibition').
subclass_of('health_insurance_mandate', 'health_policy').
subclass_of('health_insurance_mandate', 'individual_mandate').
subclass_of('health_literacy', 'information_literacy').
subclass_of('health_literacy', 'health_education').
subclass_of('health_literacy', 'competence').
subclass_of('health_policy', 'public_policy').
subclass_of('health_system', 'medical_organization').
subclass_of('health_system', 'sociotechnical_system').
subclass_of('healthcare_chaplaincy', 'religion_and_health').
subclass_of('healthcare_chaplaincy', 'doctor_patient_relationship').
subclass_of('in_absentia_health_care', 'health_care').
subclass_of('health_insurance', 'insurance').
subclass_of('integrated_care', 'health_care').
subclass_of('lgbtq_life_expectancy', 'life_expectancy').
subclass_of('long_term_care', 'nursing').
subclass_of('long_term_care', 'health_care').
subclass_of('long_term_care', 'residential_care').
subclass_of('long_term_care', 'social_services').
subclass_of('medical_billing', 'business_process').
subclass_of('medical_device', 'appliance').
subclass_of('medical_device', 'medical_product').
subclass_of('medical_tourism', 'tourism').
subclass_of('patient_transport', 'transport').
subclass_of('patient_transport', 'patient_transfer').
subclass_of('person_centered_care', 'nursing').
subclass_of('philosophy_of_healthcare', 'social_philosophy').
subclass_of('physician_engagement', 'work_engagement').
subclass_of('prescriptive_analytics', 'business_analytics').
subclass_of('quality_of_life__healthcare_', 'quality_of_life').
subclass_of('socialized_medicine', 'public_policy').
subclass_of('socialized_medicine', 'health_system').
subclass_of('universal_health_care', 'publicly_funded_health_care').
subclass_of('health_professional', 'intellectual_and_scientific_professionals').
subclass_of('health_professional', 'healthcare_provider').
subclass_of('paraveterinary_worker', 'allied_health_professional').
subclass_of('paraveterinary_worker', 'paraprofessional').
subclass_of('veterinarian', 'health_professional').
subclass_of('veterinarian', 'medical_specialist').
subclass_of('phase_out_of_fossil_fuel_vehicles', 'fossil_fuel_phase_out').
subclass_of('historical_annual_reformulations_of_the_influenza_vaccine', 'influenza_vaccine').
subclass_of('legal_smoking_age', 'minimum_age').
subclass_of('minister_of_health', 'minister').
subclass_of('minister_of_mental_health', 'minister').
subclass_of('patient_participation', 'patient_centered_care').
subclass_of('patient_participation', 'competence__human_resources_').
subclass_of('animal_lead_poisoning', 'lead_poisoning').
subclass_of('apeirophobia', 'phobia').
subclass_of('apparent_death', 'freeze_response').
subclass_of('apparent_death', 'deception').
subclass_of('death_anxiety', 'attitude_to_death').
subclass_of('death_anxiety', 'anxiety_disorder').
subclass_of('die_in', 'demonstration').
subclass_of('dignified_death', 'death').
subclass_of('disease_of_despair', 'cause_of_death').
subclass_of('excess_mortality', 'mortality_rate').
subclass_of('information_theoretic_death', 'irreversible_process').
subclass_of('information_theoretic_death', 'philosophical_concept').
subclass_of('information_theoretic_death', 'destruction').
subclass_of('lethality', 'morbidity').
subclass_of('mortality_forecasting', 'population_projection').
subclass_of('mortality_salience', 'awareness').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('health_effects_of_pesticides', 'pesticide').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('health_effects_of_pesticides', 'pesticide').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('health_effects_of_pesticides', 'pesticide').
has_cause('health_effect', 'environmental_hazard').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('health_effects_of_coal_ash', 'fly_ash').
has_cause('effects_of_climate_change', 'climate_change').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('effects_of_overtime', 'overtime').
has_cause('effects_of_overtime', 'occupational_stress').
has_cause('health_effects_of_pesticides', 'pesticide').
has_cause('health_effects_of_sunlight_exposure', 'solar_irradiance').
has_cause('health_and_environmental_effects_of_transport', 'mode_of_transport').
has_cause('death', 'cause_of_death').
has_cause('death', 'homicide').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
topic_s_main_category('effects_of_climate_change_on_human_health', 'category_weather_and_health').
topic_s_main_category('effects_of_nuclear_explosions_on_human_health', 'q18738609').
topic_s_main_category('electromagnetic_radiation_and_health', 'category_radiation_health_effects').
topic_s_main_category('effects_of_climate_change', 'category_effects_of_climate_change').
topic_s_main_category('health_and_environmental_impact_of_the_petroleum_industry', 'category_environmental_impact_of_the_petroleum_industry').
topic_s_main_category('health_effects_of_sunlight_exposure', 'q9214204').
topic_s_main_category('health_and_environmental_effects_of_transport', 'category_transport_and_the_environment').
topic_s_main_category('clinical_engineering', 'category_clinical_engineering').
topic_s_main_category('clown_care', 'category_clown_care').
topic_s_main_category('health_advocacy', 'category_medical_activism').
topic_s_main_category('health_advocacy', 'category_health_activism').
topic_s_main_category('health_policy', 'category_health_policy').
topic_s_main_category('health_system', 'category_health_system').
topic_s_main_category('health_insurance', 'category_health_insurance').
topic_s_main_category('long_term_care', 'category_long_term_care').
topic_s_main_category('medical_desert', 'q10799738').
topic_s_main_category('medical_device', 'category_medical_devices').
topic_s_main_category('medical_tourism', 'category_medical_tourism').
topic_s_main_category('patient_transport', 'category_medical_transport_devices').
topic_s_main_category('person_centered_care', 'q27497318').
topic_s_main_category('systems_medicine', 'q55820556').
topic_s_main_category('universal_health_care', 'category_universal_health_care').
topic_s_main_category('zenana_missions', 'category_zenana_missions').
topic_s_main_category('health_professional', 'category_health_professionals').
topic_s_main_category('veterinarian', 'category_veterinarians').
topic_s_main_category('minister_of_health', 'category_ministers_of_health').
topic_s_main_category('death', 'category_death').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('electromagnetic_radiation_and_health', 'biological_effects_of_electromagnetic_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('wireless_device_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('wireless_device_radiation_and_health', 'mobile_phones_and_cancer').
different_from('wireless_device_radiation_and_health', 'environmental_impact_of_telecommunications').
different_from('wireless_device_radiation_and_health', 'electromagnetic_radiation_and_health').
different_from('enema', 'edema').
different_from('health_literacy', 'functional_health_literacy').
different_from('medical_tourism', 'wellness_travel').
different_from('socialized_medicine', 'single_payer_health_care').
different_from('death', 'd_den').
different_from('death', 'tod').
different_from('death_anxiety', 'necrophobia').
different_from('dignified_death', 'orthothanasia').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
health_specialty('health_effects_of_pesticides', 'emergency_medicine').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('mental_health_of_jesus', 'psychopathology').
studied_by('health_effect', 'exposure_science').
studied_by('built_environment', 'industrial_ecology').
studied_by('built_environment', 'built_environment_and_design_studies').
studied_by('effects_of_climate_change', 'climate_impact_research').
studied_by('health_effects_from_noise', 'audiology').
studied_by('health_system', 'health_sciences').
duration('11_day_heart_camp', '11').
duration('unrest__2017_film_', '90').
has_use('11_day_heart_camp', 'cardiology').
has_use('health_fair', 'health_promotion').
practiced_by('clown_care', 'hospital_clown').
practiced_by('health_advocacy', 'health_activist').
practiced_by('health_policy', 'health_policy_scholar').
practiced_by('veterinary_pharmacy', 'veterinary_pharmacist').
uses('enema', 'douche').
uses('medical_device', 'ce_marking').
total_revenue('eurohealthnet', '999000').
donations('eurohealthnet', '226500').
located_in_the_administrative_territorial_entity('eurohealthnet', 'city_of_brussels').
located_in_the_administrative_territorial_entity('lincoln_hospital__bronx_', 'the_bronx').
headquarters_location('eurohealthnet', 'city_of_brussels').
headquarters_location('galderma', 'zug').
headquarters_location('everyday_health', 'new_york_city').
owner_of('galderma', 'cetaphil').
industry('galderma', 'pharmaceutical_industry').
child_organization_unit('galderma', 'galderma__united_states_').
child_organization_unit('galderma', 'galderma__france_').
chief_executive_officer('galderma', 'flemming__rnskov').
legal_form('galderma', 'aktiengesellschaft').
legal_form('everyday_health', 'delaware_corporation').
field_of_work('health_advocacy', 'health_care').
field_of_work('health_advocacy', 'health').
field_of_this_occupation('health_care_provider', 'non_health_related_service_typically_performed_by_health_care_providers').
field_of_this_occupation('health_care_provider', 'health_care').
field_of_this_occupation('health_professional', 'health_profession').
field_of_this_occupation('paraveterinary_worker', 'veterinary_medicine').
field_of_this_occupation('veterinarian', 'comparative_medicine').
field_of_this_occupation('veterinarian', 'neutering').
field_of_this_occupation('veterinarian', 'veterinary_activities').
has_part_s_('health_policy', 'public_health_policy').
has_part_s_('health_policy', 'disability_policy').
has_part_s_('health_system', 'pharmacy').
has_part_s_('health_system', 'health_policy').
has_part_s_('health_system', 'health_insurance').
has_part_s_('health_system', 'health_care').
has_part_s_('death', 'philosophy_of_death').
has_part_s_('death', 'single_organism_process').
has_part_s_('death', 'multi_organism_process').
main_subject('health_policy', 'public_health').
main_subject('apeirophobia', 'infinity').
main_subject('apeirophobia', 'eternal_life').
main_subject('apeirophobia', 'black_hole').
main_subject('death_anxiety', 'death').
main_subject('death_positive_movement', 'mortality').
has_list('health_system', 'health_care_systems_by_country').
has_list('veterinarian', 'list_of_veterinarians').
applies_to_jurisdiction('health_system', 'region').
applies_to_jurisdiction('minister_of_health', 'http___www_wikidata_org__well_known_genid_413a51c01e78ebb1efdc9b2349cb62b0').
said_to_be_the_same_as('health_system', 'human_health_activities').
said_to_be_the_same_as('dignified_death', 'euthanasia').
opposite_of('health_insurance', 'self_pay').
opposite_of('death', 'birth').
opposite_of('death_drive', 'drive_toward_life').
main_regulatory_text('medical_device', 'medical_device_regulation').
main_regulatory_text('medical_device', 'q110576697').
main_regulatory_text('medical_device', 'act__2021_600__with_supplementary_provisions_to_the_eu_s_regulations_on_medical_devices').
relevant_qualification('health_professional', 'nclex_rn_exam').
relevant_qualification('health_professional', 'nclex').
topic_s_main_template('health_professional', 'template_infobox_medical_person').
patron_saint('veterinarian', 'blaise_of_sebaste').
social_media_followers('everyday_health', '632265').
social_media_followers('everyday_health', '644483').
social_media_followers('everyday_health', '625622').
stock_exchange('everyday_health', 'new_york_stock_exchange').
owned_by('everyday_health', 'j2_global').
organization_directed_by_the_office_or_position('minister_of_health', 'ministry_of_health').
producer('unrest__2017_film_', 'joanna_kerns').
producer('unrest__2017_film_', 'jennifer_brea').
producer('unrest__2017_film_', 'lindsey_dryden').
producer('unrest__2017_film_', 'deborah_hoffmann').
screenwriter('unrest__2017_film_', 'jennifer_brea').
award_received('unrest__2017_film_', 'sundance_special_jury_prize_documentary').
director('unrest__2017_film_', 'jennifer_brea').
cast_member('unrest__2017_film_', 'jennifer_brea').
cast_member('unrest__2017_film_', 'whitney_dafoe').
genre('unrest__2017_film_', 'drama_film').
genre('unrest__2017_film_', 'documentary_film').
genre('unrest__2017_film_', 'romance_film').
composer('unrest__2017_film_', 'bear_mccreary').
distributed_by('unrest__2017_film_', 'netflix').
country_of_origin('unrest__2017_film_', 'united_states').
original_language_of_film_or_tv_show('unrest__2017_film_', 'english').
cnc_film_rating__france_('unrest__2017_film_', 'no_minors_under_sixteen').
distribution_format('unrest__2017_film_', 'video_on_demand').
film_editor('unrest__2017_film_', 'kim_roberts').
kijkwijzer_rating('unrest__2017_film_', '9').
founded_by('campaign_for_access_to_essential_medicines', 'doctors_without_borders').
parent_organization('lincoln_hospital__bronx_', 'nyc_health___hospitals').
affiliation('lincoln_hospital__bronx_', 'weill_cornell_medicine').
number_of_hospital_beds('lincoln_hospital__bronx_', '362').
sex_or_gender('kate_rew', 'female').
educated_at('kate_rew', 'university_of_oxford').
sport('kate_rew', 'competitive_swimming').
given_name('kate_rew', 'kate').
has_immediate_cause('death', 'clinical_death').
has_immediate_cause('death', 'dying').
has_immediate_cause('information_theoretic_death', 'corpse_decomposition').
named_after('apparent_death', 'thanatos').
symptoms_and_signs('death_rattle', 'sound').
symptoms_and_signs('death_rattle', 'dyspnea').
connects_with('dignified_death', 'right_to_die').
does_not_have_characteristic('dignified_death', 'suffering').
follows('information_theoretic_death', 'brain_death').
used_by('lethality', 'pathologist').
used_by('lethality', 'public_health_scientist').
