instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('index_of_cryptography_articles', 'wikimedia_list_article').
instance_of('differentiation_rules', 'wikimedia_list_article').
instance_of('table_of_divisors', 'table').
instance_of('outline_of_geometry', 'wikimedia_outline_article').
instance_of('graduate_studies_in_mathematics', 'book_series').
instance_of('graduate_texts_in_mathematics', 'book_series').
instance_of('index_of_information_theory_articles', 'wikimedia_list_article').
instance_of('karp_s_21_np_complete_problems', 'set').
instance_of('table_of_lie_groups', 'wikimedia_list_article').
instance_of('index_of_logic_articles', 'wikimedia_template').
instance_of('outline_of_logic', 'wikimedia_outline_article').
instance_of('table_of_newtonian_series', 'wikimedia_list_article').
instance_of('table_of_prime_factors', 'wikimedia_list_article').
instance_of('probability_and_statistics', 'wikimedia_disambiguation_page').
instance_of('outline_of_statistics', 'wikimedia_outline_article').
instance_of('sum_of_squares', 'wikimedia_disambiguation_page').
instance_of('sums_of_powers', 'wikimedia_disambiguation_page').
instance_of('table_of_mathematical_symbols_by_introduction_date', 'wikimedia_list_article').
instance_of('tarjan_s_algorithm', 'wikimedia_disambiguation_page').
instance_of('outline_of_trigonometry', 'wikimedia_list_article').
instance_of('outline_of_trigonometry', 'wikimedia_outline_article').
instance_of('vector_calculus_identities', 'wikimedia_list_article').
instance_of('index_of_wave_articles', 'wikimedia_list_article').
instance_of('nicholas_a__m__monk', 'human').
instance_of('harold_ramkissoon', 'human').
instance_of('timeline_of_women_in_mathematics', 'wikimedia_timeline').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('index_of_cryptography_articles', 'wikimedia_list_article').
instance_of('differentiation_rules', 'wikimedia_list_article').
instance_of('table_of_divisors', 'table').
instance_of('outline_of_geometry', 'wikimedia_outline_article').
instance_of('graduate_studies_in_mathematics', 'book_series').
instance_of('graduate_texts_in_mathematics', 'book_series').
instance_of('index_of_information_theory_articles', 'wikimedia_list_article').
instance_of('karp_s_21_np_complete_problems', 'set').
instance_of('table_of_lie_groups', 'wikimedia_list_article').
instance_of('index_of_logic_articles', 'wikimedia_template').
instance_of('outline_of_logic', 'wikimedia_outline_article').
instance_of('table_of_newtonian_series', 'wikimedia_list_article').
instance_of('table_of_prime_factors', 'wikimedia_list_article').
instance_of('probability_and_statistics', 'wikimedia_disambiguation_page').
instance_of('outline_of_statistics', 'wikimedia_outline_article').
instance_of('sum_of_squares', 'wikimedia_disambiguation_page').
instance_of('sums_of_powers', 'wikimedia_disambiguation_page').
instance_of('table_of_mathematical_symbols_by_introduction_date', 'wikimedia_list_article').
instance_of('tarjan_s_algorithm', 'wikimedia_disambiguation_page').
instance_of('outline_of_trigonometry', 'wikimedia_list_article').
instance_of('outline_of_trigonometry', 'wikimedia_outline_article').
instance_of('vector_calculus_identities', 'wikimedia_list_article').
instance_of('index_of_wave_articles', 'wikimedia_list_article').
instance_of('nicholas_a__m__monk', 'human').
instance_of('harold_ramkissoon', 'human').
instance_of('timeline_of_women_in_mathematics', 'wikimedia_timeline').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('index_of_cryptography_articles', 'wikimedia_list_article').
instance_of('differentiation_rules', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_outline_article').
instance_of('table_of_divisors', 'table').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('index_of_cryptography_articles', 'wikimedia_list_article').
instance_of('differentiation_rules', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_outline_article').
instance_of('table_of_divisors', 'table').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('index_of_cryptography_articles', 'wikimedia_list_article').
instance_of('differentiation_rules', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_outline_article').
instance_of('table_of_divisors', 'table').
instance_of('glossary_of_areas_of_mathematics', 'wikimedia_glossary_list_article').
instance_of('mathematics_subject_classification', 'specialised_classification_scheme').
instance_of('pure_mathematics', 'academic_major').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('lists_of_mathematics_topics', 'wikimedia_list_article').
instance_of('index_of_accounting_articles', 'wikimedia_list_article').
instance_of('outline_of_algebra', 'wikimedia_outline_article').
instance_of('outline_of_algebraic_structures', 'wikimedia_outline_article').
instance_of('outline_of_arithmetic', 'wikimedia_outline_article').
instance_of('outline_of_calculus', 'wikimedia_outline_article').
instance_of('outline_of_category_theory', 'wikimedia_outline_article').
instance_of('index_of_combinatorics_articles', 'wikimedia_list_article').
instance_of('outline_of_combinatorics', 'wikimedia_outline_article').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('index_of_cryptography_articles', 'wikimedia_list_article').
instance_of('differentiation_rules', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_list_article').
instance_of('outline_of_discrete_mathematics', 'wikimedia_outline_article').
instance_of('table_of_divisors', 'table').
instance_of('index_of_fractal_related_articles', 'wikimedia_list_article').
instance_of('outline_of_geometry', 'wikimedia_outline_article').
instance_of('graduate_studies_in_mathematics', 'book_series').
instance_of('graduate_texts_in_mathematics', 'book_series').
instance_of('highly_composite_number', 'type_of_integer').
instance_of('highly_composite_number', 'integer_sequence').
instance_of('index_of_information_theory_articles', 'wikimedia_list_article').
instance_of('karp_s_21_np_complete_problems', 'set').
instance_of('table_of_lie_groups', 'wikimedia_list_article').
instance_of('outline_of_logic', 'wikimedia_outline_article').
instance_of('table_of_newtonian_series', 'wikimedia_list_article').
instance_of('table_of_prime_factors', 'wikimedia_list_article').
instance_of('probability_and_statistics', 'wikimedia_disambiguation_page').
instance_of('outline_of_statistics', 'wikimedia_outline_article').
instance_of('sum_of_squares', 'wikimedia_disambiguation_page').
instance_of('sums_of_powers', 'wikimedia_disambiguation_page').
instance_of('table_of_mathematical_symbols_by_introduction_date', 'wikimedia_list_article').
instance_of('tarjan_s_algorithm', 'wikimedia_disambiguation_page').
instance_of('outline_of_trigonometry', 'wikimedia_list_article').
instance_of('outline_of_trigonometry', 'wikimedia_outline_article').
instance_of('vector_calculus_identities', 'wikimedia_list_article').
instance_of('index_of_wave_articles', 'wikimedia_list_article').
instance_of('hideki_omori', 'human').
instance_of('timeline_of_women_in_mathematics', 'wikimedia_timeline').
instance_of('timeline_of_women_in_mathematics_in_the_united_states', 'timeline').
instance_of('timeline_of_women_in_mathematics_in_the_united_states', 'aspect_in_a_geographic_region').
instance_of('african_women_in_mathematics_association', 'organization').
instance_of('african_women_in_mathematics_association', 'women_s_organization').
instance_of('anne_bennett_prize', 'mathematics_award').
instance_of('association_for_women_in_mathematics', 'professional_association').
instance_of('association_for_women_in_mathematics', 'women_s_organization').
instance_of('association_for_women_in_mathematics_newsletter', 'scientific_journal').
instance_of('caucus_for_women_in_statistics_and_data_science', 'regulatory_college').
instance_of('complexities__women_in_mathematics', 'version__edition_or_translation').
instance_of('european_women_in_mathematics', 'organization').
instance_of('femmes_et_math_matiques', 'organization').
instance_of('femmes_et_math_matiques', 'learned_society').
instance_of('gifted__2017_film_', 'film').
instance_of('graduate_women_in_science', 'international_organization').
instance_of('graduate_women_in_science', 'women_s_organization').
instance_of('graduate_women_in_science', '501_c__3__organization').
instance_of('hidden_figures__book_', 'literary_work').
instance_of('hidden_figures__book_', 'non_fiction_novel').
instance_of('international_women_in_mathematics_day', 'world_day').
instance_of('krieger_nelson_prize', 'science_award').
instance_of('krieger_nelson_prize', 'award').
instance_of('noether_lecture', 'lecture_series').
instance_of('noether_lecture', 'named_lecture').
instance_of('noether_lecture', 'mathematics_award').
instance_of('pioneering_women_in_american_mathematics', 'written_work').
instance_of('power_in_numbers__the_rebel_women_of_mathematics', 'book').
instance_of('ruth_lyttle_satter_prize_in_mathematics', 'mathematics_award').
instance_of('women_in_mathematics__book_', 'book').
instance_of('women_in_stem', 'female_topic').
instance_of('fermat_kitchen', 'manga_series').
instance_of('science_fell_in_love__so_i_tried_to_prove_it', 'manga_series').
instance_of('s_gaku_golden', 'manga_series').
instance_of('s_ji_de_asobo', 'manga_series').
instance_of('trisatika', 'written_work').
instance_of('mathematics_and_art', 'relation').
instance_of('sarah_marie_belcastro', 'human').
instance_of('the_bridges_organization', 'organization').
instance_of('equals_pi', 'painting').
instance_of('european_society_for_mathematics_and_the_arts', 'mathematical_society').
instance_of('fourth_dimension_in_art', 'art_genre').
instance_of('golden_ratio', 'constructible_number').
instance_of('golden_ratio', 'brjuno_number').
instance_of('golden_ratio', 'irrational_number').
instance_of('golden_ratio', 'mathematical_constant').
instance_of('golden_ratio', 'algebraic_number').
instance_of('golden_ratio', 'metallic_ratio').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('m__c__escher__visions_of_symmetry', 'literary_work').
instance_of('making_mathematics_with_needlework', 'literary_work').
instance_of('mathemalchemy', 'organization').
instance_of('a_new_kind_of_science', 'written_work').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('index_of_cryptography_articles', 'wikimedia_article_page').
is_a_list_of('differentiation_rules', 'differentiation_rule').
is_a_list_of('index_of_information_theory_articles', 'wikimedia_article_page').
is_a_list_of('index_of_wave_articles', 'wikimedia_article_page').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('index_of_cryptography_articles', 'wikimedia_article_page').
is_a_list_of('differentiation_rules', 'differentiation_rule').
is_a_list_of('index_of_information_theory_articles', 'wikimedia_article_page').
is_a_list_of('index_of_wave_articles', 'wikimedia_article_page').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('index_of_cryptography_articles', 'wikimedia_article_page').
is_a_list_of('differentiation_rules', 'differentiation_rule').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('index_of_cryptography_articles', 'wikimedia_article_page').
is_a_list_of('differentiation_rules', 'differentiation_rule').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('index_of_cryptography_articles', 'wikimedia_article_page').
is_a_list_of('differentiation_rules', 'differentiation_rule').
is_a_list_of('glossary_of_areas_of_mathematics', 'area_of_mathematics').
is_a_list_of('index_of_accounting_articles', 'wikimedia_article_page').
is_a_list_of('index_of_cryptography_articles', 'wikimedia_article_page').
is_a_list_of('differentiation_rules', 'differentiation_rule').
is_a_list_of('index_of_information_theory_articles', 'wikimedia_article_page').
is_a_list_of('index_of_wave_articles', 'wikimedia_article_page').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematician', 'category_mathematicians').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('mathematics_subject_classification', 'category_mathematics_subject_classification').
topic_s_main_category('association_for_women_in_mathematics', 'category_fellows_of_the_association_for_women_in_mathematics').
topic_s_main_category('science_fell_in_love__so_i_tried_to_prove_it', 'q114008531').
topic_s_main_category('mathematics_and_art', 'category_mathematics_and_art').
topic_s_main_category('golden_ratio', 'category_golden_ratio').
topic_s_main_category('music_and_mathematics', 'category_mathematics_of_music').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('highly_composite_number', 'composite_number').
subclass_of('sums_of_powers', 'sum').
subclass_of('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('highly_composite_number', 'composite_number').
subclass_of('sums_of_powers', 'sum').
subclass_of('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
subclass_of('mathematician', 'scientist').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('highly_composite_number', 'composite_number').
subclass_of('highly_composite_number', 'positive_integer').
subclass_of('sums_of_powers', 'sum').
subclass_of('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
subclass_of('krieger_nelson_prize', 'award_honoring_women').
subclass_of('ruth_lyttle_satter_prize_in_mathematics', 'award_honoring_women').
subclass_of('women_in_stem', 'group_of_humans').
subclass_of('anamorphosis', 'image').
subclass_of('anamorphosis', 'projection').
subclass_of('mathematical_beauty', 'beauty').
subclass_of('mathematics_of_paper_folding', 'mathematics').
subclass_of('music_and_mathematics', 'mathematics_and_art').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
opposite_of('pure_mathematics', 'applied_mathematics').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_statistics', 'statistics').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_statistics', 'statistics').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_category_theory', 'category_theory').
facet_of('outline_of_statistics', 'statistics').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
facet_of('women_in_stem', 'occupational_segregation').
facet_of('mathematical_beauty', 'mathematics').
facet_of('music_and_mathematics', 'music_theory').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('karp_s_21_np_complete_problems', 'boolean_satisfiability_problem').
has_part_s_('karp_s_21_np_complete_problems', 'job_shop_scheduling').
has_part_s_('karp_s_21_np_complete_problems', 'exact_cover').
has_part_s_('karp_s_21_np_complete_problems', 'knapsack_problem').
has_part_s_('karp_s_21_np_complete_problems', 'maximum_cut').
has_part_s_('karp_s_21_np_complete_problems', 'feedback_vertex_set').
has_part_s_('karp_s_21_np_complete_problems', 'hamiltonian_path_problem').
has_part_s_('karp_s_21_np_complete_problems', 'feedback_arc_set').
has_part_s_('karp_s_21_np_complete_problems', 'chromatic_number').
has_part_s_('karp_s_21_np_complete_problems', 'set_packing').
has_part_s_('karp_s_21_np_complete_problems', 'set_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', 'clique_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', 'steiner_tree_problem').
has_part_s_('karp_s_21_np_complete_problems', '3_satisfiability_problem').
has_part_s_('karp_s_21_np_complete_problems', 'vertex_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', '3_dimensional_matching').
has_part_s_('karp_s_21_np_complete_problems', 'clique_problem').
has_part_s_('karp_s_21_np_complete_problems', 'partition_problem').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('karp_s_21_np_complete_problems', 'boolean_satisfiability_problem').
has_part_s_('karp_s_21_np_complete_problems', 'job_shop_scheduling').
has_part_s_('karp_s_21_np_complete_problems', 'exact_cover').
has_part_s_('karp_s_21_np_complete_problems', 'knapsack_problem').
has_part_s_('karp_s_21_np_complete_problems', 'maximum_cut').
has_part_s_('karp_s_21_np_complete_problems', 'feedback_vertex_set').
has_part_s_('karp_s_21_np_complete_problems', 'hamiltonian_path_problem').
has_part_s_('karp_s_21_np_complete_problems', 'feedback_arc_set').
has_part_s_('karp_s_21_np_complete_problems', 'chromatic_number').
has_part_s_('karp_s_21_np_complete_problems', 'set_packing').
has_part_s_('karp_s_21_np_complete_problems', 'set_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', 'clique_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', 'steiner_tree_problem').
has_part_s_('karp_s_21_np_complete_problems', '3_satisfiability_problem').
has_part_s_('karp_s_21_np_complete_problems', 'vertex_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', '3_dimensional_matching').
has_part_s_('karp_s_21_np_complete_problems', 'clique_problem').
has_part_s_('karp_s_21_np_complete_problems', 'partition_problem').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('outline_of_category_theory', 'category_theory_terminology').
has_part_s_('graduate_studies_in_mathematics', 'toric_varieties').
has_part_s_('karp_s_21_np_complete_problems', 'boolean_satisfiability_problem').
has_part_s_('karp_s_21_np_complete_problems', 'job_shop_scheduling').
has_part_s_('karp_s_21_np_complete_problems', 'exact_cover').
has_part_s_('karp_s_21_np_complete_problems', 'knapsack_problem').
has_part_s_('karp_s_21_np_complete_problems', 'maximum_cut').
has_part_s_('karp_s_21_np_complete_problems', 'feedback_vertex_set').
has_part_s_('karp_s_21_np_complete_problems', 'hamiltonian_path_problem').
has_part_s_('karp_s_21_np_complete_problems', 'feedback_arc_set').
has_part_s_('karp_s_21_np_complete_problems', 'chromatic_number').
has_part_s_('karp_s_21_np_complete_problems', 'set_packing').
has_part_s_('karp_s_21_np_complete_problems', 'set_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', 'clique_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', 'steiner_tree_problem').
has_part_s_('karp_s_21_np_complete_problems', '3_satisfiability_problem').
has_part_s_('karp_s_21_np_complete_problems', 'vertex_cover_problem').
has_part_s_('karp_s_21_np_complete_problems', '3_dimensional_matching').
has_part_s_('karp_s_21_np_complete_problems', 'clique_problem').
has_part_s_('karp_s_21_np_complete_problems', 'partition_problem').
has_part_s_('golden_ratio', 'golden_ratio_in_art').
category_related_to_list('differentiation_rules', 'category_differentiation_rules').
category_related_to_list('differentiation_rules', 'category_differentiation_rules').
category_related_to_list('differentiation_rules', 'category_differentiation_rules').
category_related_to_list('differentiation_rules', 'category_differentiation_rules').
category_related_to_list('differentiation_rules', 'category_differentiation_rules').
category_related_to_list('differentiation_rules', 'category_differentiation_rules').
main_subject('divisibility_rule', 'divisibility').
main_subject('divisibility_rule', 'divisor').
main_subject('index_of_logic_articles', 'logic').
main_subject('divisibility_rule', 'divisibility').
main_subject('divisibility_rule', 'divisor').
main_subject('index_of_logic_articles', 'logic').
main_subject('divisibility_rule', 'divisibility').
main_subject('divisibility_rule', 'divisor').
main_subject('divisibility_rule', 'divisibility').
main_subject('divisibility_rule', 'divisor').
main_subject('divisibility_rule', 'divisibility').
main_subject('divisibility_rule', 'divisor').
main_subject('divisibility_rule', 'divisibility').
main_subject('divisibility_rule', 'divisor').
main_subject('complexities__women_in_mathematics', 'etta_zuber_falconer').
main_subject('gifted__2017_film_', 'intellectual_giftedness').
main_subject('hidden_figures__book_', 'mary_jackson').
main_subject('hidden_figures__book_', 'christine_darden').
main_subject('hidden_figures__book_', 'space_race').
main_subject('hidden_figures__book_', 'dorothy_vaughan').
main_subject('hidden_figures__book_', 'women_in_mathematics').
main_subject('hidden_figures__book_', 'project_mercury').
main_subject('hidden_figures__book_', 'katherine_johnson').
main_subject('pioneering_women_in_american_mathematics', 'women_in_mathematics').
main_subject('power_in_numbers__the_rebel_women_of_mathematics', 'mathematician').
main_subject('power_in_numbers__the_rebel_women_of_mathematics', 'woman').
main_subject('women_in_mathematics__book_', 'women_in_mathematics').
main_subject('journal_of_mathematics_and_the_arts', 'mathematics').
main_subject('a_new_kind_of_science', 'complex_system').
studied_in('divisibility_rule', 'mental_calculation').
studied_in('table_of_lie_groups', 'category_theory').
studied_in('divisibility_rule', 'mental_calculation').
studied_in('table_of_lie_groups', 'category_theory').
topic_s_main_template('table_of_divisors', 'q26235059').
topic_s_main_template('table_of_divisors', 'q26235059').
topic_s_main_template('table_of_divisors', 'q26235059').
topic_s_main_template('table_of_divisors', 'q26235059').
topic_s_main_template('table_of_divisors', 'q26235059').
topic_s_main_template('table_of_divisors', 'q26235059').
topic_s_main_template('ruth_lyttle_satter_prize_in_mathematics', 'template_ruth_lyttle_satter_prize_in_mathematics_recipients').
topic_s_main_template('mathematics_of_paper_folding', 'template_mathematics_of_paper_folding').
publisher('graduate_studies_in_mathematics', 'american_mathematical_society').
publisher('graduate_studies_in_mathematics', 'american_mathematical_society').
publisher('graduate_studies_in_mathematics', 'american_mathematical_society').
publisher('hidden_figures__book_', 'william_morrow_and_company').
publisher('fermat_kitchen', 'kodansha_comics').
publisher('science_fell_in_love__so_i_tried_to_prove_it', 'meteor_comics').
publisher('s_gaku_golden', 'young_animal_comics').
publisher('journal_of_mathematics_and_the_arts', 'taylor___francis').
publisher('a_new_kind_of_science', 'wolfram_research').
language_of_work_or_name('graduate_studies_in_mathematics', 'english').
language_of_work_or_name('graduate_texts_in_mathematics', 'english').
language_of_work_or_name('graduate_studies_in_mathematics', 'english').
language_of_work_or_name('graduate_texts_in_mathematics', 'english').
language_of_work_or_name('graduate_studies_in_mathematics', 'english').
language_of_work_or_name('graduate_texts_in_mathematics', 'english').
language_of_work_or_name('complexities__women_in_mathematics', 'english').
language_of_work_or_name('hidden_figures__book_', 'english').
language_of_work_or_name('pioneering_women_in_american_mathematics', 'english').
language_of_work_or_name('women_in_mathematics__book_', 'english').
language_of_work_or_name('fermat_kitchen', 'japanese').
language_of_work_or_name('science_fell_in_love__so_i_tried_to_prove_it', 'japanese').
language_of_work_or_name('s_gaku_golden', 'japanese').
language_of_work_or_name('s_ji_de_asobo', 'japanese').
language_of_work_or_name('journal_of_mathematics_and_the_arts', 'english').
language_of_work_or_name('m__c__escher__visions_of_symmetry', 'english').
language_of_work_or_name('making_mathematics_with_needlework', 'english').
language_of_work_or_name('a_new_kind_of_science', 'english').
country_of_origin('graduate_studies_in_mathematics', 'united_states').
country_of_origin('graduate_texts_in_mathematics', 'united_states').
country_of_origin('graduate_studies_in_mathematics', 'united_states').
country_of_origin('graduate_texts_in_mathematics', 'united_states').
country_of_origin('graduate_studies_in_mathematics', 'united_states').
country_of_origin('graduate_texts_in_mathematics', 'united_states').
country_of_origin('hidden_figures__book_', 'united_states').
country_of_origin('fermat_kitchen', 'japan').
country_of_origin('science_fell_in_love__so_i_tried_to_prove_it', 'japan').
country_of_origin('s_gaku_golden', 'japan').
country_of_origin('s_ji_de_asobo', 'japan').
country_of_origin('journal_of_mathematics_and_the_arts', 'united_kingdom').
country_of_origin('a_new_kind_of_science', 'united_states').
named_after('karp_s_21_np_complete_problems', 'np_complete').
named_after('karp_s_21_np_complete_problems', 'richard_m__karp').
named_after('karp_s_21_np_complete_problems', 'np_complete').
named_after('karp_s_21_np_complete_problems', 'richard_m__karp').
named_after('karp_s_21_np_complete_problems', 'np_complete').
named_after('karp_s_21_np_complete_problems', 'richard_m__karp').
named_after('krieger_nelson_prize', 'cecilia_krieger').
named_after('krieger_nelson_prize', 'evelyn_nelson').
named_after('noether_lecture', 'emmy_noether').
named_after('ruth_lyttle_satter_prize_in_mathematics', 'ruth_lyttle_satter').
named_after('fermat_kitchen', 'fermat_s_last_theorem').
described_by_source('karp_s_21_np_complete_problems', 'reducibility_among_combinatorial_problems').
described_by_source('karp_s_21_np_complete_problems', 'karp_richard_m___reducibility_among_combinatorial_problems__complexity_of_computer_computations__proceedings_of_a_symposium_on_the_complexity_of_computer_computations__held_march_20_22__1972__at_the_ibm_thomas_j__watson_center__yorktown_heights__new').
described_by_source('karp_s_21_np_complete_problems', 'reducibility_among_combinatorial_problems').
described_by_source('karp_s_21_np_complete_problems', 'karp_richard_m___reducibility_among_combinatorial_problems__complexity_of_computer_computations__proceedings_of_a_symposium_on_the_complexity_of_computer_computations__held_march_20_22__1972__at_the_ibm_thomas_j__watson_center__yorktown_heights__new').
described_by_source('karp_s_21_np_complete_problems', 'q110971675').
described_by_source('karp_s_21_np_complete_problems', 'q61248534').
described_by_source('anamorphosis', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('anamorphosis', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('anamorphosis', 'encyclopedic_lexicon').
described_by_source('anamorphosis', 'q131308011').
described_by_source('golden_ratio', 'armenian_soviet_encyclopedia__vol__8').
described_by_source('golden_ratio', 'granat_encyclopedic_dictionary').
described_by_source('golden_ratio', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
creator('karp_s_21_np_complete_problems', 'richard_m__karp').
creator('karp_s_21_np_complete_problems', 'richard_m__karp').
creator('karp_s_21_np_complete_problems', 'richard_m__karp').
creator('equals_pi', 'jean_michel_basquiat').
cardinality_of_this_set('karp_s_21_np_complete_problems', '21').
cardinality_of_this_set('karp_s_21_np_complete_problems', '21').
cardinality_of_this_set('karp_s_21_np_complete_problems', '21').
part_of('vector_algebra_relations', 'euclidean_three_dimensional_space').
part_of('vector_algebra_relations', 'vector_algebra').
part_of('vector_algebra_relations', 'euclidean_three_dimensional_space').
part_of('vector_algebra_relations', 'vector_algebra').
part_of('vector_algebra_relations', 'vector_algebra').
part_of('vector_algebra_relations', 'euclidean_three_dimensional_space').
category_for_eponymous_categories('mathematician', 'category_wikipedia_categories_named_after_mathematicians').
category_for_eponymous_categories('mathematician', 'category_wikipedia_categories_named_after_mathematicians').
doctoral_student('nicholas_a__m__monk', 'karen_mary_page').
doctoral_student('nicholas_a__m__monk', 'sabine_schamberg').
doctoral_student('nicholas_a__m__monk', 'karen_mary_page').
doctoral_student('nicholas_a__m__monk', 'sabine_schamberg').
given_name('nicholas_a__m__monk', 'alexander').
given_name('nicholas_a__m__monk', 'nicholas').
given_name('nicholas_a__m__monk', 'nick').
given_name('harold_ramkissoon', 'harold').
given_name('nicholas_a__m__monk', 'alexander').
given_name('nicholas_a__m__monk', 'nicholas').
given_name('nicholas_a__m__monk', 'nick').
given_name('harold_ramkissoon', 'harold').
given_name('sarah_marie_belcastro', 'q119411672').
sex_or_gender('nicholas_a__m__monk', 'male').
sex_or_gender('harold_ramkissoon', 'male').
sex_or_gender('nicholas_a__m__monk', 'male').
sex_or_gender('harold_ramkissoon', 'male').
sex_or_gender('hideki_omori', 'male').
sex_or_gender('sarah_marie_belcastro', 'female').
educated_at('nicholas_a__m__monk', 'university_of_london').
educated_at('nicholas_a__m__monk', 'university_of_london').
educated_at('hideki_omori', 'university_of_tokyo').
educated_at('hideki_omori', 'q11453677').
educated_at('sarah_marie_belcastro', 'university_of_michigan').
doctoral_advisor('nicholas_a__m__monk', 'basil_j__hiley').
doctoral_advisor('nicholas_a__m__monk', 'basil_j__hiley').
doctoral_advisor('sarah_marie_belcastro', 'igor_dolgachev').
family_name('nicholas_a__m__monk', 'monk').
family_name('harold_ramkissoon', 'ramkissoon').
family_name('nicholas_a__m__monk', 'monk').
family_name('harold_ramkissoon', 'ramkissoon').
family_name('sarah_marie_belcastro', 'belcastro').
employer('nicholas_a__m__monk', 'university_of_sheffield').
employer('nicholas_a__m__monk', 'african_institute_for_mathematical_sciences_ghana').
employer('nicholas_a__m__monk', 'university_of_sheffield').
employer('nicholas_a__m__monk', 'african_institute_for_mathematical_sciences_ghana').
employer('hideki_omori', 'tokyo_university_of_science').
occupation('nicholas_a__m__monk', 'researcher').
occupation('harold_ramkissoon', 'applied_mathematician').
occupation('nicholas_a__m__monk', 'researcher').
occupation('harold_ramkissoon', 'applied_mathematician').
occupation('hideki_omori', 'mathematician').
occupation('sarah_marie_belcastro', 'textile_artist').
occupation('sarah_marie_belcastro', 'mathematician').
child('nicholas_a__m__monk', 'thomas_huw_monk').
child('nicholas_a__m__monk', 'jacob_alexander_monk').
child('nicholas_a__m__monk', 'oscar_llewelyn_monk').
child('nicholas_a__m__monk', 'thomas_huw_monk').
child('nicholas_a__m__monk', 'jacob_alexander_monk').
child('nicholas_a__m__monk', 'oscar_llewelyn_monk').
spouse('nicholas_a__m__monk', 'tanya_whitfield').
spouse('nicholas_a__m__monk', 'tanya_whitfield').
member_of_political_party('harold_ramkissoon', 'independent_politician').
member_of_political_party('harold_ramkissoon', 'independent_politician').
country_of_citizenship('harold_ramkissoon', 'trinidad_and_tobago').
country_of_citizenship('harold_ramkissoon', 'trinidad_and_tobago').
country_of_citizenship('hideki_omori', 'japan').
country_of_citizenship('sarah_marie_belcastro', 'united_states').
place_of_birth('harold_ramkissoon', 'tabaquite').
place_of_birth('harold_ramkissoon', 'tabaquite').
place_of_birth('sarah_marie_belcastro', 'san_diego').
field_of_this_occupation('mathematician', 'mathematics').
has_list('mathematician', 'lists_of_mathematicians').
has_list('mathematics_and_art', 'list_of_mathematical_artists').
uses('mathematician', 'mathematical_terminology').
studied_by('divisibility_rule', 'mental_calculation').
studied_by('divisibility_rule', 'mental_calculation').
studied_by('divisibility_rule', 'mental_calculation').
studied_by('divisibility_rule', 'mental_calculation').
studied_by('table_of_lie_groups', 'category_theory').
sibling('hideki_omori', 'rei__mori').
sibling('hideki_omori', 'akemi__mori').
country('timeline_of_women_in_mathematics_in_the_united_states', 'united_states').
country('association_for_women_in_mathematics', 'united_states').
country('center_for_women_in_mathematics', 'united_states').
country('european_women_in_mathematics', 'finland').
country('femmes_et_math_matiques', 'france').
country('graduate_women_in_science', 'united_states').
country('krieger_nelson_prize', 'canada').
country('noether_lecture', 'united_states').
conferred_by('anne_bennett_prize', 'london_mathematical_society').
conferred_by('krieger_nelson_prize', 'canadian_mathematical_society').
conferred_by('ruth_lyttle_satter_prize_in_mathematics', 'american_mathematical_society').
founded_by('association_for_women_in_mathematics', 'annie_selden').
founded_by('association_for_women_in_mathematics', 'alice_t__schafer').
founded_by('association_for_women_in_mathematics', 'mary_w__gray').
founded_by('association_for_women_in_mathematics', 'gloria_olive').
founded_by('ruth_lyttle_satter_prize_in_mathematics', 'joan_birman').
field_of_work('association_for_women_in_mathematics', 'mathematics').
field_of_work('association_for_women_in_mathematics', 'gender_equality').
field_of_work('caucus_for_women_in_statistics_and_data_science', 'statistics').
field_of_work('women_in_stem', 'science__technology__engineering__and_mathematics').
headquarters_location('association_for_women_in_mathematics', 'providence').
headquarters_location('european_women_in_mathematics', 'finland').
headquarters_location('the_bridges_organization', 'kansas').
located_in_the_administrative_territorial_entity('association_for_women_in_mathematics', 'fairfax').
located_in_the_administrative_territorial_entity('european_women_in_mathematics', 'europe').
located_in_the_administrative_territorial_entity('graduate_women_in_science', 'minneapolis').
chairperson('association_for_women_in_mathematics', 'talitha_washington').
chairperson('association_for_women_in_mathematics', 'ami_radunskaya').
chairperson('association_for_women_in_mathematics', 'carolyn_s__gordon').
chairperson('association_for_women_in_mathematics', 'kathryn_leonard').
chairperson('association_for_women_in_mathematics', 'jill_p__mesirov').
chairperson('association_for_women_in_mathematics', 'judith_roitman').
chairperson('association_for_women_in_mathematics', 'chuu_lian_terng').
chairperson('association_for_women_in_mathematics', 'mary_w__gray').
chairperson('association_for_women_in_mathematics', 'bhama_srinivasan').
chairperson('association_for_women_in_mathematics', 'alice_t__schafer').
chairperson('association_for_women_in_mathematics', 'jean_taylor').
chairperson('association_for_women_in_mathematics', 'cathy_kessel').
chairperson('association_for_women_in_mathematics', 'ruth_charney').
chairperson('association_for_women_in_mathematics', 'sylvia_wiegand').
chairperson('association_for_women_in_mathematics', 'kristin_lauter').
chairperson('association_for_women_in_mathematics', 'carol_s__wood').
chairperson('association_for_women_in_mathematics', 'cora_sadosky').
chairperson('european_women_in_mathematics', 'carola_bibiane_sch_nlieb').
chairperson('femmes_et_math_matiques', 'v_ronique_slovacek_chauveau').
chairperson('femmes_et_math_matiques', 'christine_charretton').
chairperson('femmes_et_math_matiques', 'julianne_unterberger').
chairperson('femmes_et_math_matiques', 'fran_oise_delon').
chairperson('femmes_et_math_matiques', 'v_ronique_lizan').
chairperson('femmes_et_math_matiques', 'catherine_goldstein').
chairperson('femmes_et_math_matiques', 'sylvie_paycha').
chairperson('femmes_et_math_matiques', 'colette_guillop_').
chairperson('femmes_et_math_matiques', 'marie_fran_oise_roy').
chairperson('femmes_et_math_matiques', 'laurence_broze').
chairperson('femmes_et_math_matiques', 'anne_boy_').
chairperson('femmes_et_math_matiques', 'mich_le_audin').
position_held_by_head_of_the_organization('association_for_women_in_mathematics', 'president_of_the_association_for_women_in_mathematics').
social_media_followers('association_for_women_in_mathematics', '4574').
social_media_followers('femmes_et_math_matiques', '3271').
social_media_followers('femmes_et_math_matiques', '3689').
social_media_followers('graduate_women_in_science', '2549').
social_media_followers('graduate_women_in_science', '2245').
social_media_followers('hidden_figures', '24267').
social_media_followers('hidden_figures', '22680').
social_media_followers('hidden_figures', '21619').
social_media_followers('a_new_kind_of_science', '65698').
social_media_followers('a_new_kind_of_science', '85861').
social_media_followers('a_new_kind_of_science', '99538').
social_media_followers('a_new_kind_of_science', '74298').
member_count('european_women_in_mathematics', '500').
member_of('european_women_in_mathematics', 'european_mathematical_society').
legal_form('femmes_et_math_matiques', 'declared_association').
industry('femmes_et_math_matiques', 'other_voluntary_membership_organizations__france_').
industry('femmes_et_math_matiques', 'higher_education').
corporate_officer('femmes_et_math_matiques', 'laurence_broze').
cast_member('gifted__2017_film_', 'mckenna_grace').
cast_member('gifted__2017_film_', 'glenn_e__plummer').
cast_member('gifted__2017_film_', 'keir_o_donnell').
cast_member('gifted__2017_film_', 'julie_ann_emery').
cast_member('gifted__2017_film_', 'octavia_spencer').
cast_member('gifted__2017_film_', 'jenny_slate').
cast_member('gifted__2017_film_', 'elizabeth_marvel').
cast_member('gifted__2017_film_', 'chris_evans').
cast_member('gifted__2017_film_', 'john_m__jackson').
cast_member('gifted__2017_film_', 'percy_hynes_white').
cast_member('gifted__2017_film_', 'lindsay_duncan').
cast_member('gifted__2017_film_', 'john_finn').
screenwriter('gifted__2017_film_', 'tom_flynn').
genre('gifted__2017_film_', 'drama_film').
genre('hidden_figures__book_', 'non_fiction').
genre('fermat_kitchen', 'cooking_manga').
genre('science_fell_in_love__so_i_tried_to_prove_it', 'romantic_comedy_anime_and_manga').
genre('equals_pi', 'neo_expressionism').
genre('a_new_kind_of_science', 'non_fiction').
composer('gifted__2017_film_', 'rob_simonsen').
director('gifted__2017_film_', 'marc_webb').
producer('gifted__2017_film_', 'andy_cohen').
different_from('gifted__2017_film_', 'the_gifted').
different_from('golden_ratio', 'q9393496').
incaa_film_rating('gifted__2017_film_', '_13').
production_company('gifted__2017_film_', 'searchlight_pictures').
distribution_format('gifted__2017_film_', 'video_on_demand').
kijkwijzer_rating('gifted__2017_film_', 'al').
kijkwijzer_rating('gifted__2017_film_', '6').
mpa_film_rating('gifted__2017_film_', 'pg_13').
assessment('gifted__2017_film_', 'bechdel_test').
assessment('hidden_figures', 'bechdel_test').
assessment('hidden_figures', 'mako_mori_test').
assessment('hidden_figures', 'waithe_test').
assessment('hidden_figures', 'landau_test').
film_editor('gifted__2017_film_', 'bill_pankow').
rcq_classification('hidden_figures', 'g').
medier_det_rating('hidden_figures', 'suitable_for_a_general_audience').
ifco_rating('hidden_figures', 'pg').
author('hidden_figures__book_', 'margot_lee_shetterly').
author('pioneering_women_in_american_mathematics', 'judy_green').
author('pioneering_women_in_american_mathematics', 'jeanne_laduke').
author('power_in_numbers__the_rebel_women_of_mathematics', 'talithia_williams').
author('fermat_kitchen', 'yugo_kobayashi').
author('science_fell_in_love__so_i_tried_to_prove_it', 'arihred_yamamoto').
author('s_ji_de_asobo', 'murako_kinuta').
author('trisatika', 'sridhara').
author('m__c__escher__visions_of_symmetry', 'doris_schattschneider').
author('a_new_kind_of_science', 'stephen_wolfram').
has_edition_or_translation('hidden_figures__book_', 'hidden_figures__the_american_dream_and_the_untold_story_of_the_black_women_mathematicians_who_helped_win_the_space_race').
has_edition_or_translation('a_new_kind_of_science', 'a_new_kind_of_science').
derivative_work('hidden_figures__book_', 'hidden_figures').
derivative_work('hidden_figures__book_', 'hidden_figures').
derivative_work('fermat_kitchen', 'fermat_no_ry_ri').
derivative_work('fermat_kitchen', 'fermat_no_ry_ri').
derivative_work('science_fell_in_love__so_i_tried_to_prove_it', 'science_fell_in_love__so_i_tried_to_prove_it').
narrative_location('hidden_figures__book_', 'florida').
category_for_recipients_of_this_award('krieger_nelson_prize', 'category_laureates_of_the_krieger_nelson_prize').
category_for_recipients_of_this_award('noether_lecture', 'category_noether_lecture_recipients').
category_for_recipients_of_this_award('ruth_lyttle_satter_prize_in_mathematics', 'category_ruth_lyttle_satter_prize_in_mathematics_recipients').
winner('noether_lecture', 'raman_parimala').
winner('noether_lecture', 'fan_chung').
winner('noether_lecture', 'susan_montgomery').
winner('noether_lecture', 'alexandra_bellow').
winner('noether_lecture', 'sun_yung_alice_chang').
winner('noether_lecture', 'joan_birman').
winner('noether_lecture', 'linda_preiss_rothschild').
winner('noether_lecture', 'barbara_keyfitz').
winner('noether_lecture', 'judith_d__sally').
winner('noether_lecture', 'olga_arsenievna_oleinik').
winner('noether_lecture', 'mary_wheeler').
winner('noether_lecture', 'nancy_kopell').
winner('noether_lecture', 'lenore_blum').
winner('noether_lecture', 'carolyn_s__gordon').
winner('noether_lecture', 'karen_keskulla_uhlenbeck').
winner('noether_lecture', 'bhama_srinivasan').
winner('noether_lecture', 'linda_keen').
winner('noether_lecture', 'jane_cronin_scanlon').
winner('noether_lecture', 'margaret_h__wright').
winner('noether_lecture', 'dusa_mcduff').
winner('noether_lecture', 'jean_taylor').
winner('noether_lecture', 'jessie_macwilliams').
winner('noether_lecture', 'olga_taussky_todd').
winner('noether_lecture', 'svetlana_katok').
winner('noether_lecture', 'lesley_sibner').
winner('noether_lecture', 'lai_sang_young').
winner('noether_lecture', 'ingrid_daubechies').
winner('noether_lecture', 'winnie_li').
winner('noether_lecture', 'krystyna_kuperberg').
winner('noether_lecture', 'karen_vogtmann').
winner('noether_lecture', 'audrey_terras').
winner('noether_lecture', 'julia_hall_bowman_robinson').
winner('noether_lecture', 'cathleen_synge_morawetz').
winner('noether_lecture', 'yvonne_choquet_bruhat').
winner('noether_lecture', 'mary_ellen_rudin').
winner('noether_lecture', 'georgia_benkart').
number_of_pages('power_in_numbers__the_rebel_women_of_mathematics', '224').
published_in('fermat_kitchen', 'monthly_sh_nen_magazine').
published_in('s_gaku_golden', 'young_animal_zero').
published_in('s_ji_de_asobo', 'flowers').
illustrator('fermat_kitchen', 'yugo_kobayashi').
intended_public('fermat_kitchen', 'sh_nen').
intended_public('science_fell_in_love__so_i_tried_to_prove_it', 'seinen').
intended_public('s_gaku_golden', 'seinen').
intended_public('s_ji_de_asobo', 'josei').
languages_spoken__written_or_signed('sarah_marie_belcastro', 'english').
has_use('golden_ratio', 'mathematics_and_architecture').
has_use('golden_ratio', 'mathematics_and_art').
numeric_value('golden_ratio', '1_6180339887498948482045868343656381177203091798057628621354486227052604628189024497072072041893911374847540880753868917521266').
notation('golden_ratio', '___').
indexed_in_bibliographic_review('journal_of_mathematics_and_the_arts', 'scopus').
partially_coincident_with('mathematical_beauty', 'elegance').
is_the_study_of('mathematics_of_paper_folding', 'origami').
