instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('forest_404', 'podcast_show').
instance_of('lenten_ys_come_with_love_to_toune', 'poem').
instance_of('swamp_legend', 'painting').
instance_of('index_of_conservation_articles', 'wikimedia_list_article').
instance_of('iucn_protected_area_categories', 'classification').
instance_of('new_7_wonders_of_nature', 'wonders_of_the_world').
instance_of('new_7_wonders_of_nature', 'seven_wonders').
instance_of('seven_natural_wonders', 'television_series').
instance_of('seven_wonders_of_canada', 'wikimedia_list_article').
instance_of('portal_world', 'wikimedia_portal').
instance_of('outline_of_earth', 'wikimedia_outline_article').
instance_of('earth_s_circumference', 'circumference').
instance_of('earth_s_circumference', 'unit_of_length').
instance_of('demographics_of_the_world', 'demographics_of_country_or_region').
instance_of('earth_s_energy_budget', 'scientific_model').
instance_of('earth_s_internal_heat_budget', 'heat_flow_rate').
instance_of('future_of_earth', 'future').
instance_of('gaia_hypothesis', 'scientific_hypothesis').
instance_of('geological_history_of_earth', 'aspect_of_history').
instance_of('history_of_earth', 'aspect_of_history').
instance_of('jaramillo_reversal', 'geomagnetic_reversal').
instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('forest_404', 'podcast_show').
instance_of('lenten_ys_come_with_love_to_toune', 'poem').
instance_of('swamp_legend', 'painting').
instance_of('index_of_conservation_articles', 'wikimedia_list_article').
instance_of('iucn_protected_area_categories', 'classification').
instance_of('new_7_wonders_of_nature', 'wonders_of_the_world').
instance_of('new_7_wonders_of_nature', 'seven_wonders').
instance_of('seven_natural_wonders', 'television_series').
instance_of('seven_wonders_of_canada', 'wikimedia_list_article').
instance_of('portal_world', 'wikimedia_portal').
instance_of('outline_of_earth', 'wikimedia_outline_article').
instance_of('earth_s_circumference', 'circumference').
instance_of('earth_s_circumference', 'unit_of_length').
instance_of('demographics_of_the_world', 'demographics_of_country_or_region').
instance_of('earth_s_energy_budget', 'scientific_model').
instance_of('earth_s_internal_heat_budget', 'heat_flow_rate').
instance_of('future_of_earth', 'future').
instance_of('gaia_hypothesis', 'scientific_hypothesis').
instance_of('geological_history_of_earth', 'aspect_of_history').
instance_of('history_of_earth', 'aspect_of_history').
instance_of('jaramillo_reversal', 'geomagnetic_reversal').
instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('the_cloud__poem_', 'poem').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('forest_404', 'podcast_show').
instance_of('lenten_ys_come_with_love_to_toune', 'poem').
instance_of('swamp_legend', 'painting').
instance_of('index_of_conservation_articles', 'wikimedia_list_article').
instance_of('iucn_protected_area_categories', 'classification').
instance_of('new_7_wonders_of_nature', 'wonders_of_the_world').
instance_of('new_7_wonders_of_nature', 'seven_wonders').
instance_of('seven_natural_wonders', 'television_series').
instance_of('seven_wonders_of_canada', 'wikimedia_list_article').
instance_of('portal_world', 'wikimedia_portal').
instance_of('outline_of_earth', 'wikimedia_outline_article').
instance_of('earth_s_circumference', 'circumference').
instance_of('earth_s_circumference', 'unit_of_length').
instance_of('demographics_of_the_world', 'demographics_of_country_or_region').
instance_of('earth_s_energy_budget', 'scientific_model').
instance_of('earth_s_internal_heat_budget', 'heat_flow_rate').
instance_of('future_of_earth', 'future').
instance_of('gaia_hypothesis', 'scientific_hypothesis').
instance_of('geological_history_of_earth', 'aspect_of_history').
instance_of('history_of_earth', 'aspect_of_history').
instance_of('jaramillo_reversal', 'geomagnetic_reversal').
instance_of('earth_mass', 'unit_of_mass').
instance_of('mediocrity_principle', 'q126168115').
instance_of('earth_s_orbit', 'motions_of_the_earth').
instance_of('earth_s_orbit', 'heliocentric_orbit').
instance_of('earth_s_orbit', 'planetary_orbit').
instance_of('origin_of_water_on_earth', 'research_question').
instance_of('origin_of_water_on_earth', 'source_type').
instance_of('purple_earth_hypothesis', 'hypothesis').
instance_of('earth_radius', 'radius').
instance_of('rare_earth_hypothesis', 'scientific_hypothesis').
instance_of('rare_earth_hypothesis', 'solution').
instance_of('earth_s_rotation', 'motions_of_the_earth').
instance_of('earth_s_rotation', 'rotation').
instance_of('earth_in_science_fiction', 'real_planet_in_a_fiction_work').
instance_of('solar_equator', 'circle_of_latitude').
instance_of('spaceship_earth', 'concept').
instance_of('spherical_earth', 'scientific_theory').
instance_of('spherical_earth', 'mathematical_model').
instance_of('terrestrial_time', 'time_standard').
instance_of('tipping_points_in_the_climate_system', 'window_of_opportunity').
instance_of('transit_of_earth_from_mars', 'astronomical_transit').
instance_of('world', 'ambiguous_wikidata_item').
instance_of('world', 'philosophical_concept').
instance_of('binding_energy', 'form_of_energy').
instance_of('bioenergetics', 'branch_of_biology').
instance_of('bioenergetics', 'branch_of_chemistry').
instance_of('buchdahl_s_theorem', 'theorem').
instance_of('conservation_of_energy', 'conservation_law').
instance_of('conservation_of_energy', 'physical_law').
instance_of('dark_energy', 'scientific_hypothesis').
instance_of('dark_energy', 'form_of_energy').
instance_of('interaction_energy', 'form_of_energy').
instance_of('internal_energy', 'form_of_energy').
instance_of('josephson_effect', 'macroscopic_quantum_phenomena').
instance_of('josephson_effect', 'physical_phenomenon').
instance_of('kilocalorie_per_mole', 'unit_of_molar_energy').
instance_of('mass_energy_equivalence', 'mathematical_concept').
instance_of('mass_energy_equivalence', 'concept_in_physics').
instance_of('mechanical_energy', 'form_of_energy').
instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('the_cloud__poem_', 'poem').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('the_cloud__poem_', 'poem').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('the_cloud__poem_', 'poem').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('forest_404', 'podcast_show').
instance_of('lenten_ys_come_with_love_to_toune', 'poem').
instance_of('swamp_legend', 'painting').
instance_of('index_of_conservation_articles', 'wikimedia_list_article').
instance_of('natural_science', 'academic_discipline').
instance_of('natural_science', 'branch_of_science').
instance_of('outline_of_natural_science', 'wikimedia_outline_article').
instance_of('anthropocene_working_group', 'working_group').
instance_of('imperial_college_faculty_of_natural_sciences', 'faculty').
instance_of('natural_sciences_collections_association', 'charitable_organization').
instance_of('natural_sciences_collections_association', 'organization').
instance_of('natural_sciences_collections_association', 'learned_society').
instance_of('rangeland_management', 'academic_discipline').
instance_of('rangeland_management', 'field_of_study').
instance_of('rangeland_management', 'academic_major').
instance_of('rangeland_management', 'field_of_study').
instance_of('uprrp_college_of_natural_sciences', 'university').
instance_of('become_ocean', 'musical_work_composition').
instance_of('the_cloud__poem_', 'poem').
instance_of('des_canyons_aux__toiles___', 'musical_work_composition').
instance_of('fe__video_game_', 'video_game').
instance_of('forest_404', 'podcast_show').
instance_of('lenten_ys_come_with_love_to_toune', 'poem').
instance_of('swamp_legend', 'painting').
instance_of('index_of_conservation_articles', 'wikimedia_list_article').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_regions_of_germany', 'natural_region').
subclass_of('iucn_protected_area_categories', 'class').
subclass_of('earth_science', 'natural_science').
subclass_of('asteroid_impact_avoidance', 'avoidance').
subclass_of('asteroid_impact_avoidance', 'defense').
subclass_of('day_length_fluctuations', 'change').
subclass_of('deep_carbon_cycle', 'carbon_cycle').
subclass_of('demographics_of_the_world', 'demographics').
subclass_of('figure_of_the_earth', 'shape').
subclass_of('geographical_distance', 'distance').
subclass_of('gravity_of_earth', 'gravitational_acceleration').
subclass_of('history_of_earth', 'history').
subclass_of('location_of_earth', 'physical_location').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_regions_of_germany', 'natural_region').
subclass_of('iucn_protected_area_categories', 'class').
subclass_of('earth_science', 'natural_science').
subclass_of('asteroid_impact_avoidance', 'avoidance').
subclass_of('asteroid_impact_avoidance', 'defense').
subclass_of('day_length_fluctuations', 'change').
subclass_of('deep_carbon_cycle', 'carbon_cycle').
subclass_of('demographics_of_the_world', 'demographics').
subclass_of('figure_of_the_earth', 'shape').
subclass_of('geographical_distance', 'distance').
subclass_of('gravity_of_earth', 'gravitational_acceleration').
subclass_of('history_of_earth', 'history').
subclass_of('location_of_earth', 'physical_location').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_regions_of_germany', 'natural_region').
subclass_of('iucn_protected_area_categories', 'class').
subclass_of('earth_science', 'natural_science').
subclass_of('asteroid_impact_avoidance', 'avoidance').
subclass_of('asteroid_impact_avoidance', 'defense').
subclass_of('day_length_fluctuations', 'change').
subclass_of('deep_carbon_cycle', 'carbon_cycle').
subclass_of('demographics_of_the_world', 'demographics').
subclass_of('figure_of_the_earth', 'shape').
subclass_of('geographical_distance', 'distance').
subclass_of('gravity_of_earth', 'gravitational_acceleration').
subclass_of('history_of_earth', 'history').
subclass_of('location_of_earth', 'physical_location').
subclass_of('natural_environment', 'environment').
subclass_of('natural_environment', 'physico_geographical_object').
subclass_of('earth_phase', 'planetary_phase').
subclass_of('precession', 'rotation').
subclass_of('earth_in_science_fiction', 'fictional_planet').
subclass_of('earth_s_shadow', 'atmospheric_optical_phenomenon').
subclass_of('subsolar_point', 'geographic_location').
subclass_of('substorm', 'geomagnetic_storm').
subclass_of('near_earth_supernova', 'supernova').
subclass_of('tipping_points_in_the_climate_system', 'tipping_point').
subclass_of('water_distribution_on_earth', 'spatial_distribution').
subclass_of('world', 'material_entity').
subclass_of('binding_energy', 'physical_quantity').
subclass_of('binding_energy', 'potential_energy').
subclass_of('dark_energy', 'class').
subclass_of('dark_energy', 'field').
subclass_of('energy_current', 'flux').
subclass_of('energy_current', 'energy_transfer').
subclass_of('energy_current', 'physical_quantity').
subclass_of('energy_current', 'current').
subclass_of('energy_functional', 'functional').
subclass_of('energy_transformation', 'energy_source').
subclass_of('energy_transformation', 'transformation').
subclass_of('energy_transformation', 'process').
subclass_of('enthalpy', 'thermodynamic_potential').
subclass_of('enthalpy', 'energy').
subclass_of('gravitational_potential', 'scalar_quantity').
subclass_of('gravitational_potential', 'scalar_potential').
subclass_of('gravitational_potential', 'physical_quantity').
subclass_of('interaction_energy', 'energy').
subclass_of('internal_energy', 'chemical_quantity').
subclass_of('internal_energy', 'extensive_quantity').
subclass_of('internal_energy', 'physical_quantity').
subclass_of('internal_energy', 'thermodynamic_potential').
subclass_of('internal_energy', 'energy').
subclass_of('internal_energy', 'state_function').
subclass_of('invariant_mass', 'energy').
subclass_of('invariant_mass', 'mass').
subclass_of('invariant_mass', 'physical_quantity').
subclass_of('mechanical_energy', 'energy').
subclass_of('mechanical_energy', 'physical_quantity').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_regions_of_germany', 'natural_region').
subclass_of('natural_science', 'science').
subclass_of('rangeland_management', 'natural_resource_management').
subclass_of('rangeland_management', 'ecosystem_management').
subclass_of('natural_regions_of_germany', 'natural_region').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_regions_of_germany', 'category_natural_regions_of_germany').
topic_s_main_category('iucn_protected_area_categories', 'category_protected_areas_by_world_conservation_union_category').
topic_s_main_category('new_7_wonders_of_nature', 'category_new_7_wonders_of_nature').
topic_s_main_category('earth_science', 'category_earth_sciences').
topic_s_main_category('figure_of_the_earth', 'category_curvature_of_the_earth').
topic_s_main_category('geological_history_of_earth', 'category_geological_history_of_earth').
topic_s_main_category('history_of_earth', 'category_history_of_the_earth').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_regions_of_germany', 'category_natural_regions_of_germany').
topic_s_main_category('iucn_protected_area_categories', 'category_protected_areas_by_world_conservation_union_category').
topic_s_main_category('new_7_wonders_of_nature', 'category_new_7_wonders_of_nature').
topic_s_main_category('earth_science', 'category_earth_sciences').
topic_s_main_category('figure_of_the_earth', 'category_curvature_of_the_earth').
topic_s_main_category('geological_history_of_earth', 'category_geological_history_of_earth').
topic_s_main_category('history_of_earth', 'category_history_of_the_earth').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_regions_of_germany', 'category_natural_regions_of_germany').
topic_s_main_category('iucn_protected_area_categories', 'category_protected_areas_by_world_conservation_union_category').
topic_s_main_category('new_7_wonders_of_nature', 'category_new_7_wonders_of_nature').
topic_s_main_category('earth_science', 'category_earth_sciences').
topic_s_main_category('figure_of_the_earth', 'category_curvature_of_the_earth').
topic_s_main_category('geological_history_of_earth', 'category_geological_history_of_earth').
topic_s_main_category('history_of_earth', 'category_history_of_the_earth').
topic_s_main_category('mediocrity_principle', 'q32692914').
topic_s_main_category('natural_environment', 'category_natural_environment').
topic_s_main_category('precession', 'category_precession').
topic_s_main_category('earth_in_science_fiction', 'category_fiction_about_earth').
topic_s_main_category('spherical_earth', 'category_spherical_earth').
topic_s_main_category('world', 'category_world').
topic_s_main_category('energy', 'category_energy').
topic_s_main_category('binding_energy', 'category_binding_energy').
topic_s_main_category('bioenergetics', 'category_bioenergetics').
topic_s_main_category('conservation_of_energy', 'category_conservation_of_energy').
topic_s_main_category('dark_energy', 'category_dark_energy').
topic_s_main_category('energy_transformation', 'category_energy_conversion').
topic_s_main_category('enthalpy', 'category_enthalpy').
topic_s_main_category('josephson_effect', 'category_josephson_effect').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_regions_of_germany', 'category_natural_regions_of_germany').
topic_s_main_category('natural_science', 'category_natural_sciences').
topic_s_main_category('natural_regions_of_germany', 'category_natural_regions_of_germany').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
has_part_s_('new_7_wonders_of_nature', 'table_mountain').
has_part_s_('new_7_wonders_of_nature', 'ha_long_bay').
has_part_s_('new_7_wonders_of_nature', 'jeju_volcanic_island_and_lava_tubes').
has_part_s_('new_7_wonders_of_nature', 'puerto_princesa_river').
has_part_s_('new_7_wonders_of_nature', 'igua_u_falls').
has_part_s_('new_7_wonders_of_nature', 'amazon_rainforest').
has_part_s_('new_7_wonders_of_nature', 'komodo_island').
has_part_s_('figure_of_the_earth', 'earth_ellipsoid').
has_part_s_('history_of_earth', 'human_history').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
has_part_s_('new_7_wonders_of_nature', 'table_mountain').
has_part_s_('new_7_wonders_of_nature', 'ha_long_bay').
has_part_s_('new_7_wonders_of_nature', 'jeju_volcanic_island_and_lava_tubes').
has_part_s_('new_7_wonders_of_nature', 'puerto_princesa_river').
has_part_s_('new_7_wonders_of_nature', 'igua_u_falls').
has_part_s_('new_7_wonders_of_nature', 'amazon_rainforest').
has_part_s_('new_7_wonders_of_nature', 'komodo_island').
has_part_s_('figure_of_the_earth', 'earth_ellipsoid').
has_part_s_('history_of_earth', 'human_history').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
has_part_s_('new_7_wonders_of_nature', 'table_mountain').
has_part_s_('new_7_wonders_of_nature', 'ha_long_bay').
has_part_s_('new_7_wonders_of_nature', 'jeju_volcanic_island_and_lava_tubes').
has_part_s_('new_7_wonders_of_nature', 'puerto_princesa_river').
has_part_s_('new_7_wonders_of_nature', 'igua_u_falls').
has_part_s_('new_7_wonders_of_nature', 'amazon_rainforest').
has_part_s_('new_7_wonders_of_nature', 'komodo_island').
has_part_s_('figure_of_the_earth', 'earth_ellipsoid').
has_part_s_('history_of_earth', 'human_history').
has_part_s_('conservation_of_energy', 'energy').
has_part_s_('energy_transformation', 'form_of_energy').
has_part_s_('josephson_effect', 'josephson_energy').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
has_part_s_('natural_science', 'physics').
has_part_s_('natural_science', 'environmental_science').
has_part_s_('natural_science', 'life_sciences').
has_part_s_('natural_science', 'earth_science').
has_part_s_('natural_science', 'space_sciences').
has_part_s_('natural_science', 'biochemistry').
has_part_s_('natural_science', 'chemistry').
has_part_s_('natural_science', 'biology').
said_to_be_the_same_as('natural_science', 'natural_history').
said_to_be_the_same_as('figure_of_the_earth', 'geoid').
said_to_be_the_same_as('natural_science', 'natural_history').
said_to_be_the_same_as('figure_of_the_earth', 'geoid').
said_to_be_the_same_as('natural_science', 'natural_history').
said_to_be_the_same_as('figure_of_the_earth', 'geoid').
said_to_be_the_same_as('world', 'earth').
said_to_be_the_same_as('world', 'universe').
said_to_be_the_same_as('conservation_of_energy', 'conservation_of_mass').
said_to_be_the_same_as('natural_science', 'natural_history').
said_to_be_the_same_as('natural_science', 'natural_history').
said_to_be_the_same_as('natural_science', 'natural_history').
said_to_be_the_same_as('natural_science', 'natural_history').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('swamp_legend', 'after_26_years__munich_settles_case_over_a_klee_looted_by_the_nazis').
described_by_source('swamp_legend', '_26_years_is_too_long____settlement_finally_reached_in_battle_over_paul_klee_from_nazi__degenerate_art__show').
described_by_source('earth', 'bible_encyclopedia_of_archimandrite_nicephorus').
described_by_source('earth', 'explanatory_dictionary_of_the_living_great_russian_language').
described_by_source('earth', 'q2041543').
described_by_source('earth', 'gujin_tushu_jicheng').
described_by_source('earth', 'der_volks_brockhaus').
described_by_source('earth_science', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('figure_of_the_earth', 'encyclop_dia_britannica_11th_edition').
described_by_source('gaia_hypothesis', 'lean_logic').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('swamp_legend', 'after_26_years__munich_settles_case_over_a_klee_looted_by_the_nazis').
described_by_source('swamp_legend', '_26_years_is_too_long____settlement_finally_reached_in_battle_over_paul_klee_from_nazi__degenerate_art__show').
described_by_source('earth', 'bible_encyclopedia_of_archimandrite_nicephorus').
described_by_source('earth', 'explanatory_dictionary_of_the_living_great_russian_language').
described_by_source('earth', 'q2041543').
described_by_source('earth', 'gujin_tushu_jicheng').
described_by_source('earth', 'der_volks_brockhaus').
described_by_source('earth_science', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('figure_of_the_earth', 'encyclop_dia_britannica_11th_edition').
described_by_source('gaia_hypothesis', 'lean_logic').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('swamp_legend', 'after_26_years__munich_settles_case_over_a_klee_looted_by_the_nazis').
described_by_source('swamp_legend', '_26_years_is_too_long____settlement_finally_reached_in_battle_over_paul_klee_from_nazi__degenerate_art__show').
described_by_source('earth', 'bible_encyclopedia_of_archimandrite_nicephorus').
described_by_source('earth', 'explanatory_dictionary_of_the_living_great_russian_language').
described_by_source('earth', 'q2041543').
described_by_source('earth', 'gujin_tushu_jicheng').
described_by_source('earth', 'der_volks_brockhaus').
described_by_source('earth_science', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('figure_of_the_earth', 'encyclop_dia_britannica_11th_edition').
described_by_source('gaia_hypothesis', 'lean_logic').
described_by_source('earth_s_orbit', 'filit').
described_by_source('precession', 'granat_encyclopedic_dictionary').
described_by_source('world', 'gujin_tushu_jicheng').
described_by_source('world', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('world', 'encyclop_dia_britannica_11th_edition').
described_by_source('energy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('energy', 'iso_80000_5_2019_quantities_and_units___part_5__thermodynamics').
described_by_source('energy', 'iso_80000_5_2007_quantities_and_units___part_5__thermodynamics').
described_by_source('energy', 'lean_logic').
described_by_source('binding_energy', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('bioenergetics', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('conservation_of_energy', 'the_nuttall_encyclop_dia').
described_by_source('conservation_of_energy', 'granat_encyclopedic_dictionary').
described_by_source('enthalpy', 'iso_80000_5_2007_quantities_and_units___part_5__thermodynamics').
described_by_source('internal_energy', 'iso_80000_5_2019_quantities_and_units___part_5__thermodynamics').
described_by_source('internal_energy', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('internal_energy', 'iso_80000_5_2007_quantities_and_units___part_5__thermodynamics').
described_by_source('mechanical_energy', 'iso_80000_4_2019_quantities_and_units___part_4__mechanics').
described_by_source('mechanical_energy', 'iso_80000_4_2006_quantities_and_units_part_4__mechanics').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('swamp_legend', 'after_26_years__munich_settles_case_over_a_klee_looted_by_the_nazis').
described_by_source('swamp_legend', '_26_years_is_too_long____settlement_finally_reached_in_battle_over_paul_klee_from_nazi__degenerate_art__show').
described_by_source('natural_science', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('swamp_legend', 'after_26_years__munich_settles_case_over_a_klee_looted_by_the_nazis').
described_by_source('swamp_legend', '_26_years_is_too_long____settlement_finally_reached_in_battle_over_paul_klee_from_nazi__degenerate_art__show').
partially_coincident_with('natural_science', 'hard_science').
partially_coincident_with('natural_science', 'hard_science').
partially_coincident_with('natural_science', 'hard_science').
partially_coincident_with('world', 'this_world').
partially_coincident_with('natural_science', 'hard_science').
partially_coincident_with('natural_science', 'hard_science').
partially_coincident_with('natural_science', 'hard_science').
partially_coincident_with('natural_science', 'hard_science').
is_the_study_of('natural_science', 'nature').
is_the_study_of('earth_science', 'earth').
is_the_study_of('natural_science', 'nature').
is_the_study_of('earth_science', 'earth').
is_the_study_of('natural_science', 'nature').
is_the_study_of('earth_science', 'earth').
is_the_study_of('natural_science', 'nature').
is_the_study_of('natural_science', 'nature').
is_the_study_of('natural_science', 'nature').
is_the_study_of('natural_science', 'nature').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
parent_organization('anthropocene_working_group', 'international_commission_on_stratigraphy').
parent_organization('imperial_college_faculty_of_natural_sciences', 'imperial_college_london').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
located_in_the_administrative_territorial_entity('imperial_college_faculty_of_natural_sciences', 'london').
located_in_the_administrative_territorial_entity('uprrp_college_of_natural_sciences', 'puerto_rico').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
replaces('terrestrial_time', 'geocentric_coordinate_time').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
replaces('imperial_college_faculty_of_natural_sciences', 'royal_college_of_science').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_life_sciences__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_chemistry__imperial_college_london').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'centre_for_environmental_policy').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'blackett_laboratory').
has_subsidiary('imperial_college_faculty_of_natural_sciences', 'department_of_mathematics__imperial_college_london').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
field_of_work('imperial_college_faculty_of_natural_sciences', 'natural_science').
field_of_work('natural_sciences_collections_association', 'natural_science').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
tuition_fee('imperial_college_faculty_of_natural_sciences', '31000').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('natural_regions_of_germany', 'germany').
country('seven_wonders_of_canada', 'canada').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('natural_regions_of_germany', 'germany').
country('seven_wonders_of_canada', 'canada').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('natural_regions_of_germany', 'germany').
country('seven_wonders_of_canada', 'canada').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('natural_regions_of_germany', 'germany').
country('imperial_college_faculty_of_natural_sciences', 'united_kingdom').
country('uprrp_college_of_natural_sciences', 'united_states').
country('natural_regions_of_germany', 'germany').
interested_in('natural_sciences_collections_association', 'scientific_collection').
interested_in('natural_sciences_collections_association', 'scientific_collection').
interested_in('natural_sciences_collections_association', 'scientific_collection').
interested_in('natural_sciences_collections_association', 'scientific_collection').
interested_in('natural_sciences_collections_association', 'scientific_collection').
interested_in('natural_sciences_collections_association', 'scientific_collection').
interested_in('natural_sciences_collections_association', 'scientific_collection').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
headquarters_location('natural_sciences_collections_association', 'united_kingdom').
social_media_followers('natural_sciences_collections_association', '6336').
social_media_followers('natural_sciences_collections_association', '6336').
social_media_followers('natural_sciences_collections_association', '6336').
social_media_followers('natural_sciences_collections_association', '6336').
social_media_followers('natural_sciences_collections_association', '6336').
social_media_followers('natural_sciences_collections_association', '6336').
social_media_followers('natural_sciences_collections_association', '6336').
industry('natural_sciences_collections_association', 'higher_education').
industry('natural_sciences_collections_association', 'higher_education').
industry('natural_sciences_collections_association', 'higher_education').
industry('natural_sciences_collections_association', 'higher_education').
industry('natural_sciences_collections_association', 'higher_education').
industry('natural_sciences_collections_association', 'higher_education').
industry('natural_sciences_collections_association', 'higher_education').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
indexed_in_bibliographic_review('nature__journal_', 'scopus').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
indexed_in_bibliographic_review('nature__journal_', 'scopus').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
indexed_in_bibliographic_review('nature__journal_', 'science_citation_index_expanded').
qualis_rank('nature__journal_', 'a1').
qualis_rank('nature__journal_', 'a1').
qualis_rank('nature__journal_', 'a1').
qualis_rank('nature__journal_', 'a1').
qualis_rank('nature__journal_', 'a1').
qualis_rank('nature__journal_', 'a1').
qualis_rank('nature__journal_', 'a1').
different_from('nature__journal_', 'nature').
different_from('asteroid_impact_avoidance', 'planetary_protection').
different_from('gravity_of_earth', 'standard_acceleration_of_free_fall').
different_from('gravity_of_earth', 'acceleration_of_free_fall').
different_from('gravity_of_earth', 'gravity').
different_from('gravity_of_earth', 'gravitational_acceleration').
different_from('history_of_earth', 'human_history').
different_from('nature__journal_', 'nature').
different_from('asteroid_impact_avoidance', 'planetary_protection').
different_from('gravity_of_earth', 'standard_acceleration_of_free_fall').
different_from('gravity_of_earth', 'acceleration_of_free_fall').
different_from('gravity_of_earth', 'gravity').
different_from('gravity_of_earth', 'gravitational_acceleration').
different_from('history_of_earth', 'human_history').
different_from('nature__journal_', 'nature').
different_from('asteroid_impact_avoidance', 'planetary_protection').
different_from('gravity_of_earth', 'standard_acceleration_of_free_fall').
different_from('gravity_of_earth', 'acceleration_of_free_fall').
different_from('gravity_of_earth', 'gravity').
different_from('gravity_of_earth', 'gravitational_acceleration').
different_from('history_of_earth', 'human_history').
different_from('earth_mass', 'mass_of_the_earth').
different_from('earth_s_orbit', 'geocentric_orbit').
different_from('rare_earth_hypothesis', 'rare_earth_element').
different_from('earth_in_science_fiction', 'fictional_earth_analogue').
different_from('spaceship_earth', 'earthship').
different_from('spaceship_earth', 'spaceship_earth').
different_from('substorm', 'geomagnetic_storm').
different_from('world', 'dunia').
different_from('world', 'welt').
different_from('world', 'svet').
different_from('world', '_wiat').
different_from('world', 'the_world').
different_from('conservation_of_energy', 'energy_conservation').
different_from('energy_current', 'energy_flux').
different_from('gravitational_potential', 'gravitational_field').
different_from('gravitational_potential', 'geopotential').
different_from('gravitational_potential', 'gravitational_energy').
different_from('invariant_mass', 'rest_mass').
different_from('invariant_mass', 'rest_energy').
different_from('invariant_mass', 'mass').
different_from('josephson_effect', 'long_josephson_junction').
different_from('josephson_effect', 'josephson_vortex').
different_from('josephson_effect', 'josephson_phase').
different_from('nature__journal_', 'nature').
different_from('nature__journal_', 'nature').
different_from('nature__journal_', 'nature').
different_from('nature__journal_', 'nature').
online_access_status('nature__journal_', 'paywall').
online_access_status('nature__journal_', 'paywall').
online_access_status('nature__journal_', 'paywall').
online_access_status('nature__journal_', 'paywall').
online_access_status('nature__journal_', 'paywall').
online_access_status('nature__journal_', 'paywall').
online_access_status('nature__journal_', 'paywall').
practiced_by('rangeland_management', 'range_manager').
practiced_by('earth_science', 'earth_scientist').
practiced_by('rangeland_management', 'range_manager').
practiced_by('earth_science', 'earth_scientist').
practiced_by('rangeland_management', 'range_manager').
practiced_by('earth_science', 'earth_scientist').
practiced_by('rangeland_management', 'range_manager').
practiced_by('rangeland_management', 'range_manager').
practiced_by('rangeland_management', 'range_manager').
practiced_by('rangeland_management', 'range_manager').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
composer('become_desert', 'john_luther_adams').
composer('become_ocean', 'john_luther_adams').
composer('des_canyons_aux__toiles___', 'olivier_messiaen').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('forest_404', 'fiction_podcast').
genre('forest_404', 'drama_podcast').
genre('forest_404', 'drama_fiction_podcast').
genre('seven_natural_wonders', 'television_documentary').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('forest_404', 'fiction_podcast').
genre('forest_404', 'drama_podcast').
genre('forest_404', 'drama_fiction_podcast').
genre('seven_natural_wonders', 'television_documentary').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('forest_404', 'fiction_podcast').
genre('forest_404', 'drama_podcast').
genre('forest_404', 'drama_fiction_podcast').
genre('seven_natural_wonders', 'television_documentary').
genre('earth_in_science_fiction', 'science_fiction').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('forest_404', 'fiction_podcast').
genre('forest_404', 'drama_podcast').
genre('forest_404', 'drama_fiction_podcast').
genre('become_ocean', 'contemporary_classical_music').
genre('fe__video_game_', 'action_adventure_game').
genre('forest_404', 'fiction_podcast').
genre('forest_404', 'drama_podcast').
genre('forest_404', 'drama_fiction_podcast').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
instrumentation('des_canyons_aux__toiles___', 'orchestra').
instrumentation('des_canyons_aux__toiles___', 'horn').
instrumentation('des_canyons_aux__toiles___', 'piano').
instrumentation('des_canyons_aux__toiles___', 'glockenspiel').
developer('fe__video_game_', 'zoink_games').
developer('fe__video_game_', 'zoink_games').
developer('fe__video_game_', 'zoink_games').
developer('fe__video_game_', 'zoink_games').
developer('fe__video_game_', 'zoink_games').
developer('fe__video_game_', 'zoink_games').
developer('fe__video_game_', 'zoink_games').
publisher('fe__video_game_', 'electronic_arts').
publisher('fe__video_game_', 'electronic_arts').
publisher('fe__video_game_', 'electronic_arts').
publisher('fe__video_game_', 'electronic_arts').
publisher('fe__video_game_', 'electronic_arts').
publisher('fe__video_game_', 'electronic_arts').
publisher('fe__video_game_', 'electronic_arts').
esrb_rating('fe__video_game_', 'everyone').
esrb_rating('fe__video_game_', 'everyone').
esrb_rating('fe__video_game_', 'everyone').
esrb_rating('fe__video_game_', 'everyone').
esrb_rating('fe__video_game_', 'everyone').
esrb_rating('fe__video_game_', 'everyone').
esrb_rating('fe__video_game_', 'everyone').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('forest_404', 'british_english').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('forest_404', 'british_english').
language_of_work_or_name('the_cloud__poem_', 'english').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('forest_404', 'british_english').
language_of_work_or_name('the_cloud__poem_', 'english').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('the_cloud__poem_', 'english').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('the_cloud__poem_', 'english').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('forest_404', 'british_english').
language_of_work_or_name('the_cloud__poem_', 'english').
language_of_work_or_name('fe__video_game_', 'japanese').
language_of_work_or_name('fe__video_game_', 'spanish').
language_of_work_or_name('fe__video_game_', 'italian').
language_of_work_or_name('fe__video_game_', 'french').
language_of_work_or_name('fe__video_game_', 'english').
language_of_work_or_name('fe__video_game_', 'german').
language_of_work_or_name('forest_404', 'british_english').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('forest_404', 'bbc_radio').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('forest_404', 'bbc_radio').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('forest_404', 'bbc_radio').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('forest_404', 'bbc_radio').
distributed_by('fe__video_game_', 'steam').
distributed_by('fe__video_game_', 'playstation_store').
distributed_by('fe__video_game_', 'nintendo_eshop').
distributed_by('fe__video_game_', 'microsoft_store').
distributed_by('fe__video_game_', 'humble_store').
distributed_by('forest_404', 'bbc_radio').
game_mode('fe__video_game_', 'single_player_video_game').
game_mode('fe__video_game_', 'single_player_video_game').
game_mode('fe__video_game_', 'single_player_video_game').
game_mode('fe__video_game_', 'single_player_video_game').
game_mode('fe__video_game_', 'single_player_video_game').
game_mode('fe__video_game_', 'single_player_video_game').
game_mode('fe__video_game_', 'single_player_video_game').
digital_rights_management_system('fe__video_game_', 'denuvo').
digital_rights_management_system('fe__video_game_', 'denuvo').
digital_rights_management_system('fe__video_game_', 'denuvo').
digital_rights_management_system('fe__video_game_', 'denuvo').
digital_rights_management_system('fe__video_game_', 'denuvo').
digital_rights_management_system('fe__video_game_', 'denuvo').
digital_rights_management_system('fe__video_game_', 'denuvo').
platform('fe__video_game_', 'microsoft_windows').
platform('fe__video_game_', 'microsoft_windows').
platform('fe__video_game_', 'microsoft_windows').
platform('fe__video_game_', 'microsoft_windows').
platform('fe__video_game_', 'microsoft_windows').
platform('fe__video_game_', 'microsoft_windows').
platform('fe__video_game_', 'microsoft_windows').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('forest_404', 'audio_podcast').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('forest_404', 'audio_podcast').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('forest_404', 'audio_podcast').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('forest_404', 'audio_podcast').
distribution_format('fe__video_game_', 'digital_download').
distribution_format('forest_404', 'audio_podcast').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('forest_404', 'united_kingdom').
country_of_origin('seven_natural_wonders', 'united_kingdom').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('forest_404', 'united_kingdom').
country_of_origin('seven_natural_wonders', 'united_kingdom').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('forest_404', 'united_kingdom').
country_of_origin('seven_natural_wonders', 'united_kingdom').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('forest_404', 'united_kingdom').
country_of_origin('fe__video_game_', 'sweden').
country_of_origin('forest_404', 'united_kingdom').
software_engine('fe__video_game_', 'unity').
software_engine('fe__video_game_', 'unity').
software_engine('fe__video_game_', 'unity').
software_engine('fe__video_game_', 'unity').
software_engine('fe__video_game_', 'unity').
software_engine('fe__video_game_', 'unity').
software_engine('fe__video_game_', 'unity').
presenter('forest_404', 'pearl_mackie').
presenter('forest_404', 'tanya_moodie').
presenter('forest_404', 'pippa_haywood').
presenter('forest_404', 'pearl_mackie').
presenter('forest_404', 'tanya_moodie').
presenter('forest_404', 'pippa_haywood').
presenter('forest_404', 'pearl_mackie').
presenter('forest_404', 'tanya_moodie').
presenter('forest_404', 'pippa_haywood').
presenter('forest_404', 'pearl_mackie').
presenter('forest_404', 'tanya_moodie').
presenter('forest_404', 'pippa_haywood').
presenter('forest_404', 'pearl_mackie').
presenter('forest_404', 'tanya_moodie').
presenter('forest_404', 'pippa_haywood').
production_company('forest_404', 'bbc_radio_4').
production_company('forest_404', 'bbc_radio_4').
production_company('forest_404', 'bbc_radio_4').
production_company('forest_404', 'bbc_radio_4').
production_company('forest_404', 'bbc_radio_4').
broadcast_by('forest_404', 'bbc_radio_4').
broadcast_by('forest_404', 'bbc_radio_4').
broadcast_by('forest_404', 'bbc_radio_4').
broadcast_by('forest_404', 'bbc_radio_4').
broadcast_by('forest_404', 'bbc_radio_4').
copyright_status('forest_404', 'copyrighted').
copyright_status('swamp_legend', 'public_domain').
copyright_status('forest_404', 'copyrighted').
copyright_status('swamp_legend', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('forest_404', 'copyrighted').
copyright_status('swamp_legend', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('forest_404', 'copyrighted').
copyright_status('swamp_legend', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('the_cloud__poem_', 'public_domain').
copyright_status('forest_404', 'copyrighted').
copyright_status('swamp_legend', 'public_domain').
number_of_episodes('forest_404', '28').
number_of_episodes('seven_natural_wonders', '8').
number_of_episodes('forest_404', '28').
number_of_episodes('seven_natural_wonders', '8').
number_of_episodes('forest_404', '28').
number_of_episodes('seven_natural_wonders', '8').
number_of_episodes('forest_404', '28').
number_of_episodes('forest_404', '28').
publication_interval('forest_404', '1').
publication_interval('forest_404', '1').
publication_interval('forest_404', '1').
publication_interval('forest_404', '1').
publication_interval('forest_404', '1').
day_of_regular_release('forest_404', 'thursday').
day_of_regular_release('forest_404', 'thursday').
day_of_regular_release('forest_404', 'thursday').
day_of_regular_release('forest_404', 'thursday').
day_of_regular_release('forest_404', 'thursday').
collection('swamp_legend', 'lenbachhaus').
collection('swamp_legend', '_degenerate_art__collection').
collection('swamp_legend', 'lenbachhaus').
collection('swamp_legend', '_degenerate_art__collection').
collection('swamp_legend', 'lenbachhaus').
collection('swamp_legend', '_degenerate_art__collection').
collection('swamp_legend', 'lenbachhaus').
collection('swamp_legend', '_degenerate_art__collection').
collection('swamp_legend', 'lenbachhaus').
collection('swamp_legend', '_degenerate_art__collection').
owned_by('swamp_legend', 'sophie_lissitzky_k_ppers').
owned_by('swamp_legend', 'hildebrand_gurlitt').
owned_by('swamp_legend', 'munich').
owned_by('swamp_legend', 'paul_erich_k_ppers').
owned_by('swamp_legend', 'ernst_beyeler').
owned_by('swamp_legend', 'sophie_lissitzky_k_ppers').
owned_by('swamp_legend', 'hildebrand_gurlitt').
owned_by('swamp_legend', 'munich').
owned_by('swamp_legend', 'paul_erich_k_ppers').
owned_by('swamp_legend', 'ernst_beyeler').
owned_by('swamp_legend', 'sophie_lissitzky_k_ppers').
owned_by('swamp_legend', 'hildebrand_gurlitt').
owned_by('swamp_legend', 'munich').
owned_by('swamp_legend', 'paul_erich_k_ppers').
owned_by('swamp_legend', 'ernst_beyeler').
owned_by('swamp_legend', 'sophie_lissitzky_k_ppers').
owned_by('swamp_legend', 'hildebrand_gurlitt').
owned_by('swamp_legend', 'munich').
owned_by('swamp_legend', 'paul_erich_k_ppers').
owned_by('swamp_legend', 'ernst_beyeler').
owned_by('swamp_legend', 'sophie_lissitzky_k_ppers').
owned_by('swamp_legend', 'hildebrand_gurlitt').
owned_by('swamp_legend', 'munich').
owned_by('swamp_legend', 'paul_erich_k_ppers').
owned_by('swamp_legend', 'ernst_beyeler').
location('swamp_legend', 'landesmuseum_hannover').
location('swamp_legend', '_degenerate_art__collection').
location('demographics_of_the_world', 'earth').
location('gravity_of_earth', 'earth').
location('swamp_legend', 'landesmuseum_hannover').
location('swamp_legend', '_degenerate_art__collection').
location('demographics_of_the_world', 'earth').
location('gravity_of_earth', 'earth').
location('swamp_legend', 'landesmuseum_hannover').
location('swamp_legend', '_degenerate_art__collection').
location('demographics_of_the_world', 'earth').
location('gravity_of_earth', 'earth').
location('swamp_legend', 'landesmuseum_hannover').
location('swamp_legend', '_degenerate_art__collection').
location('swamp_legend', 'landesmuseum_hannover').
location('swamp_legend', '_degenerate_art__collection').
creator('swamp_legend', 'paul_klee').
creator('iucn_protected_area_categories', 'international_union_for_conservation_of_nature').
creator('swamp_legend', 'paul_klee').
creator('iucn_protected_area_categories', 'international_union_for_conservation_of_nature').
creator('swamp_legend', 'paul_klee').
creator('iucn_protected_area_categories', 'international_union_for_conservation_of_nature').
creator('swamp_legend', 'paul_klee').
creator('swamp_legend', 'paul_klee').
made_from_material('swamp_legend', 'oil_paint').
made_from_material('swamp_legend', 'oil_paint').
made_from_material('swamp_legend', 'oil_paint').
made_from_material('swamp_legend', 'oil_paint').
made_from_material('swamp_legend', 'oil_paint').
location_of_creation('swamp_legend', 'castle_suresnes').
location_of_creation('swamp_legend', 'castle_suresnes').
location_of_creation('swamp_legend', 'castle_suresnes').
location_of_creation('swamp_legend', 'castle_suresnes').
location_of_creation('swamp_legend', 'castle_suresnes').
significant_event('swamp_legend', 'legal_settlement').
significant_event('swamp_legend', 'claim_for_restitution_of_an_artwork').
significant_event('swamp_legend', 'seizure').
significant_event('swamp_legend', 'legal_settlement').
significant_event('swamp_legend', 'claim_for_restitution_of_an_artwork').
significant_event('swamp_legend', 'seizure').
significant_event('swamp_legend', 'legal_settlement').
significant_event('swamp_legend', 'claim_for_restitution_of_an_artwork').
significant_event('swamp_legend', 'seizure').
significant_event('swamp_legend', 'legal_settlement').
significant_event('swamp_legend', 'claim_for_restitution_of_an_artwork').
significant_event('swamp_legend', 'seizure').
significant_event('swamp_legend', 'legal_settlement').
significant_event('swamp_legend', 'claim_for_restitution_of_an_artwork').
significant_event('swamp_legend', 'seizure').
exhibition_history('swamp_legend', 'degenerate_art_exhibition').
exhibition_history('swamp_legend', 'degenerate_art_exhibition').
exhibition_history('swamp_legend', 'degenerate_art_exhibition').
exhibition_history('swamp_legend', 'degenerate_art_exhibition').
exhibition_history('swamp_legend', 'degenerate_art_exhibition').
height('swamp_legend', '47').
height('swamp_legend', '47').
height('swamp_legend', '47').
height('swamp_legend', '47').
height('swamp_legend', '47').
width('swamp_legend', '40_8').
width('swamp_legend', '40_8').
width('swamp_legend', '40_8').
width('swamp_legend', '40_8').
width('swamp_legend', '40_8').
is_a_list_of('index_of_conservation_articles', 'wikimedia_article_page').
is_a_list_of('index_of_conservation_articles', 'wikimedia_article_page').
is_a_list_of('index_of_conservation_articles', 'wikimedia_article_page').
is_a_list_of('index_of_conservation_articles', 'wikimedia_article_page').
is_a_list_of('index_of_conservation_articles', 'wikimedia_article_page').
part_of('natural_regions_of_germany', 'natural_region_of_germany').
part_of('history_of_earth', 'planetary_science').
part_of('location_of_earth', 'universe').
part_of('natural_regions_of_germany', 'natural_region_of_germany').
part_of('history_of_earth', 'planetary_science').
part_of('location_of_earth', 'universe').
part_of('natural_regions_of_germany', 'natural_region_of_germany').
part_of('history_of_earth', 'planetary_science').
part_of('location_of_earth', 'universe').
part_of('precession', 'classical_mechanics').
part_of('substorm', 'space_weather').
part_of('bioenergetics', 'biochemistry').
part_of('dark_energy', 'hidden_sector').
part_of('dark_energy', 'observable_universe').
part_of('energy_transformation', 'physics').
part_of('natural_regions_of_germany', 'natural_region_of_germany').
part_of('natural_regions_of_germany', 'natural_region_of_germany').
used_by('iucn_protected_area_categories', 'openstreetmap').
used_by('iucn_protected_area_categories', 'openstreetmap').
used_by('iucn_protected_area_categories', 'openstreetmap').
operator('iucn_protected_area_categories', 'international_union_for_conservation_of_nature').
operator('iucn_protected_area_categories', 'international_union_for_conservation_of_nature').
operator('iucn_protected_area_categories', 'international_union_for_conservation_of_nature').
facet_of('iucn_protected_area_categories', 'protected_area').
facet_of('day_length_fluctuations', 'horology').
facet_of('day_length_fluctuations', 'day').
facet_of('earth_s_internal_heat_budget', 'geothermal_energy').
facet_of('earth_s_internal_heat_budget', 'geophysics').
facet_of('future_of_earth', 'earth').
facet_of('future_of_earth', 'future').
facet_of('geological_history_of_earth', 'earth').
facet_of('history_of_earth', 'history').
facet_of('history_of_earth', 'earth').
facet_of('iucn_protected_area_categories', 'protected_area').
facet_of('day_length_fluctuations', 'horology').
facet_of('day_length_fluctuations', 'day').
facet_of('earth_s_internal_heat_budget', 'geothermal_energy').
facet_of('earth_s_internal_heat_budget', 'geophysics').
facet_of('future_of_earth', 'earth').
facet_of('future_of_earth', 'future').
facet_of('geological_history_of_earth', 'earth').
facet_of('history_of_earth', 'history').
facet_of('history_of_earth', 'earth').
facet_of('iucn_protected_area_categories', 'protected_area').
facet_of('day_length_fluctuations', 'horology').
facet_of('day_length_fluctuations', 'day').
facet_of('earth_s_internal_heat_budget', 'geothermal_energy').
facet_of('earth_s_internal_heat_budget', 'geophysics').
facet_of('future_of_earth', 'earth').
facet_of('future_of_earth', 'future').
facet_of('geological_history_of_earth', 'earth').
facet_of('history_of_earth', 'history').
facet_of('history_of_earth', 'earth').
facet_of('earth_s_orbit', 'earth').
facet_of('origin_of_water_on_earth', 'water_on_earth').
facet_of('purple_earth_hypothesis', 'astrobiology').
facet_of('solar_equator', 'sun').
facet_of('spaceship_earth', 'earth').
facet_of('spherical_earth', 'figure_of_the_earth').
facet_of('water_distribution_on_earth', 'water_on_earth').
facet_of('gravitational_potential', 'gravity').
facet_of('gravitational_potential', 'gravitational_field').
facet_of('josephson_effect', 'supercurrent').
facet_of('mass_energy_equivalence', 'special_relativity').
original_broadcaster('seven_natural_wonders', 'bbc').
original_broadcaster('seven_natural_wonders', 'bbc').
original_broadcaster('seven_natural_wonders', 'bbc').
original_language_of_film_or_tv_show('seven_natural_wonders', 'english').
original_language_of_film_or_tv_show('seven_natural_wonders', 'english').
original_language_of_film_or_tv_show('seven_natural_wonders', 'english').
shape('earth', 'geoid').
shape('earth', 'ball').
shape('earth', 'geoid').
shape('earth', 'ball').
shape('earth', 'geoid').
shape('earth', 'ball').
shape('earth_s_orbit', 'ellipse').
population('earth', '5263593000').
population('earth', '7000000000').
population('earth', '8000000000').
population('earth', '7475406776').
population('earth', '5000000000').
population('earth', '4000000000').
population('earth', '4830979000').
population('earth', '7969111502').
population('earth', '3021475000').
population('earth', '400000000').
population('earth', '2755823000').
population('earth', '7510021269').
population('earth', '5674380000').
population('earth', '7830458560').
population('earth', '7000000').
population('earth', '7202951000').
population('earth', '6343628000').
population('earth', '6800000000').
population('earth', '285000000').
population('earth', '5263593000').
population('earth', '7000000000').
population('earth', '8000000000').
population('earth', '7475406776').
population('earth', '5000000000').
population('earth', '4000000000').
population('earth', '4830979000').
population('earth', '7969111502').
population('earth', '3021475000').
population('earth', '400000000').
population('earth', '2755823000').
population('earth', '7510021269').
population('earth', '5674380000').
population('earth', '7830458560').
population('earth', '7000000').
population('earth', '7202951000').
population('earth', '6343628000').
population('earth', '6800000000').
population('earth', '285000000').
population('earth', '5263593000').
population('earth', '7000000000').
population('earth', '8000000000').
population('earth', '7475406776').
population('earth', '5000000000').
population('earth', '4000000000').
population('earth', '4830979000').
population('earth', '7969111502').
population('earth', '3021475000').
population('earth', '400000000').
population('earth', '2755823000').
population('earth', '7510021269').
population('earth', '5674380000').
population('earth', '7830458560').
population('earth', '7000000').
population('earth', '7202951000').
population('earth', '6343628000').
population('earth', '6800000000').
population('earth', '285000000').
flattening('earth', '0_0033528').
flattening('earth', '0_0033528').
flattening('earth', '0_0033528').
orbital_eccentricity('earth', '0_01671123').
orbital_eccentricity('earth', '0_01671123').
orbital_eccentricity('earth', '0_01671123').
topic_s_main_template('earth_science', 'template_earth_science').
topic_s_main_template('asteroid_impact_avoidance', 'template_planetary_defense').
topic_s_main_template('geological_history_of_earth', 'template_geological_history_of_earth').
topic_s_main_template('location_of_earth', 'template_earth_s_location').
topic_s_main_template('earth_science', 'template_earth_science').
topic_s_main_template('asteroid_impact_avoidance', 'template_planetary_defense').
topic_s_main_template('geological_history_of_earth', 'template_geological_history_of_earth').
topic_s_main_template('location_of_earth', 'template_earth_s_location').
topic_s_main_template('earth_science', 'template_earth_science').
topic_s_main_template('asteroid_impact_avoidance', 'template_planetary_defense').
topic_s_main_template('geological_history_of_earth', 'template_geological_history_of_earth').
topic_s_main_template('location_of_earth', 'template_earth_s_location').
topic_s_main_template('energy', 'template_energy_footer').
history_of_topic('earth_science', 'history_of_earth_science').
history_of_topic('earth_science', 'history_of_earth_science').
history_of_topic('earth_science', 'history_of_earth_science').
history_of_topic('world', 'human_history').
main_subject('earth_science', 'earth').
main_subject('earth_science', 'earth_analog').
main_subject('earth_science', 'earth').
main_subject('earth_science', 'earth_analog').
main_subject('earth_science', 'earth').
main_subject('earth_science', 'earth_analog').
studied_in('earth_science', 'earth_science_studies').
studied_in('earth_science', 'earth_science_studies').
studied_in('earth_science', 'earth_science_studies').
studied_in('natural_environment', 'ecology').
studied_in('natural_environment', 'geography').
studied_in('natural_environment', 'ecological_economics').
studied_in('dark_energy', 'astrophysics').
studied_in('dark_energy', 'cosmology').
studied_in('internal_energy', 'thermodynamics').
uses('asteroid_impact_avoidance', 'asteroid_impact_prediction').
uses('asteroid_impact_avoidance', 'asteroid_impact_prediction').
uses('asteroid_impact_avoidance', 'asteroid_impact_prediction').
in_opposition_to('asteroid_impact_avoidance', 'impact_event').
in_opposition_to('asteroid_impact_avoidance', 'impact_event').
in_opposition_to('asteroid_impact_avoidance', 'impact_event').
has_goal('asteroid_impact_avoidance', 'prevention').
has_goal('asteroid_impact_avoidance', 'prevention').
has_goal('asteroid_impact_avoidance', 'prevention').
the_length_of('earth_s_circumference', '40075_017').
the_length_of('earth_s_circumference', '40075_017').
the_length_of('earth_s_circumference', '40075_017').
measured_physical_quantity('earth_s_circumference', 'length').
measured_physical_quantity('earth_s_circumference', 'length').
measured_physical_quantity('earth_s_circumference', 'length').
measured_physical_quantity('earth_mass', 'mass').
measured_physical_quantity('kilocalorie_per_mole', 'molar_energy').
numeric_value('earth_s_internal_heat_budget', '47').
numeric_value('earth_s_internal_heat_budget', '47').
numeric_value('earth_s_internal_heat_budget', '47').
numeric_value('earth_radius', '6371').
manifestation_of('figure_of_the_earth', 'oblate_spheroid').
manifestation_of('figure_of_the_earth', 'oblate_spheroid').
manifestation_of('figure_of_the_earth', 'oblate_spheroid').
manifestation_of('mass_energy_equivalence', 'theory_of_relativity').
calculated_from('gravity_of_earth', 'position_vector').
calculated_from('gravity_of_earth', 'earth_radius').
calculated_from('gravity_of_earth', 'gravitational_constant').
calculated_from('gravity_of_earth', 'earth_mass').
calculated_from('gravity_of_earth', 'position_vector').
calculated_from('gravity_of_earth', 'earth_radius').
calculated_from('gravity_of_earth', 'gravitational_constant').
calculated_from('gravity_of_earth', 'earth_mass').
calculated_from('gravity_of_earth', 'position_vector').
calculated_from('gravity_of_earth', 'earth_radius').
calculated_from('gravity_of_earth', 'gravitational_constant').
calculated_from('gravity_of_earth', 'earth_mass').
time_period('history_of_earth', 'matter_epoch').
time_period('history_of_earth', 'matter_epoch').
time_period('history_of_earth', 'matter_epoch').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud__shelley_').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'mrak').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud__shelley_').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'mrak').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud__shelley_').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'mrak').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud__shelley_').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'mrak').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud__shelley_').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'the_cloud').
has_edition_or_translation('the_cloud__poem_', 'mrak').
form_of_creative_work('the_cloud__poem_', 'poem').
form_of_creative_work('the_cloud__poem_', 'poem').
form_of_creative_work('the_cloud__poem_', 'poem').
form_of_creative_work('the_cloud__poem_', 'poem').
form_of_creative_work('the_cloud__poem_', 'poem').
author('the_cloud__poem_', 'percy_bysshe_shelley').
author('the_cloud__poem_', 'percy_bysshe_shelley').
author('the_cloud__poem_', 'percy_bysshe_shelley').
author('the_cloud__poem_', 'percy_bysshe_shelley').
author('the_cloud__poem_', 'percy_bysshe_shelley').
based_on('earth_mass', 'mass_of_the_earth').
conversion_to_si_unit('earth_mass', '5972190000000000000000000').
conversion_to_si_unit('kilocalorie_per_mole', '4184').
followed_by('earth_s_orbit', 'orbit_of_mars').
follows('earth_s_orbit', 'orbit_of_venus').
has_effect('earth_s_rotation', 'earth_s_centrifugal_acceleration').
has_effect('earth_s_rotation', 'earth_flattening').
fictional_or_mythical_analog_of('earth_in_science_fiction', 'earth').
opposite_of('spherical_earth', 'flat_earth').
geography_of_topic('world', 'world_geography').
economy_of_topic('world', 'world_economy').
demographics_of_topic('world', 'demographics_of_the_world').
recommended_unit_of_measurement('energy', 'kilogram_square_metre_per_square_second').
recommended_unit_of_measurement('energy', 'electronvolt').
recommended_unit_of_measurement('enthalpy', 'kilogram_square_metre_per_square_second').
recommended_unit_of_measurement('enthalpy', 'joule').
recommended_unit_of_measurement('internal_energy', 'kilogram_square_metre_per_square_second').
recommended_unit_of_measurement('internal_energy', 'joule').
recommended_unit_of_measurement('mechanical_energy', 'joule').
recommended_unit_of_measurement('mechanical_energy', 'kilogram_square_metre_per_square_second').
has_characteristic('energy', 'conservation_of_energy').
has_characteristic('energy_transformation', 'conservation_of_energy').
has_characteristic('invariant_mass', 'symmetry').
measurement_scale('energy_transformation', 'energy_efficiency').
has_cause('energy_transformation', 'energy_transformer').
is_invariant_under('enthalpy', 'isenthalpic_process').
is_invariant_under('invariant_mass', 'lorentz_transformation').
named_after('josephson_effect', 'brian_david_josephson').
has_use('mass_energy_equivalence', 'nuclear_power').
has_use('mass_energy_equivalence', 'nuclear_weapon').
discoverer_or_inventor('mass_energy_equivalence', 'albert_einstein').
