facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('bibliography_of_abraham_lincoln', 'abraham_lincoln').
facet_of('bibliography_of_works_on_madonna', 'madonna').
facet_of('hayao_miyazaki_bibliography', 'hayao_miyazaki').
facet_of('bibliography_of_richard_nixon', 'richard_nixon').
facet_of('bibliography_of_harold_pinter', 'harold_pinter').
facet_of('bibliography_of_pope_pius_xii', 'pius_xii').
facet_of('bibliography_of_george_washington', 'george_washington').
facet_of('bibliography_of_orson_welles', 'orson_welles').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('bibliography_of_abraham_lincoln', 'abraham_lincoln').
facet_of('bibliography_of_works_on_madonna', 'madonna').
facet_of('hayao_miyazaki_bibliography', 'hayao_miyazaki').
facet_of('bibliography_of_richard_nixon', 'richard_nixon').
facet_of('bibliography_of_harold_pinter', 'harold_pinter').
facet_of('bibliography_of_pope_pius_xii', 'pius_xii').
facet_of('bibliography_of_george_washington', 'george_washington').
facet_of('bibliography_of_orson_welles', 'orson_welles').
facet_of('biographical_film', 'based_on').
facet_of('man_bites_dog', 'journalism').
facet_of('shooting_the_messenger', 'communication').
facet_of('shooting_the_messenger', 'news').
facet_of('agency__philosophy_', 'decision_making').
facet_of('agency__philosophy_', 'humanism').
facet_of('beginning_of_human_personhood', 'personhood').
facet_of('great_ape_personhood', 'personhood').
facet_of('great_ape_personhood', 'primatology').
facet_of('great_ape_personhood', 'animal_rights').
facet_of('individual', 'biology').
facet_of('individual', 'law').
facet_of('individual', 'philosophy').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('yaroslavich', 'patronymic_family_name').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('yaroslavich', 'patronymic_family_name').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography_of_winston_churchill', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'written_work').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_stephen_harper', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_stephen_king', 'wikimedia_list_article').
instance_of('bibliography_of_stanis_aw_lem', 'bibliography').
instance_of('bibliography_of_lili_uokalani', 'bibliography').
instance_of('bibliography_of_abraham_lincoln', 'bibliography').
instance_of('bibliography_of_james_madison', 'bibliography').
instance_of('bibliography_of_works_on_madonna', 'bibliography').
instance_of('bibliography_of_william_mckinley', 'bibliography').
instance_of('bibliography_of_works_on_adolfas_mekas', 'bibliography').
instance_of('hayao_miyazaki_bibliography', 'bibliography').
instance_of('bibliography_of_james_monroe', 'public_election').
instance_of('bibliography_of_abul_hasan_ali_hasani_nadwi', 'book').
instance_of('bibliography_of_napoleon', 'bibliography').
instance_of('bibliography_of_richard_nixon', 'bibliography').
instance_of('bibliography_of_shibli_nomani', 'book').
instance_of('bibliography_of_barack_obama', 'wikimedia_list_article').
instance_of('bibliography_of_louis_joseph_papineau', 'bibliography').
instance_of('bibliography_of_harold_pinter', 'bibliography').
instance_of('bibliography_of_pope_pius_xii', 'bibliography').
instance_of('bibliography_of_ramakrishna', 'bibliography').
instance_of('bibliography_of_ayn_rand_and_objectivism', 'bibliography').
instance_of('bibliography_of_ronald_reagan', 'bibliography').
instance_of('bibliography_of_jacques_rivette', 'bibliography').
instance_of('bibliography_of_jane_roberts', 'bibliography').
instance_of('bibliography_of_eleanor_roosevelt', 'bibliography').
instance_of('bibliography_of_eleanor_roosevelt', 'wikimedia_list_article').
instance_of('bibliography_of_franklin_d__roosevelt', 'bibliography').
instance_of('bibliography_of_theodore_roosevelt', 'bibliography').
instance_of('bibliography_of_works_on_shakira', 'bibliography').
instance_of('the_works_of_m__p__shiel', 'literary_work').
instance_of('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'literary_work').
instance_of('bibliography_of_william_howard_taft', 'bibliography').
instance_of('bibliography_of_margaret_thatcher', 'bibliography').
instance_of('bibliography_of_justin_trudeau', 'bibliography').
instance_of('bibliography_of_harry_s__truman', 'bibliography').
instance_of('bibliography_of_donald_trump', 'personal_bibliography').
instance_of('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'bibliography').
instance_of('bibliography_of_martin_van_buren', 'bibliography').
instance_of('bibliography_of_swami_vivekananda', 'bibliography').
instance_of('bibliography_of_george_washington', 'bibliography').
instance_of('bibliography_of_orson_welles', 'bibliography').
instance_of('bibliography_of_woodrow_wilson', 'bibliography').
instance_of('bibliography_of_zakariyya_kandhlawi', 'human').
instance_of('autobiografiction', 'genre').
instance_of('autobiography', 'literary_genre').
instance_of('autobiography', 'book_form').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography_of_winston_churchill', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'written_work').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_stephen_harper', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_stephen_king', 'wikimedia_list_article').
instance_of('bibliography_of_stanis_aw_lem', 'bibliography').
instance_of('bibliography_of_lili_uokalani', 'bibliography').
instance_of('bibliography_of_abraham_lincoln', 'bibliography').
instance_of('bibliography_of_james_madison', 'bibliography').
instance_of('bibliography_of_works_on_madonna', 'bibliography').
instance_of('bibliography_of_william_mckinley', 'bibliography').
instance_of('bibliography_of_works_on_adolfas_mekas', 'bibliography').
instance_of('hayao_miyazaki_bibliography', 'bibliography').
instance_of('bibliography_of_james_monroe', 'public_election').
instance_of('bibliography_of_abul_hasan_ali_hasani_nadwi', 'book').
instance_of('bibliography_of_napoleon', 'bibliography').
instance_of('bibliography_of_richard_nixon', 'bibliography').
instance_of('bibliography_of_shibli_nomani', 'book').
instance_of('bibliography_of_barack_obama', 'wikimedia_list_article').
instance_of('bibliography_of_louis_joseph_papineau', 'bibliography').
instance_of('bibliography_of_harold_pinter', 'bibliography').
instance_of('bibliography_of_pope_pius_xii', 'bibliography').
instance_of('bibliography_of_ramakrishna', 'bibliography').
instance_of('bibliography_of_ayn_rand_and_objectivism', 'bibliography').
instance_of('bibliography_of_ronald_reagan', 'bibliography').
instance_of('bibliography_of_jacques_rivette', 'bibliography').
instance_of('bibliography_of_jane_roberts', 'bibliography').
instance_of('bibliography_of_eleanor_roosevelt', 'bibliography').
instance_of('bibliography_of_eleanor_roosevelt', 'wikimedia_list_article').
instance_of('bibliography_of_franklin_d__roosevelt', 'bibliography').
instance_of('bibliography_of_theodore_roosevelt', 'bibliography').
instance_of('bibliography_of_works_on_shakira', 'bibliography').
instance_of('the_works_of_m__p__shiel', 'literary_work').
instance_of('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'literary_work').
instance_of('bibliography_of_william_howard_taft', 'bibliography').
instance_of('bibliography_of_margaret_thatcher', 'bibliography').
instance_of('bibliography_of_justin_trudeau', 'bibliography').
instance_of('bibliography_of_harry_s__truman', 'bibliography').
instance_of('bibliography_of_donald_trump', 'personal_bibliography').
instance_of('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'bibliography').
instance_of('bibliography_of_martin_van_buren', 'bibliography').
instance_of('bibliography_of_swami_vivekananda', 'bibliography').
instance_of('bibliography_of_george_washington', 'bibliography').
instance_of('bibliography_of_orson_welles', 'bibliography').
instance_of('bibliography_of_woodrow_wilson', 'bibliography').
instance_of('bibliography_of_zakariyya_kandhlawi', 'human').
instance_of('autobiografiction', 'genre').
instance_of('autobiography', 'literary_genre').
instance_of('autobiography', 'book_form').
instance_of('biographical_evaluation', 'academic_discipline').
instance_of('biographical_novel', 'novel_genre').
instance_of('portal_biography', 'wikimedia_portal').
instance_of('biography_in_literature', 'branch_of_literature').
instance_of('clerihew', 'poetry_genre').
instance_of('biographical_film', 'film_genre').
instance_of('photobiography', 'art_genre').
instance_of('psychobiography', 'literary_genre').
instance_of('psychobiography', 'field_of_work').
instance_of('coat_of_arms_of_charles_v__holy_roman_emperor', 'coat_of_arms').
instance_of('giedroy_', 'family_name').
instance_of('coat_of_arms_of_the_king_of_spain', 'coat_of_arms').
instance_of('coat_of_arms_of_the_prince_of_asturias', 'coat_of_arms').
instance_of('coat_of_arms_of_the_prince_of_wales', 'coat_of_arms').
instance_of('coat_of_arms_of_the_united_kingdom', 'national_coat_of_arms').
instance_of('coat_of_arms_of_the_united_kingdom', 'royal_coat_of_arms').
instance_of('luciana_achugar', 'human').
instance_of('eden_ahbez', 'human').
instance_of('alan_dawa_dolma', 'human').
instance_of('bill_bissett', 'human').
instance_of('danah_boyd', 'human').
instance_of('adrienne_maree_brown', 'human').
instance_of('mc_chris', 'human').
instance_of('maia_arson_crimew', 'human').
instance_of('d_bi_young_anitafrika', 'human').
instance_of('steve_depyssler', 'human').
instance_of('arthur_fforde', 'human').
instance_of('charles_ffoulkes', 'human').
instance_of('michael_ffrench_o_carroll', 'human').
instance_of('richard_ffrench_constant', 'human').
instance_of('rose_ffrench__1st_baroness_ffrench', 'human').
instance_of('barbara_findlay', 'human').
instance_of('brian_d_foy', 'human').
instance_of('debbie_tucker_green', 'human').
instance_of('jack_green__critic_', 'human').
instance_of('dream_hampton', 'human').
instance_of('rei_harakami', 'human').
instance_of('fredric_j__harris', 'human').
instance_of('imbi_the_girl', 'human').
instance_of('invincible__rapper_', 'human').
instance_of('pattrice_jones', 'human').
instance_of('shalan_joudry', 'human').
instance_of('valter_hugo_m_e', 'human').
instance_of('iris_menas', 'human').
instance_of('sj_miller', 'human').
instance_of('mxmtoon', 'human').
instance_of('bpnichol', 'human').
instance_of('conrad_o_brien_ffrench', 'human').
instance_of('bart_plantenga', 'human').
instance_of('john_a__powell', 'human').
instance_of('ellsworth_snyder', 'human').
instance_of('katherena_vermette', 'human').
instance_of('ruth_weiss__beat_poet_', 'human').
instance_of('bill_wurtz', 'human').
instance_of('avery_r__young', 'human').
instance_of('astronaut_family', 'family').
instance_of('aunt_sally', 'sport').
instance_of('aunt_sally', 'pub_game').
instance_of('aunt_sally', 'game').
instance_of('cassandra__metaphor_', 'syndrome').
instance_of('cassandra__metaphor_', 'metaphor').
instance_of('hobson_s_choice', 'dilemma').
instance_of('judgement_of_solomon', 'artistic_theme').
instance_of('judgement_of_solomon', 'bible_story').
instance_of('man_bites_dog', 'aphorism').
instance_of('master_slave__technology_', 'conceptual_model').
instance_of('nigger_in_the_woodpile', 'ethnophaulism').
instance_of('nigger_in_the_woodpile', 'q15841920').
instance_of('o_captain__my_captain_', 'literary_work').
instance_of('poster_child', 'metaphor').
instance_of('procrustes', 'mythological_greek_character').
instance_of('shooting_the_messenger', 'concept').
instance_of('shooting_the_messenger', 'idiom').
instance_of('skeleton_in_the_closet', 'idiom').
instance_of('skeleton_in_the_closet', 'colloquial_expression').
instance_of('whipping_boy', 'historical_profession').
instance_of('personhood', 'property').
instance_of('abortion_debate', 'debate').
instance_of('agency__philosophy_', 'philosophical_concept').
instance_of('agency__philosophy_', 'type_of_property').
instance_of('beginning_of_human_personhood', 'opinion').
instance_of('fetal_rights', 'human_rights').
instance_of('great_ape_personhood', 'social_movement').
instance_of('great_ape_personhood', 'generalization').
instance_of('human_rights_in_dubai', 'human_rights_by_country_or_territory').
instance_of('hypatia_transracialism_controversy', 'occurrence').
instance_of('individual', 'unit_of_analysis').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('luciana_achugar', 'dancer').
occupation('luciana_achugar', 'choreographer').
occupation('eden_ahbez', 'composer').
occupation('eden_ahbez', 'singer_songwriter').
occupation('eden_ahbez', 'songwriter').
occupation('eden_ahbez', 'poet').
occupation('alan_dawa_dolma', 'model').
occupation('alan_dawa_dolma', 'pianist').
occupation('alan_dawa_dolma', 'singer').
occupation('alan_dawa_dolma', 'actor').
occupation('alan_dawa_dolma', 'fashion_model').
occupation('bill_bissett', 'painter').
occupation('bill_bissett', 'writer').
occupation('bill_bissett', 'publisher').
occupation('bill_bissett', 'poet').
occupation('danah_boyd', 'blogger').
occupation('danah_boyd', 'university_teacher').
occupation('adrienne_maree_brown', 'podcaster').
occupation('adrienne_maree_brown', 'climate_activist').
occupation('adrienne_maree_brown', 'poet').
occupation('adrienne_maree_brown', 'writer').
occupation('adrienne_maree_brown', 'musician').
occupation('mc_chris', 'rapper').
occupation('mc_chris', 'musician').
occupation('mc_chris', 'voice_actor').
occupation('mc_chris', 'screenwriter').
occupation('maia_arson_crimew', 'security_hacker').
occupation('maia_arson_crimew', 'security_researcher').
occupation('maia_arson_crimew', 'disc_jockey').
occupation('maia_arson_crimew', 'software_developer').
occupation('maia_arson_crimew', 'hacktivist').
occupation('maia_arson_crimew', 'hacker').
occupation('d_bi_young_anitafrika', 'actor').
occupation('d_bi_young_anitafrika', 'musician').
occupation('d_bi_young_anitafrika', 'poet').
occupation('steve_depyssler', 'air_force_officer').
occupation('arthur_fforde', 'poet').
occupation('charles_ffoulkes', 'weapon_historian').
occupation('charles_ffoulkes', 'curator').
occupation('charles_ffoulkes', 'historian').
occupation('michael_ffrench_o_carroll', 'politician').
occupation('richard_ffrench_constant', 'university_teacher').
occupation('richard_ffrench_constant', 'entomologist').
occupation('richard_ffrench_constant', 'biologist').
occupation('richard_ffrench_constant', 'scientist').
occupation('rose_ffrench__1st_baroness_ffrench', 'politician').
occupation('barbara_findlay', 'lawyer').
occupation('barbara_findlay', 'women_s_rights_activist').
occupation('brian_d_foy', 'computer_scientist').
occupation('brian_d_foy', 'engineer').
occupation('brian_d_foy', 'writer').
occupation('debbie_tucker_green', 'playwright').
occupation('debbie_tucker_green', 'writer').
occupation('debbie_tucker_green', 'screenwriter').
occupation('debbie_tucker_green', 'film_director').
occupation('jack_green__critic_', 'journalist').
occupation('jack_green__critic_', 'literary_critic').
occupation('dream_hampton', 'music_journalist').
occupation('dream_hampton', 'journalist').
occupation('dream_hampton', 'film_director').
occupation('dream_hampton', 'television_director').
occupation('rei_harakami', 'musician').
occupation('rei_harakami', 'composer').
occupation('fredric_j__harris', 'electrical_engineer').
occupation('fredric_j__harris', 'university_teacher').
occupation('imbi_the_girl', 'rapper').
occupation('imbi_the_girl', 'singer_songwriter').
occupation('invincible__rapper_', 'rapper').
occupation('pattrice_jones', 'writer').
occupation('pattrice_jones', 'teacher').
occupation('pattrice_jones', 'activist').
occupation('shalan_joudry', 'poet').
occupation('shalan_joudry', 'producer').
occupation('shalan_joudry', 'ecologist').
occupation('shalan_joudry', 'filmmaker').
occupation('shalan_joudry', 'actor').
occupation('shalan_joudry', 'storyteller').
occupation('shalan_joudry', 'playwright').
occupation('valter_hugo_m_e', 'poet').
occupation('valter_hugo_m_e', 'writer').
occupation('iris_menas', 'actor').
occupation('sj_miller', 'activist').
occupation('sj_miller', 'orator').
occupation('sj_miller', 'professor').
occupation('mxmtoon', 'television_producer').
occupation('mxmtoon', 'youtuber').
occupation('mxmtoon', 'singer_songwriter').
occupation('mxmtoon', 'vlogger').
occupation('bpnichol', 'poet').
occupation('conrad_o_brien_ffrench', 'military_personnel').
occupation('bart_plantenga', 'disc_jockey').
occupation('john_a__powell', 'teacher').
occupation('ellsworth_snyder', 'artist').
occupation('ellsworth_snyder', 'composer').
occupation('ellsworth_snyder', 'pianist').
occupation('katherena_vermette', 'film_director').
occupation('katherena_vermette', 'poet').
occupation('katherena_vermette', 'writer').
occupation('katherena_vermette', 'novelist').
occupation('katherena_vermette', 'children_s_writer').
occupation('ruth_weiss__beat_poet_', 'writer').
occupation('ruth_weiss__beat_poet_', 'poet').
occupation('bill_wurtz', 'musician').
occupation('bill_wurtz', 'youtuber').
occupation('bill_wurtz', 'television_producer').
occupation('avery_r__young', 'singer').
occupation('avery_r__young', 'poet').
occupation('avery_r__young', 'visual_artist').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('bibliography_of_james_monroe', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('bibliography_of_james_monroe', 'united_states').
country('coat_of_arms_of_charles_v__holy_roman_emperor', 'spain').
country('coat_of_arms_of_charles_v__holy_roman_emperor', 'germania').
country('coat_of_arms_of_the_ni_o_family', 'spain').
country('coat_of_arms_of_the_king_of_spain', 'spain').
country('coat_of_arms_of_the_prince_of_asturias', 'spain').
country('coat_of_arms_of_the_prince_of_spain', 'spain').
country('coat_of_arms_of_the_united_kingdom', 'united_kingdom').
country('coat_of_arms_of_the_united_kingdom', 'united_kingdom_of_great_britain_and_ireland').
country('human_rights_in_dubai', 'united_arab_emirates').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'bibliography').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_stephen_harper', 'stephen_harper').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('bibliography_of_stanis_aw_lem', 'stanislav_lem').
main_subject('bibliography_of_richard_nixon', 'richard_nixon').
main_subject('bibliography_of_jacques_rivette', 'jacques_rivette').
main_subject('the_works_of_m__p__shiel', 'm__p__shiel').
main_subject('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'clark_ashton_smith').
main_subject('bibliography_of_margaret_thatcher', 'margaret_thatcher').
main_subject('bibliography_of_justin_trudeau', 'justin_trudeau').
main_subject('bibliography_of_donald_trump', 'donald_trump').
main_subject('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'first_lady_of_the_united_states').
main_subject('bibliography_of_martin_van_buren', 'martin_van_buren').
main_subject('bibliography_of_swami_vivekananda', 'swami_vivekananda').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'bibliography').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_stephen_harper', 'stephen_harper').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('bibliography_of_stanis_aw_lem', 'stanislav_lem').
main_subject('bibliography_of_richard_nixon', 'richard_nixon').
main_subject('bibliography_of_jacques_rivette', 'jacques_rivette').
main_subject('the_works_of_m__p__shiel', 'm__p__shiel').
main_subject('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'clark_ashton_smith').
main_subject('bibliography_of_margaret_thatcher', 'margaret_thatcher').
main_subject('bibliography_of_justin_trudeau', 'justin_trudeau').
main_subject('bibliography_of_donald_trump', 'donald_trump').
main_subject('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'first_lady_of_the_united_states').
main_subject('bibliography_of_martin_van_buren', 'martin_van_buren').
main_subject('bibliography_of_swami_vivekananda', 'swami_vivekananda').
main_subject('o_captain__my_captain_', 'assassination_of_abraham_lincoln').
main_subject('abortion_debate', 'abortion').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_works_on_stephen_king', 'book').
is_a_list_of('bibliography_of_barack_obama', 'book').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_works_on_stephen_king', 'book').
is_a_list_of('bibliography_of_barack_obama', 'book').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('autobiography', 'category_autobiographies').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('autobiography', 'category_autobiographies').
topic_s_main_category('biographical_evaluation', 'category_ilm_ar_rijal').
topic_s_main_category('biographical_novel', 'category_biographical_novels').
topic_s_main_category('portal_biography', 'category_biography_portal').
topic_s_main_category('biographical_film', 'category_biographical_films').
topic_s_main_category('coat_of_arms_of_the_united_kingdom', 'category_british_coats_of_arms').
topic_s_main_category('personhood', 'category_personhood').
topic_s_main_category('abortion_debate', 'category_abortion_debate').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'united_states').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('the_works_of_m__p__shiel', 'united_states').
country_of_origin('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'united_states').
country_of_origin('bibliography_of_donald_trump', 'united_states').
country_of_origin('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'united_states').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('the_works_of_m__p__shiel', 'united_states').
country_of_origin('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'united_states').
country_of_origin('bibliography_of_donald_trump', 'united_states').
country_of_origin('aunt_sally', 'england').
sport('bibliography_of_bobby_fischer', 'chess').
sport('bibliography_of_bobby_fischer', 'chess').
sport('bibliography_of_bobby_fischer', 'chess').
sport('bibliography_of_bobby_fischer', 'chess').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'english').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('the_works_of_m__p__shiel', 'english').
language_of_work_or_name('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'english').
language_of_work_or_name('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'english').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('the_works_of_m__p__shiel', 'english').
language_of_work_or_name('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'english').
language_of_work_or_name('giedroy_', 'polish').
language_of_work_or_name('o_captain__my_captain_', 'english').
language_of_work_or_name('siyokoy__linguistics_', 'tagalog').
author('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'henry_hardy_heins').
author('the_works_of_m__p__shiel', 'albert_reynolds_morse').
author('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'donald_sidney_fryer').
author('bibliography_of_donald_trump', 'donald_trump').
author('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'henry_hardy_heins').
author('the_works_of_m__p__shiel', 'albert_reynolds_morse').
author('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'donald_sidney_fryer').
author('bibliography_of_donald_trump', 'donald_trump').
author('o_captain__my_captain_', 'walt_whitman').
genre('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'bibliography').
genre('the_works_of_m__p__shiel', 'bibliography').
genre('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'bibliography').
genre('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'bibliography').
genre('the_works_of_m__p__shiel', 'bibliography').
genre('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'bibliography').
genre('23_people', 'memoir').
genre('eden_ahbez', 'exotica').
genre('alan_dawa_dolma', 'j_pop').
genre('mc_chris', 'hip_hop').
genre('mc_chris', 'nerdcore').
genre('mc_chris', 'rapping').
genre('rei_harakami', 'electronic_music').
genre('invincible__rapper_', 'hip_hop').
genre('mxmtoon', 'folk_pop').
genre('mxmtoon', 'lofi_hip_hop').
genre('mxmtoon', 'pop_music').
genre('mxmtoon', 'indie_pop').
genre('mxmtoon', 'bedroom_pop').
genre('mxmtoon', 'vlog').
genre('o_captain__my_captain_', 'poetry').
publisher('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'donald_m__grant__publisher').
publisher('bibliography_of_stephen_harper', 'english_wikipedia').
publisher('the_works_of_m__p__shiel', 'fantasy_publishing_company__inc_').
publisher('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'donald_m__grant__publisher').
publisher('bibliography_of_justin_trudeau', 'english_wikipedia').
publisher('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'donald_m__grant__publisher').
publisher('bibliography_of_stephen_harper', 'english_wikipedia').
publisher('the_works_of_m__p__shiel', 'fantasy_publishing_company__inc_').
publisher('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'donald_m__grant__publisher').
publisher('bibliography_of_justin_trudeau', 'english_wikipedia').
cover_art_by('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'j__allen_st__john').
cover_art_by('the_works_of_m__p__shiel', 'salvador_dal_').
cover_art_by('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'ned_dameron').
cover_art_by('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'j__allen_st__john').
cover_art_by('the_works_of_m__p__shiel', 'salvador_dal_').
cover_art_by('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'ned_dameron').
sex_or_gender('bibliography_of_zakariyya_kandhlawi', 'male').
sex_or_gender('bibliography_of_zakariyya_kandhlawi', 'male').
sex_or_gender('luciana_achugar', 'female').
sex_or_gender('eden_ahbez', 'male').
sex_or_gender('alan_dawa_dolma', 'female').
sex_or_gender('bill_bissett', 'male').
sex_or_gender('danah_boyd', 'female').
sex_or_gender('adrienne_maree_brown', 'female').
sex_or_gender('mc_chris', 'male').
sex_or_gender('maia_arson_crimew', 'non_binary').
sex_or_gender('d_bi_young_anitafrika', 'female').
sex_or_gender('steve_depyssler', 'male').
sex_or_gender('arthur_fforde', 'male').
sex_or_gender('charles_ffoulkes', 'male').
sex_or_gender('michael_ffrench_o_carroll', 'male').
sex_or_gender('richard_ffrench_constant', 'male').
sex_or_gender('rose_ffrench__1st_baroness_ffrench', 'female').
sex_or_gender('barbara_findlay', 'cisgender_woman').
sex_or_gender('brian_d_foy', 'male').
sex_or_gender('debbie_tucker_green', 'female').
sex_or_gender('jack_green__critic_', 'male').
sex_or_gender('dream_hampton', 'female').
sex_or_gender('rei_harakami', 'male').
sex_or_gender('fredric_j__harris', 'male').
sex_or_gender('imbi_the_girl', 'non_binary').
sex_or_gender('invincible__rapper_', 'non_binary').
sex_or_gender('pattrice_jones', 'female').
sex_or_gender('shalan_joudry', 'female').
sex_or_gender('valter_hugo_m_e', 'male').
sex_or_gender('iris_menas', 'non_binary').
sex_or_gender('sj_miller', 'non_binary').
sex_or_gender('mxmtoon', 'female').
sex_or_gender('bpnichol', 'male').
sex_or_gender('conrad_o_brien_ffrench', 'male').
sex_or_gender('bart_plantenga', 'male').
sex_or_gender('john_a__powell', 'male').
sex_or_gender('ellsworth_snyder', 'male').
sex_or_gender('katherena_vermette', 'female').
sex_or_gender('ruth_weiss__beat_poet_', 'female').
sex_or_gender('bill_wurtz', 'male').
sex_or_gender('avery_r__young', 'male').
sex_or_gender('procrustes', 'male').
described_by_source('biography', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('biography', 'gujin_tushu_jicheng').
described_by_source('biography', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('biography', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('autobiography', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('biography', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('biography', 'gujin_tushu_jicheng').
described_by_source('biography', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('biography', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('autobiography', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('eden_ahbez', 'ob_lky_knih').
described_by_source('bell_hooks', 'ob_lky_knih').
described_by_source('bell_hooks', 'contemporary_black_biography').
described_by_source('bell_hooks', 'notable_black_american_women').
described_by_source('bell_hooks', 'encyclopedia_of_african_american_women_writers').
described_by_source('bell_hooks', 'american_women_writers').
described_by_source('k_d__lang', 'ob_lky_knih').
described_by_source('bpnichol', 'ubuweb').
described_by_source('ruth_weiss__beat_poet_', 'biografia__lexikon__sterreichischer_frauen').
described_by_source('will_i_am', 'ob_lky_knih').
described_by_source('aunt_sally', 'encyclop_dia_britannica_11th_edition').
described_by_source('hobson_s_choice', 'encyclop_dia_britannica_11th_edition').
described_by_source('procrustes', 'pauly_wissowa').
described_by_source('procrustes', 'granat_encyclopedic_dictionary').
described_by_source('procrustes', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('procrustes', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('procrustes', 'armenian_soviet_encyclopedia').
described_by_source('procrustes', 'the_nuttall_encyclop_dia').
described_by_source('procrustes', 'encyclop_dia_britannica_11th_edition').
described_by_source('person', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('individual', 'explanatory_dictionary_of_the_living_great_russian_language').
described_by_source('individual', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('individual', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('individual', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('individual', 'national_encyclopedia_of_uzbekistan').
described_by_source('individual', 'encyclopedia_of_armenian_nature').
different_from('biography', 'biographical_article').
different_from('biography', 'biography').
different_from('biography', 'vita').
different_from('biography', 'biographer').
different_from('autobiography', 'personal_history').
different_from('autobiography', 'memoir').
different_from('biography', 'biographical_article').
different_from('biography', 'biography').
different_from('biography', 'vita').
different_from('biography', 'biographer').
different_from('autobiography', 'personal_history').
different_from('autobiography', 'memoir').
different_from('giedroy_', 'giedraitis').
different_from('giedroy_', 'giedroyc').
different_from('dodie', 'dido').
different_from('master_slave__technology_', 'master_slave').
different_from('master_slave__technology_', 'peer_to_peer').
different_from('siyokoy__linguistics_', 'siyokoy').
different_from('whipping_boy', 'the_whipping_boy').
different_from('personhood', 'corporate_personhood').
different_from('personhood', 'persona').
different_from('personhood', 'person').
different_from('personhood', 'ethnicity').
different_from('person', 'corporate_personhood').
different_from('person', 'fulbe_people').
different_from('agency__philosophy_', 'agency').
studied_by('biography', 'biographistics').
studied_by('biography', 'biographistics').
has_part_s_('autobiografiction', 'fiction').
has_part_s_('autobiografiction', 'autobiography').
has_part_s_('autobiografiction', 'fiction').
has_part_s_('autobiografiction', 'autobiography').
has_part_s_('biography_in_literature', 'biographical_criticism').
has_part_s_('coat_of_arms_of_the_king_of_spain', 'spanish_royal_crown').
has_part_s_('coat_of_arms_of_the_king_of_spain', 'golden_fleece').
has_part_s_('coat_of_arms_of_the_united_kingdom', 'dieu_et_mon_droit').
has_part_s_('coat_of_arms_of_the_united_kingdom', 'coat_of_arms_of_ireland').
has_part_s_('coat_of_arms_of_the_united_kingdom', 'royal_coat_of_arms_of_great_britain').
has_part_s_('great_ape_personhood', 'habeas_corpus').
has_part_s_('great_ape_personhood', 'protection').
partially_coincident_with('autobiografiction', 'autofiction').
partially_coincident_with('autobiografiction', 'autofiction').
opposite_of('autobiography', 'heterobiography').
opposite_of('autobiography', 'heterobiography').
opposite_of('person', 'society').
subclass_of('biographical_criticism', 'literary_studies').
subclass_of('biographical_criticism', 'literary_criticism').
subclass_of('biographical_criticism', 'literary_studies').
subclass_of('biographical_criticism', 'literary_criticism').
subclass_of('biographical_novel', 'historical_novel').
subclass_of('biographical_novel', 'biographical_book').
subclass_of('clerihew', 'humorous_poetry').
subclass_of('biographical_film', 'film').
subclass_of('biographical_film', 'biographical_work').
subclass_of('legal_biography', 'biography').
subclass_of('photobiography', 'photography').
subclass_of('photobiography', 'biography').
subclass_of('psychobiography', 'biography').
subclass_of('burgher_arms', 'coat_of_arms').
subclass_of('cassandra__metaphor_', 'asperger_syndrome').
subclass_of('mcnamara_fallacy', 'sampling_bias').
subclass_of('siyokoy__linguistics_', 'hybrid_word').
subclass_of('agency__philosophy_', 'aptitude').
subclass_of('environmental_personhood', 'personhood').
subclass_of('fetal_rights', 'legal_position_of_the_conceived').
subclass_of('great_ape_personhood', 'subjective_right').
subclass_of('great_ape_personhood', 'animal_rights').
subclass_of('great_ape_personhood', 'universal_suffrage').
subclass_of('individual', 'being').
subclass_of('individual', 'organism').
part_of('biographical_evaluation', 'science_of_hadith').
part_of('cassandra__metaphor_', 'psychology_terminology').
part_of('cassandra__metaphor_', 'greek_mythology').
part_of('judgement_of_solomon', 'first_book_of_kings').
part_of('individual', 'organization').
part_of('individual', 'society').
uses('biographical_novel', 'fictionalisation').
is_the_study_of('biography_in_literature', 'biography').
is_the_study_of('biography_in_literature', 'literature').
has_list('biographical_film', 'list_of_biographical_films').
model_item('psychobiography', 'leonardo_da_vinci__a_memory_of_his_childhood').
used_by('coat_of_arms_of_charles_v__holy_roman_emperor', 'charles_v').
writing_system('giedroy_', 'latin_script').
depicts('coat_of_arms_of_the_king_of_spain', 'felipe_vi_of_spain').
depicts('coat_of_arms_of_the_united_kingdom', 'tudor_rose').
depicts('coat_of_arms_of_the_united_kingdom', 'lion').
depicts('coat_of_arms_of_the_united_kingdom', 'st_edward_s_crown').
depicts('coat_of_arms_of_the_united_kingdom', 'tressure_flory').
depicts('coat_of_arms_of_the_united_kingdom', 'threefoil').
depicts('coat_of_arms_of_the_united_kingdom', 'royal_coat_of_arms_in_scotland').
depicts('coat_of_arms_of_the_united_kingdom', 'unicorn').
depicts('coat_of_arms_of_the_united_kingdom', 'harp').
depicts('coat_of_arms_of_the_united_kingdom', 'lion').
depicts('coat_of_arms_of_the_united_kingdom', 'coat_of_arms_of_ireland').
depicts('coat_of_arms_of_the_united_kingdom', 'thistle').
depicts('coat_of_arms_of_the_united_kingdom', 'royal_arms_of_england').
applies_to_jurisdiction('coat_of_arms_of_the_king_of_spain', 'juan_carlos_i_of_spain').
applies_to_jurisdiction('coat_of_arms_of_the_united_kingdom', 'united_kingdom').
applies_to_jurisdiction('coat_of_arms_of_the_united_kingdom', 'united_kingdom_of_great_britain_and_ireland').
given_name('luciana_achugar', 'luciana').
given_name('eden_ahbez', 'george').
given_name('eden_ahbez', 'alexander').
given_name('alan_dawa_dolma', 'alan').
given_name('bill_bissett', 'bill').
given_name('adrienne_maree_brown', 'adrienne').
given_name('adrienne_maree_brown', 'maree').
given_name('mc_chris', 'christopher').
given_name('mc_chris', 'brendan').
given_name('maia_arson_crimew', 'tillie').
given_name('maia_arson_crimew', 'maia').
given_name('steve_depyssler', 'steve').
given_name('dodie', 'miranda').
given_name('dodie', 'dorothy').
given_name('arthur_fforde', 'q1778168').
given_name('charles_ffoulkes', 'charles').
given_name('michael_ffrench_o_carroll', 'michael').
given_name('richard_ffrench_constant', 'richard').
given_name('rose_ffrench__1st_baroness_ffrench', 'rose').
given_name('barbara_findlay', 'barbara').
given_name('brian_d_foy', 'brian').
given_name('debbie_tucker_green', 'debbie').
given_name('jack_green__critic_', 'jack').
given_name('dream_hampton', 'dream').
given_name('fredric_j__harris', 'fredric').
given_name('bell_hooks', 'gloria').
given_name('invincible__rapper_', 'ilana').
given_name('pattrice_jones', 'patrice').
given_name('k_d__lang', 'kathryn').
given_name('valter_hugo_m_e', 'hugo').
given_name('valter_hugo_m_e', 'valter').
given_name('iris_menas', 'iris').
given_name('conrad_o_brien_ffrench', 'conrad').
given_name('bart_plantenga', 'bart').
given_name('john_a__powell', 'q4925477').
given_name('ellsworth_snyder', 'ellsworth').
given_name('katherena_vermette', 'katherena').
given_name('katherena_vermette', 'angy').
given_name('ruth_weiss__beat_poet_', 'ruth').
given_name('bill_wurtz', 'bill').
award_received('luciana_achugar', 'guggenheim_fellowship').
award_received('danah_boyd', 'fellow_of_the_american_association_for_the_advancement_of_science').
award_received('d_bi_young_anitafrika', 'dora_mavor_moore_awards').
award_received('arthur_fforde', 'knight_bachelor').
award_received('arthur_fforde', 'knight_grand_cross_of_the_order_of_the_british_empire').
award_received('richard_ffrench_constant', 'fellow_of_the_royal_society').
award_received('debbie_tucker_green', 'windham_campbell_literature_prizes').
award_received('fredric_j__harris', 'ieee_fellow').
award_received('shalan_joudry', 'robert_merritt_awards').
award_received('shalan_joudry', 'atlantic_book_awards___festival').
award_received('valter_hugo_m_e', 'jos__saramago_prize').
award_received('katherena_vermette', 'governor_general_s_literary_awards').
family_name('luciana_achugar', 'achugar').
family_name('eden_ahbez', 'aberle').
family_name('bill_bissett', 'bissett').
family_name('danah_boyd', 'boyd').
family_name('adrienne_maree_brown', 'brown').
family_name('mc_chris', 'ward').
family_name('d_bi_young_anitafrika', 'young').
family_name('dodie', 'clark').
family_name('arthur_fforde', 'fforde').
family_name('michael_ffrench_o_carroll', 'ffrench_o_carroll').
family_name('michael_ffrench_o_carroll', 'o_carroll').
family_name('michael_ffrench_o_carroll', 'ffrench').
family_name('richard_ffrench_constant', 'ffrench_constant').
family_name('rose_ffrench__1st_baroness_ffrench', 'dillon').
family_name('rose_ffrench__1st_baroness_ffrench', 'ffrench').
family_name('barbara_findlay', 'q16869941').
family_name('debbie_tucker_green', 'green').
family_name('jack_green__critic_', 'green').
family_name('dream_hampton', 'hampton').
family_name('fredric_j__harris', 'harris').
family_name('bell_hooks', 'watkins').
family_name('invincible__rapper_', 'weaver').
family_name('pattrice_jones', 'jones').
family_name('k_d__lang', 'lang').
family_name('iris_menas', 'menas').
family_name('sj_miller', 'miller').
family_name('bpnichol', 'nichol').
family_name('conrad_o_brien_ffrench', 'o_brien_ffrench').
family_name('bart_plantenga', 'plantenga').
family_name('john_a__powell', 'powell').
family_name('ellsworth_snyder', 'snyder').
family_name('katherena_vermette', 'vermette').
family_name('ruth_weiss__beat_poet_', 'weiss').
family_name('bill_wurtz', 'wurtz').
family_name('avery_r__young', 'young').
country_of_citizenship('luciana_achugar', 'uruguay').
country_of_citizenship('luciana_achugar', 'united_states').
country_of_citizenship('eden_ahbez', 'united_states').
country_of_citizenship('alan_dawa_dolma', 'people_s_republic_of_china').
country_of_citizenship('bill_bissett', 'canada').
country_of_citizenship('danah_boyd', 'united_states').
country_of_citizenship('adrienne_maree_brown', 'united_states').
country_of_citizenship('mc_chris', 'united_states').
country_of_citizenship('maia_arson_crimew', 'switzerland').
country_of_citizenship('d_bi_young_anitafrika', 'canada').
country_of_citizenship('steve_depyssler', 'united_states').
country_of_citizenship('charles_ffoulkes', 'united_kingdom_of_great_britain_and_ireland').
country_of_citizenship('charles_ffoulkes', 'united_kingdom').
country_of_citizenship('michael_ffrench_o_carroll', 'ireland').
country_of_citizenship('barbara_findlay', 'canada').
country_of_citizenship('brian_d_foy', 'united_states').
country_of_citizenship('debbie_tucker_green', 'united_kingdom').
country_of_citizenship('jack_green__critic_', 'united_states').
country_of_citizenship('dream_hampton', 'united_states').
country_of_citizenship('rei_harakami', 'japan').
country_of_citizenship('imbi_the_girl', 'australia').
country_of_citizenship('invincible__rapper_', 'united_states').
country_of_citizenship('pattrice_jones', 'united_states').
country_of_citizenship('shalan_joudry', 'canada').
country_of_citizenship('valter_hugo_m_e', 'portugal').
country_of_citizenship('iris_menas', 'united_states').
country_of_citizenship('sj_miller', 'united_states').
country_of_citizenship('mxmtoon', 'united_states').
country_of_citizenship('bpnichol', 'canada').
country_of_citizenship('bart_plantenga', 'united_states').
country_of_citizenship('ellsworth_snyder', 'united_states').
country_of_citizenship('katherena_vermette', 'canada').
country_of_citizenship('ruth_weiss__beat_poet_', 'united_states').
country_of_citizenship('bill_wurtz', 'united_states').
place_of_birth('luciana_achugar', 'montevideo').
place_of_birth('eden_ahbez', 'brooklyn').
place_of_birth('alan_dawa_dolma', 'kangding').
place_of_birth('bill_bissett', 'halifax').
place_of_birth('danah_boyd', 'altoona').
place_of_birth('adrienne_maree_brown', 'el_paso').
place_of_birth('mc_chris', 'libertyville').
place_of_birth('maia_arson_crimew', 'lucerne').
place_of_birth('d_bi_young_anitafrika', 'kingston').
place_of_birth('steve_depyssler', 'chicago').
place_of_birth('charles_ffoulkes', 'london').
place_of_birth('michael_ffrench_o_carroll', 'dublin').
place_of_birth('brian_d_foy', 'united_states').
place_of_birth('debbie_tucker_green', 'london').
place_of_birth('dream_hampton', 'detroit').
place_of_birth('rei_harakami', 'hiroshima').
place_of_birth('fredric_j__harris', 'brooklyn').
place_of_birth('imbi_the_girl', 'sydney').
place_of_birth('invincible__rapper_', 'champaign').
place_of_birth('pattrice_jones', 'baltimore').
place_of_birth('shalan_joudry', 'bear_river_6a').
place_of_birth('valter_hugo_m_e', 'saurimo').
place_of_birth('iris_menas', 'wichita').
place_of_birth('mxmtoon', 'oakland').
place_of_birth('bpnichol', 'vancouver').
place_of_birth('conrad_o_brien_ffrench', 'london').
place_of_birth('bart_plantenga', 'amsterdam').
place_of_birth('john_a__powell', 'detroit').
place_of_birth('katherena_vermette', 'winnipeg').
place_of_birth('ruth_weiss__beat_poet_', 'berlin').
ethnic_group('luciana_achugar', 'uruguayan_americans').
ethnic_group('shalan_joudry', 'mi_kmaw').
ethnic_group('katherena_vermette', 'm_tis').
place_of_death('eden_ahbez', 'los_angeles').
place_of_death('steve_depyssler', 'bossier_city').
place_of_death('charles_ffoulkes', 'oxford').
place_of_death('bpnichol', 'toronto').
place_of_death('conrad_o_brien_ffrench', 'loveland').
place_of_death('ruth_weiss__beat_poet_', 'albion').
influenced_by('eden_ahbez', 'john_and_vera_richter').
influenced_by('bell_hooks', 'th_ch_nh_t_h_nh').
influenced_by('bell_hooks', 'gustavo_guti_rrez').
influenced_by('bell_hooks', 'lorraine_hansberry').
influenced_by('bell_hooks', 'sojourner_truth').
influenced_by('bell_hooks', 'toni_morrison').
influenced_by('bell_hooks', 'martin_luther_king_jr_').
influenced_by('bell_hooks', 'erich_fromm').
influenced_by('bell_hooks', 'malcolm_x').
influenced_by('bell_hooks', 'paulo_freire').
influenced_by('k_d__lang', 'kitty_wells').
influenced_by('k_d__lang', 'patsy_cline').
influenced_by('great_ape_personhood', 'richard_dawkins').
influenced_by('great_ape_personhood', 'jane_goodall').
influenced_by('great_ape_personhood', 'paola_cavalieri').
influenced_by('great_ape_personhood', 'peter_singer').
influenced_by('great_ape_personhood', 'dawn_prince_hughes').
influenced_by('great_ape_personhood', 'steven_m__wise').
copyright_representative('eden_ahbez', 'american_society_of_composers__authors_and_publishers').
residence('eden_ahbez', 'hollywood_sign').
residence('adrienne_maree_brown', 'durham').
residence('maia_arson_crimew', 'lucerne').
residence('pattrice_jones', 'vermont').
cause_of_death('eden_ahbez', 'traffic_collision').
cause_of_death('steve_depyssler', 'covid_19').
cause_of_death('bell_hooks', 'kidney_failure').
height('alan_dawa_dolma', '158').
social_media_followers('alan_dawa_dolma', '22124').
social_media_followers('alan_dawa_dolma', '18712').
social_media_followers('danah_boyd', '230774').
social_media_followers('danah_boyd', '237700').
social_media_followers('adrienne_maree_brown', '32703').
social_media_followers('adrienne_maree_brown', '47893').
social_media_followers('adrienne_maree_brown', '359000').
social_media_followers('adrienne_maree_brown', '44705').
social_media_followers('mc_chris', '39636').
social_media_followers('mc_chris', '39699').
social_media_followers('mc_chris', '40027').
social_media_followers('maia_arson_crimew', '79218').
social_media_followers('maia_arson_crimew', '5584').
social_media_followers('maia_arson_crimew', '5737').
social_media_followers('dodie', '2020000').
social_media_followers('dodie', '1020094').
social_media_followers('dodie', '1970000').
social_media_followers('dodie', '2000000').
social_media_followers('dodie', '1002538').
social_media_followers('dodie', '1051882').
social_media_followers('dream_hampton', '104870').
social_media_followers('dream_hampton', '103544').
social_media_followers('dream_hampton', '101132').
social_media_followers('dream_hampton', '97093').
social_media_followers('invincible__rapper_', '9322').
social_media_followers('invincible__rapper_', '9486').
social_media_followers('mxmtoon', '872000').
social_media_followers('mxmtoon', '529590').
social_media_followers('mxmtoon', '180300').
social_media_followers('mxmtoon', '952000').
social_media_followers('mxmtoon', '489513').
social_media_followers('mxmtoon', '520084').
social_media_followers('mxmtoon', '929000').
social_media_followers('mxmtoon', '977000').
social_media_followers('will_i_am', '4710000').
social_media_followers('will_i_am', '4900000').
social_media_followers('will_i_am', '11932789').
social_media_followers('bill_wurtz', '144').
social_media_followers('bill_wurtz', '142').
social_media_followers('bill_wurtz', '365463').
social_media_followers('bill_wurtz', '137').
social_media_followers('bill_wurtz', '372577').
social_media_followers('bill_wurtz', '296090').
mass('alan_dawa_dolma', '40').
instrument('alan_dawa_dolma', 'voice').
instrument('alan_dawa_dolma', 'erhu').
instrument('mc_chris', 'voice').
instrument('dodie', 'voice').
instrument('imbi_the_girl', 'voice').
instrument('invincible__rapper_', 'voice').
instrument('k_d__lang', 'voice').
instrument('ellsworth_snyder', 'piano').
instrument('will_i_am', 'keyboard_instrument').
record_label('alan_dawa_dolma', 'avex_asia').
record_label('rei_harakami', 'q11305022').
record_label('k_d__lang', 'elektra').
record_label('k_d__lang', 'warner_bros__records').
record_label('k_d__lang', 'bumstead_records').
blood_type('alan_dawa_dolma', 'o').
educated_at('bill_bissett', 'university_of_british_columbia').
educated_at('bill_bissett', 'dalhousie_university').
educated_at('danah_boyd', 'massachusetts_institute_of_technology').
educated_at('danah_boyd', 'university_of_california__berkeley_school_of_information').
educated_at('danah_boyd', 'brown_university').
educated_at('danah_boyd', 'manheim_township_high_school').
educated_at('adrienne_maree_brown', 'columbia_university').
educated_at('mc_chris', 'new_york_university_tisch_school_of_the_arts').
educated_at('mc_chris', 'school_of_the_art_institute_of_chicago').
educated_at('arthur_fforde', 'trinity_college').
educated_at('arthur_fforde', 'rugby_school').
educated_at('michael_ffrench_o_carroll', 'school_of_medicine__trinity_college_dublin').
educated_at('richard_ffrench_constant', 'university_of_exeter').
educated_at('richard_ffrench_constant', 'imperial_college_london').
educated_at('barbara_findlay', 'university_of_british_columbia').
educated_at('barbara_findlay', 'queen_s_university').
educated_at('dream_hampton', 'new_york_university_tisch_school_of_the_arts').
educated_at('rei_harakami', 'kyoto_college_of_art').
educated_at('fredric_j__harris', 'aalborg_university').
educated_at('fredric_j__harris', 'san_diego_state_university').
educated_at('fredric_j__harris', 'new_york_university_tandon_school_of_engineering').
educated_at('pattrice_jones', 'university_of_michigan').
educated_at('pattrice_jones', 'towson_university').
educated_at('shalan_joudry', 'dalhousie_university').
educated_at('sj_miller', 'university_of_new_mexico').
educated_at('mxmtoon', 'lick_wilmerding_high_school').
educated_at('conrad_o_brien_ffrench', 'byam_shaw_school_of_art').
educated_at('conrad_o_brien_ffrench', 'st__aubyns_school').
educated_at('john_a__powell', 'university_of_minnesota').
educated_at('john_a__powell', 'stanford_university').
educated_at('john_a__powell', 'university_of_california__berkeley').
educated_at('ellsworth_snyder', 'university_of_wisconsin_madison').
educated_at('avery_r__young', 'loyola_university_chicago').
archives_at('bill_bissett', 'city_of_vancouver_archives').
archives_at('bill_bissett', 'clara_thomas_archives_and_special_collections').
archives_at('charles_ffoulkes', 'university_of_victoria_special_collections_and_university_archives').
languages_spoken__written_or_signed('bill_bissett', 'english').
languages_spoken__written_or_signed('adrienne_maree_brown', 'english').
languages_spoken__written_or_signed('mc_chris', 'english').
languages_spoken__written_or_signed('maia_arson_crimew', 'english').
languages_spoken__written_or_signed('maia_arson_crimew', 'swiss_german').
languages_spoken__written_or_signed('dodie', 'english').
languages_spoken__written_or_signed('richard_ffrench_constant', 'english').
languages_spoken__written_or_signed('barbara_findlay', 'english').
languages_spoken__written_or_signed('brian_d_foy', 'english').
languages_spoken__written_or_signed('debbie_tucker_green', 'english').
languages_spoken__written_or_signed('jack_green__critic_', 'english').
languages_spoken__written_or_signed('fredric_j__harris', 'english').
languages_spoken__written_or_signed('bell_hooks', 'american_english').
languages_spoken__written_or_signed('bell_hooks', 'english').
languages_spoken__written_or_signed('invincible__rapper_', 'english').
languages_spoken__written_or_signed('invincible__rapper_', 'hebrew').
languages_spoken__written_or_signed('k_d__lang', 'english').
languages_spoken__written_or_signed('valter_hugo_m_e', 'portuguese').
languages_spoken__written_or_signed('iris_menas', 'english').
languages_spoken__written_or_signed('bpnichol', 'english').
languages_spoken__written_or_signed('katherena_vermette', 'english').
languages_spoken__written_or_signed('katherena_vermette', 'french').
languages_spoken__written_or_signed('will_i_am', 'english').
languages_spoken__written_or_signed('bill_wurtz', 'english').
employer('danah_boyd', 'microsoft_research').
employer('danah_boyd', 'new_york_university').
employer('arthur_fforde', 'bbc').
employer('richard_ffrench_constant', 'university_of_exeter').
employer('richard_ffrench_constant', 'university_of_bath').
employer('richard_ffrench_constant', 'university_of_wisconsin_madison').
employer('fredric_j__harris', 'san_diego_state_university').
employer('sj_miller', 'new_york_university').
employer('conrad_o_brien_ffrench', 'secret_intelligence_service').
employer('john_a__powell', 'university_of_san_francisco').
employer('john_a__powell', 'american_university').
employer('john_a__powell', 'moritz_college_of_law').
employer('john_a__powell', 'university_of_minnesota').
employer('john_a__powell', 'ohio_state_university').
employer('john_a__powell', 'harvard_university').
employer('john_a__powell', 'university_of_miami').
employer('john_a__powell', 'university_of_california__berkeley__school_of_law').
employer('john_a__powell', 'columbia_university').
employer('john_a__powell', 'american_civil_liberties_union').
employer('john_a__powell', 'haas_institute_for_a_fair_and_inclusive_society').
field_of_work('danah_boyd', 'social_media').
field_of_work('charles_ffoulkes', 'history').
field_of_work('charles_ffoulkes', 'body_armor').
field_of_work('charles_ffoulkes', 'curating').
field_of_work('charles_ffoulkes', 'historic_weapon').
field_of_work('richard_ffrench_constant', 'insecticide_resistance').
field_of_work('richard_ffrench_constant', 'evolution').
field_of_work('richard_ffrench_constant', 'entomology').
field_of_work('richard_ffrench_constant', 'molecular_biology').
field_of_work('richard_ffrench_constant', 'bacterial_infectious_disease').
field_of_work('richard_ffrench_constant', 'bacteria').
field_of_work('richard_ffrench_constant', 'biology').
field_of_work('fredric_j__harris', 'digital_signal_processing').
field_of_work('fredric_j__harris', 'software_defined_radio').
field_of_work('fredric_j__harris', 'communication_system').
field_of_work('fredric_j__harris', 'electrical_engineering').
field_of_work('fredric_j__harris', 'signal_processing').
field_of_work('sj_miller', 'educational_equity').
field_of_work('katherena_vermette', 'literature').
doctoral_advisor('danah_boyd', 'peter_lyman').
notable_work('danah_boyd', 'q27044712').
notable_work('adrienne_maree_brown', 'pleasure_activism__the_politics_of_feeling_good').
notable_work('bell_hooks', 'we_real_cool__black_men_and_masculinity').
notable_work('bell_hooks', 'bone_black__memories_of_girlhood').
notable_work('bell_hooks', 'ain_t_i_a_woman_').
notable_work('bell_hooks', 'feminist_theory__from_margin_to_center').
notable_work('bell_hooks', 'all_about_love__new_visions').
native_language('adrienne_maree_brown', 'english').
native_language('fredric_j__harris', 'english').
sexual_orientation('mc_chris', 'bisexuality').
sexual_orientation('maia_arson_crimew', 'lesbianism').
sexual_orientation('maia_arson_crimew', 'bisexuality').
sexual_orientation('barbara_findlay', 'lesbianism').
sexual_orientation('pattrice_jones', 'lesbianism').
sexual_orientation('mxmtoon', 'bisexuality').
discography('mc_chris', 'mc_chris_discography').
discography('dodie', 'dodie_clark_discography').
discography('k_d__lang', 'k_d__lang_discography').
named_after('maia_arson_crimew', 'arson').
named_after('maia_arson_crimew', 'crime').
named_after('maia_arson_crimew', 'meow').
named_after('maia_arson_crimew', 'mxmtoon').
named_after('bambi_effect__slang_', 'bambi').
named_after('cassandra__metaphor_', 'cassandra').
named_after('hobson_s_choice', 'thomas_hobson').
named_after('judgement_of_solomon', 'solomon').
named_after('master_slave__technology_', 'slavery').
named_after('mcnamara_fallacy', 'robert_mcnamara').
named_after('siyokoy__linguistics_', 'siyokoy').
website_account_on('maia_arson_crimew', 'last_fm').
website_account_on('maia_arson_crimew', 'ko_fi').
member_of('maia_arson_crimew', 'young_socialists_switzerland').
member_of('shalan_joudry', 'bear_river_first_nation').
medical_condition('maia_arson_crimew', 'autism').
political_ideology('maia_arson_crimew', 'anarchism').
political_ideology('pattrice_jones', 'ecofeminism').
political_ideology('pattrice_jones', 'intersectionality').
political_ideology('pattrice_jones', 'veganism').
political_ideology('pattrice_jones', 'animal_rights_movement').
artist_files_at('e__e__cummings', 'frick_art_research_library').
artist_files_at('e__e__cummings', 'smithsonian_american_art_and_portrait_gallery_library').
copyright_status_as_a_creator('e__e__cummings', 'works_protected_by_copyrights').
copyright_status_as_a_creator('bpnichol', 'works_protected_by_copyrights').
copyright_status_as_a_creator('will_i_am', 'works_protected_by_copyrights').
writing_language('e__e__cummings', 'english').
writing_language('richard_ffrench_constant', 'english').
documentation_files_at('e__e__cummings', 'sapa_foundation__swiss_archive_of_the_performing_arts').
documentation_files_at('debbie_tucker_green', 'sapa_foundation__swiss_archive_of_the_performing_arts').
manner_of_death('steve_depyssler', 'natural_causes').
manner_of_death('bell_hooks', 'natural_causes').
military_or_police_rank('steve_depyssler', 'colonel').
spouse('arthur_fforde', 'mary_alison_maclehose').
spouse('charles_ffoulkes', 'maud_mary_chester_craven').
spouse('rose_ffrench__1st_baroness_ffrench', 'sir_charles_ffrench__1st_bt_').
spouse('conrad_o_brien_ffrench', 'maud_astrid_tarras_wahlberg').
spouse('conrad_o_brien_ffrench', 'rosalie_isabelle_baker').
spouse('procrustes', 'sylea').
child('arthur_fforde', 'christine_mary_kathleen_fforde').
child('rose_ffrench__1st_baroness_ffrench', 'thomas_hamilton_ffrench__2nd_baron_ffrench_of_castle_ffrench').
child('rose_ffrench__1st_baroness_ffrench', 'catherine_ffrench').
child('rose_ffrench__1st_baroness_ffrench', 'jane_ffrench').
child('conrad_o_brien_ffrench', 'rollo_acheson_o_brien_ffrench').
child('conrad_o_brien_ffrench', 'christina_laetitia_o_brien_ffrench').
child('conrad_o_brien_ffrench', 'john_valentine_o_brien_ffrench').
child('procrustes', 'sinis').
position_held('arthur_fforde', 'chair_of_the_bbc').
position_held('arthur_fforde', 'governor_of_the_bbc').
position_held('michael_ffrench_o_carroll', 'senator_of_ireland').
position_held('michael_ffrench_o_carroll', 'substitute_member_of_the_parliamentary_assembly_of_the_council_of_europe').
position_held('michael_ffrench_o_carroll', 'teachta_d_la').
mother('arthur_fforde', 'mary_alice_storer_branson').
mother('charles_ffoulkes', 'anne_strange').
mother('conrad_o_brien_ffrench', 'winifred_thursby').
honorific_prefix('arthur_fforde', 'sir').
sibling('arthur_fforde', 'kathleen_baxter').
father('arthur_fforde', 'arthur_brownlow_fforde').
father('charles_ffoulkes', 'edmund_ffoulkes').
father('rose_ffrench__1st_baroness_ffrench', 'patrick_dillon').
father('conrad_o_brien_ffrench', 'henry_albert_de_vreque_o_brien_ffrench__1st_marquess_of_castel_thomond').
father('procrustes', 'poseidon').
member_of_political_party('michael_ffrench_o_carroll', 'fianna_f_il').
noble_title('rose_ffrench__1st_baroness_ffrench', 'baron_ffrench').
nominated_for('k_d__lang', 'grammy_award_for_best_pop_collaboration_with_vocals').
nominated_for('k_d__lang', 'grammy_award_for_album_of_the_year').
nominated_for('k_d__lang', 'jack_richardson_producer_of_the_year_award').
nominated_for('k_d__lang', 'grammy_award_for_best_pop_collaboration_with_vocals').
nominated_for('k_d__lang', 'brit_award_for_international_female_solo_artist').
nominated_for('k_d__lang', 'mtv_video_music_award_for_best_cinematography').
nominated_for('k_d__lang', 'juno_award_for_artist_of_the_year').
nominated_for('k_d__lang', 'juno_award_for_entertainer_of_the_year').
nominated_for('k_d__lang', 'grammy_award_for_record_of_the_year').
nominated_for('k_d__lang', 'juno_award_for_entertainer_of_the_year').
nominated_for('k_d__lang', 'grammy_award_for_best_female_pop_vocal_performance').
nominated_for('k_d__lang', 'grammy_award_for_best_female_country_vocal_performance').
nominated_for('k_d__lang', 'grammy_award_for_best_country_collaboration_with_vocals').
nominated_for('k_d__lang', 'juno_award_for_entertainer_of_the_year').
nominated_for('k_d__lang', 'grammy_award_for_best_pop_collaboration_with_vocals').
nominated_for('k_d__lang', 'grammy_award_for_best_female_pop_vocal_performance').
nominated_for('k_d__lang', 'grammy_award_for_best_country_collaboration_with_vocals').
nominated_for('k_d__lang', 'jack_richardson_producer_of_the_year_award').
has_works_in_the_collection('bpnichol', 'tate').
has_works_in_the_collection('will_i_am', 'design_museum_den_bosch').
participated_in_conflict('conrad_o_brien_ffrench', 'world_war_i').
military_branch('conrad_o_brien_ffrench', 'british_army').
ancestral_home('katherena_vermette', 'red_river_colony').
participant_in('will_i_am', 'world_economic_forum_annual_meeting_2020').
participant_in('avery_r__young', 'furious_flower_conference__4th__2024_').
owner_of('will_i_am', 'i_am_').
owner_of('procrustes', 'procrustean_bed').
significant_event('aunt_sally', 'aunt_sally_singles_world_championship').
significant_place('aunt_sally', 'oxfordshire').
symptoms_and_signs('cassandra__metaphor_', 'weight_gain').
symptoms_and_signs('cassandra__metaphor_', 'mental_depression').
symptoms_and_signs('cassandra__metaphor_', 'panic_disorder').
symptoms_and_signs('cassandra__metaphor_', 'weight_loss').
symptoms_and_signs('cassandra__metaphor_', 'migraine').
symptoms_and_signs('cassandra__metaphor_', 'lethargy').
religion_or_worldview('judgement_of_solomon', 'judaism').
religion_or_worldview('judgement_of_solomon', 'christianity').
depicted_by('judgement_of_solomon', 'judgment_of_solomon').
characters('judgement_of_solomon', 'solomon').
copyright_status('o_captain__my_captain_', 'public_domain').
form_of_creative_work('o_captain__my_captain_', 'poem').
published_in('o_captain__my_captain_', 'the_saturday_press').
has_edition_or_translation('o_captain__my_captain_', 'o_captain__my_captain_').
has_edition_or_translation('o_captain__my_captain_', 'o_captain__my_captain_').
has_edition_or_translation('o_captain__my_captain_', 'o_captain__my_captain_').
has_edition_or_translation('o_captain__my_captain_', 'q133364757').
has_edition_or_translation('o_captain__my_captain_', 'q19494087').
has_edition_or_translation('o_captain__my_captain_', 'q133365497').
worshipped_by('procrustes', 'greek_mythology').
enemy('procrustes', 'theseus').
named_by('siyokoy__linguistics_', 'virgilio_s__almario').
category_for_eponymous_categories('person', 'category_wikipedia_categories_named_after_people').
said_to_be_the_same_as('person', 'juridical_person').
said_to_be_the_same_as('person', 'natural_person').
said_to_be_the_same_as('agency__philosophy_', 'volition').
said_to_be_the_same_as('agency__philosophy_', 'activity').
said_to_be_the_same_as('individual', 'q12767484').
said_to_be_the_same_as('individual', 'q12767969').
has_characteristic('person', 'personal_identity').
has_characteristic('person', 'given_name').
has_characteristic('person', 'person_property').
has_characteristic('person', 'adaptive_capacity').
has_characteristic('person', 'personal_life').
has_characteristic('person', 'mental_state').
has_characteristic('person', 'biographic_information').
has_characteristic('person', 'family_name').
has_characteristic('individual', 'individuality').
has_characteristic('individual', 'course_of_life').
has_characteristic('individual', 'goal').
has_characteristic('individual', 'rights').
has_characteristic('individual', 'moral_responsibility').
has_characteristic('individual', 'culpability').
has_characteristic('individual', 'accountability').
has_effect('agency__philosophy_', 'action').
criterion_used('great_ape_personhood', 'sentience').
located_in_the_administrative_territorial_entity('human_rights_in_dubai', 'dubai').
