facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('outline_of_albert_einstein', 'albert_einstein').
facet_of('outline_of_bob_marley', 'bob_marley').
facet_of('bibliography_of_jimmy_carter', 'jimmy_carter').
facet_of('pope_john_paul_ii_bibliography', 'john_paul_ii').
facet_of('bibliography_of_abraham_lincoln', 'abraham_lincoln').
facet_of('bibliography_of_works_on_madonna', 'madonna').
facet_of('hayao_miyazaki_bibliography', 'hayao_miyazaki').
facet_of('bibliography_of_richard_nixon', 'richard_nixon').
facet_of('bibliography_of_harold_pinter', 'harold_pinter').
facet_of('bibliography_of_pope_pius_xii', 'pius_xii').
facet_of('bibliography_of_george_washington', 'george_washington').
facet_of('bibliography_of_orson_welles', 'orson_welles').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('yaroslavich', 'patronymic_family_name').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('yaroslavich', 'patronymic_family_name').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('outline_of_albert_einstein', 'wikimedia_outline_article').
instance_of('outline_of_henry_ford', 'wikimedia_outline_article').
instance_of('outline_of_jesus', 'wikimedia_outline_article').
instance_of('outline_of_gottfried_wilhelm_leibniz', 'wikimedia_outline_article').
instance_of('outline_of_abraham_lincoln', 'wikimedia_outline_article').
instance_of('outline_of_bob_marley', 'wikimedia_outline_article').
instance_of('outline_of_prem_rawat', 'wikimedia_outline_article').
instance_of('outline_of_william_shakespeare', 'wikimedia_outline_article').
instance_of('outline_of_joseph_smith', 'wikimedia_outline_article').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography_of_winston_churchill', 'bibliography').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'written_work').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography_of_george_w__bush', 'wikimedia_list_article').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography_of_hillary_clinton', 'wikimedia_list_article').
instance_of('bibliography_of_leonard_cohen', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography_of_bobby_fischer', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography_of_stephen_harper', 'bibliography').
instance_of('bibliography_of_adolf_hitler', 'wikimedia_list_article').
instance_of('bibliography_of_herbert_hoover', 'public_election').
instance_of('bibliography_of_sam_houston', 'wikimedia_list_article').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography_of_thomas_jefferson', 'personal_bibliography').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography_of_s_ren_kierkegaard', 'wikimedia_list_article').
instance_of('bibliography_of_works_on_stephen_king', 'wikimedia_list_article').
instance_of('bibliography_of_stanis_aw_lem', 'bibliography').
instance_of('bibliography_of_lili_uokalani', 'bibliography').
instance_of('bibliography_of_abraham_lincoln', 'bibliography').
instance_of('bibliography_of_james_madison', 'bibliography').
instance_of('bibliography_of_works_on_madonna', 'bibliography').
instance_of('bibliography_of_william_mckinley', 'bibliography').
instance_of('bibliography_of_works_on_adolfas_mekas', 'bibliography').
instance_of('hayao_miyazaki_bibliography', 'bibliography').
instance_of('bibliography_of_james_monroe', 'public_election').
instance_of('bibliography_of_abul_hasan_ali_hasani_nadwi', 'book').
instance_of('bibliography_of_napoleon', 'bibliography').
instance_of('bibliography_of_richard_nixon', 'bibliography').
instance_of('bibliography_of_shibli_nomani', 'book').
instance_of('bibliography_of_barack_obama', 'wikimedia_list_article').
instance_of('bibliography_of_louis_joseph_papineau', 'bibliography').
instance_of('bibliography_of_harold_pinter', 'bibliography').
instance_of('bibliography_of_pope_pius_xii', 'bibliography').
instance_of('bibliography_of_ramakrishna', 'bibliography').
instance_of('bibliography_of_ayn_rand_and_objectivism', 'bibliography').
instance_of('bibliography_of_ronald_reagan', 'bibliography').
instance_of('bibliography_of_jacques_rivette', 'bibliography').
instance_of('bibliography_of_jane_roberts', 'bibliography').
instance_of('bibliography_of_eleanor_roosevelt', 'bibliography').
instance_of('bibliography_of_eleanor_roosevelt', 'wikimedia_list_article').
instance_of('bibliography_of_franklin_d__roosevelt', 'bibliography').
instance_of('bibliography_of_theodore_roosevelt', 'bibliography').
instance_of('bibliography_of_works_on_shakira', 'bibliography').
instance_of('the_works_of_m__p__shiel', 'literary_work').
instance_of('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'literary_work').
instance_of('bibliography_of_william_howard_taft', 'bibliography').
instance_of('bibliography_of_margaret_thatcher', 'bibliography').
instance_of('bibliography_of_justin_trudeau', 'bibliography').
instance_of('bibliography_of_harry_s__truman', 'bibliography').
instance_of('bibliography_of_donald_trump', 'personal_bibliography').
instance_of('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'bibliography').
instance_of('bibliography_of_martin_van_buren', 'bibliography').
instance_of('bibliography_of_swami_vivekananda', 'bibliography').
instance_of('bibliography_of_george_washington', 'bibliography').
instance_of('bibliography_of_orson_welles', 'bibliography').
instance_of('bibliography_of_woodrow_wilson', 'bibliography').
instance_of('bibliography_of_zakariyya_kandhlawi', 'human').
instance_of('autobiografiction', 'genre').
instance_of('autobiography', 'literary_genre').
instance_of('autobiography', 'book_form').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('outline_of_prem_rawat', 'category_prem_rawat').
category_related_to_list('bibliography_of_adolf_hitler', 'category_books_about_adolf_hitler').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
occupation('outline_of_william_shakespeare', 'writer').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('bibliography_of_james_monroe', 'united_states').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('habib_bourguiba_bibliography', 'habib_bourguiba').
main_subject('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'bibliography').
main_subject('bibliography_of_abdul_majid_daryabadi', 'abdul_majid_daryabadi').
main_subject('bibliography_of_haile_selassie', 'haile_selassie_i').
main_subject('bibliography_of_stephen_harper', 'stephen_harper').
main_subject('bibliography_of_thomas_jefferson', 'thomas_jefferson').
main_subject('bibliography_of_john_f__kennedy', 'john_f__kennedy').
main_subject('bibliography_of_stanis_aw_lem', 'stanislav_lem').
main_subject('bibliography_of_richard_nixon', 'richard_nixon').
main_subject('bibliography_of_jacques_rivette', 'jacques_rivette').
main_subject('the_works_of_m__p__shiel', 'm__p__shiel').
main_subject('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'clark_ashton_smith').
main_subject('bibliography_of_margaret_thatcher', 'margaret_thatcher').
main_subject('bibliography_of_justin_trudeau', 'justin_trudeau').
main_subject('bibliography_of_donald_trump', 'donald_trump').
main_subject('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'first_lady_of_the_united_states').
main_subject('bibliography_of_martin_van_buren', 'martin_van_buren').
main_subject('bibliography_of_swami_vivekananda', 'swami_vivekananda').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_george_w__bush', 'book').
is_a_list_of('bibliography_of_hillary_clinton', 'book').
is_a_list_of('bibliography_of_leonard_cohen', 'book').
is_a_list_of('bibliography_of_bobby_fischer', 'book').
is_a_list_of('bibliography_of_adolf_hitler', 'book').
is_a_list_of('bibliography_of_sam_houston', 'work').
is_a_list_of('bibliography_of_s_ren_kierkegaard', 'work').
is_a_list_of('bibliography_of_works_on_stephen_king', 'book').
is_a_list_of('bibliography_of_barack_obama', 'book').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('bibliography_of_jimmy_carter', 'category_books_by_jimmy_carter').
topic_s_main_category('autobiography', 'category_autobiographies').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'united_states').
country_of_origin('bibliography_of_jimmy_carter', 'united_states').
country_of_origin('the_works_of_m__p__shiel', 'united_states').
country_of_origin('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'united_states').
country_of_origin('bibliography_of_donald_trump', 'united_states').
sport('bibliography_of_bobby_fischer', 'chess').
sport('bibliography_of_bobby_fischer', 'chess').
sport('bibliography_of_bobby_fischer', 'chess').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'english').
language_of_work_or_name('iowa_authors_and_their_works', 'english').
language_of_work_or_name('the_works_of_m__p__shiel', 'english').
language_of_work_or_name('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'english').
author('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'henry_hardy_heins').
author('the_works_of_m__p__shiel', 'albert_reynolds_morse').
author('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'donald_sidney_fryer').
author('bibliography_of_donald_trump', 'donald_trump').
genre('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'bibliography').
genre('the_works_of_m__p__shiel', 'bibliography').
genre('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'bibliography').
publisher('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'donald_m__grant__publisher').
publisher('bibliography_of_stephen_harper', 'english_wikipedia').
publisher('the_works_of_m__p__shiel', 'fantasy_publishing_company__inc_').
publisher('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'donald_m__grant__publisher').
publisher('bibliography_of_justin_trudeau', 'english_wikipedia').
cover_art_by('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'j__allen_st__john').
cover_art_by('the_works_of_m__p__shiel', 'salvador_dal_').
cover_art_by('emperor_of_dreams__a_clark_ashton_smith_bibliography', 'ned_dameron').
sex_or_gender('bibliography_of_zakariyya_kandhlawi', 'male').
described_by_source('biography', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('biography', 'gujin_tushu_jicheng').
described_by_source('biography', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('biography', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('autobiography', 'small_brockhaus_and_efron_encyclopedic_dictionary').
different_from('biography', 'biographical_article').
different_from('biography', 'biography').
different_from('biography', 'vita').
different_from('biography', 'biographer').
different_from('autobiography', 'personal_history').
different_from('autobiography', 'memoir').
studied_by('biography', 'biographistics').
has_part_s_('autobiografiction', 'fiction').
has_part_s_('autobiografiction', 'autobiography').
partially_coincident_with('autobiografiction', 'autofiction').
opposite_of('autobiography', 'heterobiography').
subclass_of('biographical_criticism', 'literary_studies').
subclass_of('biographical_criticism', 'literary_criticism').
