topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('high_tech', 'q9841082').
topic_s_main_category('microtechnology', 'category_microtechnology').
topic_s_main_category('geomatics', 'category_geomatics').
topic_s_main_category('science_and_technology_studies', 'category_science_and_technology_studies').
topic_s_main_category('technology_and_society', 'category_technology_in_society').
topic_s_main_category('agricultural_technology', 'category_agricultural_technology').
topic_s_main_category('alt_tech', 'category_alt_tech').
topic_s_main_category('anti_nuclear_movement_in_germany', 'category_anti_nuclear_movement_in_germany').
topic_s_main_category('anti_nuclear_protests', 'category_anti_nuclear_protests').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('high_tech', 'q9841082').
topic_s_main_category('microtechnology', 'category_microtechnology').
topic_s_main_category('geomatics', 'category_geomatics').
topic_s_main_category('science_and_technology_studies', 'category_science_and_technology_studies').
topic_s_main_category('technology_and_society', 'category_technology_in_society').
topic_s_main_category('agricultural_technology', 'category_agricultural_technology').
topic_s_main_category('alt_tech', 'category_alt_tech').
topic_s_main_category('anti_nuclear_movement_in_germany', 'category_anti_nuclear_movement_in_germany').
topic_s_main_category('anti_nuclear_protests', 'category_anti_nuclear_protests').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('high_tech', 'q9841082').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('high_tech', 'q9841082').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('ancient_egyptian_technology', 'category_ancient_egyptian_technology').
topic_s_main_category('ancient_greek_technology', 'category_ancient_greek_technology').
topic_s_main_category('medieval_technology', 'category_technology_in_the_middle_ages').
topic_s_main_category('prehistoric_technology', 'category_prehistoric_technology').
topic_s_main_category('outline_of_prehistoric_technology', 'category_primitive_technology').
topic_s_main_category('high_tech', 'q9841082').
topic_s_main_category('microtechnology', 'category_microtechnology').
topic_s_main_category('geomatics', 'category_geomatics').
topic_s_main_category('science_and_technology_studies', 'category_science_and_technology_studies').
topic_s_main_category('technology_and_society', 'category_technology_in_society').
topic_s_main_category('agricultural_technology', 'category_agricultural_technology').
topic_s_main_category('alt_tech', 'category_alt_tech').
topic_s_main_category('anti_nuclear_movement_in_germany', 'category_anti_nuclear_movement_in_germany').
topic_s_main_category('anti_nuclear_protests', 'category_anti_nuclear_protests').
topic_s_main_category('criticism_of_technology', 'q19891055').
topic_s_main_category('crowdfunding', 'category_crowdfunding').
topic_s_main_category('cyber_dissident', 'category_cyber_dissidents').
topic_s_main_category('digital_journalism', 'category_online_journalism').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('enabling_technology', 'technology').
subclass_of('high_tech', 'technology').
subclass_of('industrial_technology', 'technology').
subclass_of('low_technology', 'technology').
subclass_of('marine_technology', 'technology').
subclass_of('microtechnology', 'technology').
subclass_of('open_source_appropriate_technology', 'appropriate_technology').
subclass_of('open_source_appropriate_technology', 'open_source_technology').
subclass_of('subsea_technology', 'technology').
subclass_of('geographic_information_science', 'information_science').
subclass_of('geographic_information_science', 'geoinformation_science').
subclass_of('geomatics', 'spatial_science').
subclass_of('geomatics', 'computer_science').
subclass_of('sociotechnology', 'sociology').
subclass_of('active_seti', 'message').
subclass_of('agricultural_technology', 'technology').
subclass_of('agricultural_technology', 'agricultural_science').
subclass_of('anti_nuclear_movement_in_australia', 'anti_nuclear_movement').
subclass_of('anti_nuclear_movement_in_germany', 'anti_nuclear_movement').
subclass_of('anti_nuclear_protests', 'protest').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('enabling_technology', 'technology').
subclass_of('high_tech', 'technology').
subclass_of('industrial_technology', 'technology').
subclass_of('low_technology', 'technology').
subclass_of('marine_technology', 'technology').
subclass_of('microtechnology', 'technology').
subclass_of('open_source_appropriate_technology', 'appropriate_technology').
subclass_of('open_source_appropriate_technology', 'open_source_technology').
subclass_of('subsea_technology', 'technology').
subclass_of('geographic_information_science', 'information_science').
subclass_of('geographic_information_science', 'geoinformation_science').
subclass_of('geomatics', 'spatial_science').
subclass_of('geomatics', 'computer_science').
subclass_of('sociotechnology', 'sociology').
subclass_of('active_seti', 'message').
subclass_of('agricultural_technology', 'technology').
subclass_of('agricultural_technology', 'agricultural_science').
subclass_of('anti_nuclear_movement_in_australia', 'anti_nuclear_movement').
subclass_of('anti_nuclear_movement_in_germany', 'anti_nuclear_movement').
subclass_of('anti_nuclear_protests', 'protest').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('enabling_technology', 'technology').
subclass_of('high_tech', 'technology').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('enabling_technology', 'technology').
subclass_of('high_tech', 'technology').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('enabling_technology', 'technology').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('inca_technology', 'technology').
subclass_of('medieval_technology', 'technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('alternative_technology', 'technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('architectural_technology', 'technology').
subclass_of('architectural_technology', 'architecture').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('enabling_technology', 'technology').
subclass_of('high_tech', 'technology').
subclass_of('industrial_technology', 'technology').
subclass_of('low_technology', 'technology').
subclass_of('marine_technology', 'technology').
subclass_of('microtechnology', 'technology').
subclass_of('open_source_appropriate_technology', 'appropriate_technology').
subclass_of('open_source_appropriate_technology', 'open_source_technology').
subclass_of('subsea_technology', 'technology').
subclass_of('geographic_information_science', 'information_science').
subclass_of('geographic_information_science', 'geoinformation_science').
subclass_of('geomatics', 'spatial_science').
subclass_of('geomatics', 'computer_science').
subclass_of('sociotechnology', 'sociology').
subclass_of('active_seti', 'message').
subclass_of('agricultural_technology', 'agricultural_science').
subclass_of('agricultural_technology', 'technology').
subclass_of('anti_nuclear_movement_in_australia', 'anti_nuclear_movement').
subclass_of('anti_nuclear_movement_in_germany', 'anti_nuclear_movement').
subclass_of('anti_nuclear_protests', 'protest').
subclass_of('civic_application', 'application').
subclass_of('communication_with_extraterrestrial_intelligence', 'communication').
subclass_of('cosmic_call', 'active_seti').
subclass_of('crisis_camp', 'barcamp').
subclass_of('crowdfunding', 'sharing_economy').
subclass_of('crowdfunding', 'capital_procurement').
subclass_of('crowdfunding', 'funding').
subclass_of('crowdfunding', 'crowdsourcing').
subclass_of('crowdfunding', 'ai').
subclass_of('cultural_lag', 'social_phenomenon').
subclass_of('cyber_dissident', 'activist').
subclass_of('de_mail', 'message_traffic').
subclass_of('digital_anthropology', 'anthropology').
subclass_of('digital_journalism', 'web_writing').
subclass_of('digital_journalism', 'journalism').
subclass_of('education_by_algorithm', 'education').
subclass_of('education_by_algorithm', 'educational_activity').
subclass_of('education_by_algorithm', 'outsourcing').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
culture('ancient_greek_technology', 'ancient_greece').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('creative_technology', 'academic_discipline').
instance_of('high_tech', 'type_of_technology').
instance_of('industrial_technology', 'type_of_technology').
instance_of('low_technology', 'type_of_technology').
instance_of('microtechnology', 'type_of_technology').
instance_of('open_source_appropriate_technology', 'type_of_technology').
instance_of('subsea_technology', 'industry').
instance_of('geographic_information_science', 'academic_discipline').
instance_of('geographic_information_science', 'field_of_study').
instance_of('geographic_information_science', 'field_of_study').
instance_of('geographic_information_science', 'academic_major').
instance_of('geomatics', 'academic_discipline').
instance_of('outline_of_manufacturing', 'wikimedia_outline_article').
instance_of('outline_of_mining', 'wikimedia_outline_article').
instance_of('outline_of_production', 'wikimedia_outline_article').
instance_of('outline_of_rocketry', 'wikimedia_outline_article').
instance_of('outline_of_space_exploration', 'wikimedia_outline_article').
instance_of('science_and_technology_studies', 'academic_discipline').
instance_of('sociotechnology', 'academic_discipline').
instance_of('sociotechnology', 'branch_of_sociology').
instance_of('across_the_universe__message_', 'musical_work_composition').
instance_of('age_of_artificial_intelligence', 'historical_period').
instance_of('age_of_artificial_intelligence', 'hypothesis').
instance_of('agricultural_technology', 'academic_discipline').
instance_of('agricultural_technology', 'field_of_study').
instance_of('agricultural_technology', 'field_of_study').
instance_of('agricultural_technology', 'type_of_technology').
instance_of('ai_boom', 'historical_period').
instance_of('alt_tech', 'group').
instance_of('anti_nuclear_movement_in_australia', 'aspect_in_a_geographic_region').
instance_of('arecibo_message', 'active_seti').
instance_of('arecibo_message', 'project').
instance_of('big_tech', 'acronym').
instance_of('big_tech', 'nickname').
instance_of('big_tech', 'group').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('creative_technology', 'academic_discipline').
instance_of('high_tech', 'type_of_technology').
instance_of('industrial_technology', 'type_of_technology').
instance_of('low_technology', 'type_of_technology').
instance_of('microtechnology', 'type_of_technology').
instance_of('open_source_appropriate_technology', 'type_of_technology').
instance_of('subsea_technology', 'industry').
instance_of('geographic_information_science', 'academic_discipline').
instance_of('geographic_information_science', 'field_of_study').
instance_of('geographic_information_science', 'field_of_study').
instance_of('geographic_information_science', 'academic_major').
instance_of('geomatics', 'academic_discipline').
instance_of('outline_of_manufacturing', 'wikimedia_outline_article').
instance_of('outline_of_mining', 'wikimedia_outline_article').
instance_of('outline_of_production', 'wikimedia_outline_article').
instance_of('outline_of_rocketry', 'wikimedia_outline_article').
instance_of('outline_of_space_exploration', 'wikimedia_outline_article').
instance_of('science_and_technology_studies', 'academic_discipline').
instance_of('sociotechnology', 'academic_discipline').
instance_of('sociotechnology', 'branch_of_sociology').
instance_of('across_the_universe__message_', 'musical_work_composition').
instance_of('age_of_artificial_intelligence', 'historical_period').
instance_of('age_of_artificial_intelligence', 'hypothesis').
instance_of('agricultural_technology', 'academic_discipline').
instance_of('agricultural_technology', 'field_of_study').
instance_of('agricultural_technology', 'field_of_study').
instance_of('agricultural_technology', 'type_of_technology').
instance_of('ai_boom', 'historical_period').
instance_of('alt_tech', 'group').
instance_of('anti_nuclear_movement_in_australia', 'aspect_in_a_geographic_region').
instance_of('arecibo_message', 'active_seti').
instance_of('arecibo_message', 'project').
instance_of('big_tech', 'acronym').
instance_of('big_tech', 'nickname').
instance_of('big_tech', 'group').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('creative_technology', 'academic_discipline').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('creative_technology', 'academic_discipline').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('creative_technology', 'academic_discipline').
instance_of('high_tech', 'type_of_technology').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('creative_technology', 'academic_discipline').
instance_of('high_tech', 'type_of_technology').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('creative_technology', 'academic_discipline').
instance_of('inca_technology', 'aspect_of_history').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('outline_of_prehistoric_technology', 'wikimedia_outline_article').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('animal_technology', 'field_of_study').
instance_of('architectural_technology', 'academic_discipline').
instance_of('architectural_technology', 'type_of_technology').
instance_of('creative_technology', 'academic_discipline').
instance_of('entertainment_technology', 'field_of_study').
instance_of('entertainment_technology', 'academic_major').
instance_of('entertainment_technology', 'academic_discipline').
instance_of('high_tech', 'type_of_technology').
instance_of('industrial_technology', 'type_of_technology').
instance_of('low_technology', 'type_of_technology').
instance_of('microtechnology', 'type_of_technology').
instance_of('open_source_appropriate_technology', 'type_of_technology').
instance_of('subsea_technology', 'industry').
instance_of('nick_bilton', 'human').
instance_of('christopher_fabian', 'human').
instance_of('yannik_heinze', 'human').
instance_of('ellis_horowitz', 'human').
instance_of('boon_thau_loo', 'human').
instance_of('mac_the_knife', 'multiple_use_name').
instance_of('mac_the_knife', 'magazine').
instance_of('mac_the_knife', 'house_name').
instance_of('clement_ogaja', 'human').
instance_of('charles_l__perkins', 'human').
instance_of('jason_pontin', 'human').
instance_of('sheizaf_rafaeli', 'human').
instance_of('sartaj_sahni', 'human').
instance_of('bright_simons', 'human').
instance_of('jason_cranford_teague', 'human').
instance_of('clive_thompson__journalist_', 'human').
instance_of('peter_wayner', 'human').
instance_of('nick_zhang', 'human').
instance_of('geographic_information_science', 'academic_discipline').
instance_of('geographic_information_science', 'field_of_study').
instance_of('geographic_information_science', 'field_of_study').
instance_of('geographic_information_science', 'academic_major').
instance_of('geomatics', 'academic_discipline').
instance_of('outline_of_technology', 'wikimedia_outline_article').
instance_of('electrical_polarity', 'quality').
instance_of('outline_of_manufacturing', 'wikimedia_outline_article').
instance_of('outline_of_mining', 'wikimedia_outline_article').
instance_of('outline_of_production', 'wikimedia_outline_article').
instance_of('outline_of_rocketry', 'wikimedia_outline_article').
instance_of('outline_of_space_exploration', 'wikimedia_outline_article').
instance_of('science_and_technology_studies', 'academic_discipline').
instance_of('sociotechnology', 'academic_discipline').
instance_of('sociotechnology', 'branch_of_sociology').
instance_of('technology_and_society', 'research_topic').
instance_of('across_the_universe__message_', 'musical_work_composition').
instance_of('age_of_artificial_intelligence', 'hypothesis').
instance_of('age_of_artificial_intelligence', 'historical_period').
instance_of('agricultural_technology', 'academic_discipline').
instance_of('agricultural_technology', 'type_of_technology').
instance_of('agricultural_technology', 'field_of_study').
instance_of('agricultural_technology', 'field_of_study').
instance_of('ai_boom', 'historical_period').
instance_of('alt_tech', 'group').
instance_of('anti_nuclear_movement_in_australia', 'aspect_in_a_geographic_region').
instance_of('arecibo_message', 'active_seti').
instance_of('arecibo_message', 'project').
instance_of('asian_news_international_vs__wikimedia_foundation', 'lawsuit').
instance_of('big_tech', 'acronym').
instance_of('big_tech', 'nickname').
instance_of('big_tech', 'group').
instance_of('brigade_media', 'dot_com_company').
instance_of('change_org', 'website').
instance_of('change_org', 'organization').
instance_of('coding_it_forward', 'nonprofit_organization').
instance_of('the_cool_stuff_collective', 'television_series').
instance_of('cosmic_call', 'project').
instance_of('critical_code_studies', 'branch_of_science').
instance_of('criticism_of_technology', 'political_ideology').
instance_of('crowdfunding', 'ai').
instance_of('current__financial_services_company_', 'company').
instance_of('cute_cat_theory_of_digital_activism', 'theory').
instance_of('dead_internet_theory', 'conspiracy_theory').
instance_of('dead_internet_theory', 'fringe_theory').
instance_of('digital_anthropology', 'field_of_study').
instance_of('digital_anthropology', 'academic_discipline').
instance_of('digital_anthropology', 'field_of_work').
instance_of('digital_anthropology', 'branch_of_anthropology').
instance_of('digital_anthropology', 'field_of_study').
instance_of('digital_journalism', 'academic_major').
instance_of('digital_journalism', 'journalism_genre').
instance_of('digital_journalism', 'job_activity').
instance_of('education_by_algorithm', 'economic_concept').
country('inca_technology', 'inca_empire').
country('anti_nuclear_movement_in_australia', 'australia').
country('anti_nuclear_movement_in_germany', 'germany').
country('arecibo_message', 'puerto_rico').
country('inca_technology', 'inca_empire').
country('anti_nuclear_movement_in_australia', 'australia').
country('anti_nuclear_movement_in_germany', 'germany').
country('arecibo_message', 'puerto_rico').
country('inca_technology', 'inca_empire').
country('inca_technology', 'inca_empire').
country('inca_technology', 'inca_empire').
country('inca_technology', 'inca_empire').
country('inca_technology', 'inca_empire').
country('inca_technology', 'inca_empire').
country('anti_nuclear_movement_in_australia', 'australia').
country('anti_nuclear_movement_in_germany', 'germany').
country('arecibo_message', 'puerto_rico').
country('asian_news_international_vs__wikimedia_foundation', 'india').
country('change_org', 'united_states').
country('de_mail', 'germany').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
time_period('medieval_technology', 'middle_ages').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('microtechnology', 'template_microtechnology').
topic_s_main_template('science_and_technology_studies', 'template_science_and_technology_studies').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('microtechnology', 'template_microtechnology').
topic_s_main_template('science_and_technology_studies', 'template_science_and_technology_studies').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('prehistoric_technology', 'template_prehistoric_technology').
topic_s_main_template('microtechnology', 'template_microtechnology').
topic_s_main_template('science_and_technology_studies', 'template_science_and_technology_studies').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('disruptive_innovation', 'strategic_management').
facet_of('enabling_technology', 'strategic_planning').
facet_of('agricultural_technology', 'agricultural_technology').
facet_of('ai_boom', 'artificial_intelligence').
facet_of('anti_nuclear_protests', 'anti_nuclear_movement').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('disruptive_innovation', 'strategic_management').
facet_of('enabling_technology', 'strategic_planning').
facet_of('agricultural_technology', 'agricultural_technology').
facet_of('ai_boom', 'artificial_intelligence').
facet_of('anti_nuclear_protests', 'anti_nuclear_movement').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('disruptive_innovation', 'strategic_management').
facet_of('enabling_technology', 'strategic_planning').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('disruptive_innovation', 'strategic_management').
facet_of('enabling_technology', 'strategic_planning').
facet_of('disruptive_innovation', 'strategic_management').
facet_of('enabling_technology', 'strategic_planning').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('disruptive_innovation', 'strategic_management').
facet_of('enabling_technology', 'strategic_planning').
facet_of('outline_of_technology', 'technology').
facet_of('agricultural_technology', 'agricultural_technology').
facet_of('ai_boom', 'artificial_intelligence').
facet_of('anti_nuclear_protests', 'anti_nuclear_movement').
facet_of('digital_media_use_and_mental_health', 'digital_media').
facet_of('digital_media_use_and_mental_health', 'mental_health').
practiced_by('animal_technology', 'animal_technician').
practiced_by('geographic_information_science', 'geographic_information_scientist').
practiced_by('geomatics', 'geomatician').
practiced_by('science_and_technology_studies', 'science_and_technology_studies_scholar').
practiced_by('agricultural_technology', 'agricultural_technologist').
practiced_by('animal_technology', 'animal_technician').
practiced_by('geographic_information_science', 'geographic_information_scientist').
practiced_by('geomatics', 'geomatician').
practiced_by('science_and_technology_studies', 'science_and_technology_studies_scholar').
practiced_by('agricultural_technology', 'agricultural_technologist').
practiced_by('animal_technology', 'animal_technician').
practiced_by('animal_technology', 'animal_technician').
practiced_by('animal_technology', 'animal_technician').
practiced_by('animal_technology', 'animal_technician').
practiced_by('animal_technology', 'animal_technician').
practiced_by('geographic_information_science', 'geographic_information_scientist').
practiced_by('geomatics', 'geomatician').
practiced_by('science_and_technology_studies', 'science_and_technology_studies_scholar').
practiced_by('agricultural_technology', 'agricultural_technologist').
practiced_by('digital_journalism', 'digital_journalist').
used_by('architectural_technology', 'architecture').
used_by('architectural_technology', 'architecture').
used_by('architectural_technology', 'architecture').
used_by('architectural_technology', 'architecture').
used_by('architectural_technology', 'architecture').
used_by('architectural_technology', 'architecture').
used_by('architectural_technology', 'architecture').
discoverer_or_inventor('disruptive_innovation', 'clayton_christensen').
discoverer_or_inventor('disruptive_innovation', 'clayton_christensen').
discoverer_or_inventor('disruptive_innovation', 'clayton_christensen').
discoverer_or_inventor('disruptive_innovation', 'clayton_christensen').
discoverer_or_inventor('disruptive_innovation', 'clayton_christensen').
discoverer_or_inventor('disruptive_innovation', 'clayton_christensen').
partially_coincident_with('disruptive_innovation', 'creative_disruption').
partially_coincident_with('geographic_information_science', 'geoinformation_science').
partially_coincident_with('disruptive_innovation', 'creative_disruption').
partially_coincident_with('geographic_information_science', 'geoinformation_science').
partially_coincident_with('disruptive_innovation', 'creative_disruption').
partially_coincident_with('disruptive_innovation', 'creative_disruption').
partially_coincident_with('disruptive_innovation', 'creative_disruption').
partially_coincident_with('disruptive_innovation', 'creative_disruption').
partially_coincident_with('geographic_information_science', 'geoinformation_science').
partially_coincident_with('criticism_of_technology', 'mechanophobia').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruptive_innovation', 'disruption').
opposite_of('high_tech', 'low_technology').
opposite_of('low_technology', 'high_tech').
opposite_of('active_seti', 'passive_seti').
opposite_of('ai_boom', 'ai_winter').
opposite_of('alt_tech', 'big_tech').
opposite_of('big_tech', 'alt_tech').
opposite_of('high_tech', 'low_technology').
opposite_of('low_technology', 'high_tech').
opposite_of('active_seti', 'passive_seti').
opposite_of('ai_boom', 'ai_winter').
opposite_of('alt_tech', 'big_tech').
opposite_of('big_tech', 'alt_tech').
opposite_of('high_tech', 'low_technology').
opposite_of('high_tech', 'low_technology').
opposite_of('high_tech', 'low_technology').
opposite_of('low_technology', 'high_tech').
opposite_of('active_seti', 'passive_seti').
opposite_of('ai_boom', 'ai_winter').
opposite_of('alt_tech', 'big_tech').
opposite_of('big_tech', 'alt_tech').
said_to_be_the_same_as('industrial_technology', 'manufacturing_engineering').
said_to_be_the_same_as('agricultural_technology', 'agricultural_technology').
said_to_be_the_same_as('big_tech', 'big_tech__web_').
said_to_be_the_same_as('industrial_technology', 'manufacturing_engineering').
said_to_be_the_same_as('agricultural_technology', 'agricultural_technology').
said_to_be_the_same_as('big_tech', 'big_tech__web_').
said_to_be_the_same_as('industrial_technology', 'manufacturing_engineering').
said_to_be_the_same_as('agricultural_technology', 'agricultural_technology').
said_to_be_the_same_as('big_tech', 'big_tech__web_').
said_to_be_the_same_as('crowdfunding', 'threshold_pledge_system').
said_to_be_the_same_as('digital_journalism', 'blogging').
different_from('low_technology', 'do_it_yourself').
different_from('geographic_information_science', 'geographic_information_system').
different_from('geomatics', 'geoinformatics').
different_from('geomatics', 'geomatics_engineering').
different_from('technology_and_society', 'interdisciplinarity').
different_from('active_seti', 'meti_international').
different_from('low_technology', 'do_it_yourself').
different_from('geographic_information_science', 'geographic_information_system').
different_from('geomatics', 'geoinformatics').
different_from('geomatics', 'geomatics_engineering').
different_from('technology_and_society', 'interdisciplinarity').
different_from('active_seti', 'meti_international').
different_from('low_technology', 'do_it_yourself').
different_from('geographic_information_science', 'geographic_information_system').
different_from('geomatics', 'geomatics_engineering').
different_from('geomatics', 'geoinformatics').
different_from('technology_and_society', 'interdisciplinarity').
different_from('active_seti', 'meti_international').
different_from('crowdfunding', 'collaborative_finance').
different_from('dead_internet_theory', 'dead_internet_theory').
part_of('marine_technology', 'seamanship').
part_of('sociotechnology', 'technology_assessment').
part_of('marine_technology', 'seamanship').
part_of('sociotechnology', 'technology_assessment').
part_of('marine_technology', 'seamanship').
part_of('sociotechnology', 'technology_assessment').
part_of('asian_news_international_vs__wikimedia_foundation', 'list_of_litigation_involving_the_wikimedia_foundation').
part_of('crowdfunding', 'sharing_economy').
named_after('geomatics', 'geomatic').
named_after('geomatics', 'geodesy').
named_after('geomatics', 'geoinformatics').
named_after('ai_boom', 'artificial_intelligence').
named_after('arecibo_message', 'arecibo_radio_telescope').
named_after('geomatics', 'geomatic').
named_after('geomatics', 'geodesy').
named_after('geomatics', 'geoinformatics').
named_after('ai_boom', 'artificial_intelligence').
named_after('arecibo_message', 'arecibo_radio_telescope').
named_after('geomatics', 'geoinformatics').
named_after('geomatics', 'geomatic').
named_after('geomatics', 'geodesy').
named_after('ai_boom', 'artificial_intelligence').
named_after('arecibo_message', 'arecibo_radio_telescope').
has_part_s__of_the_class('geomatics', 'surveying').
has_part_s__of_the_class('geomatics', 'geoinformatics').
has_part_s__of_the_class('geomatics', 'surveying').
has_part_s__of_the_class('geomatics', 'geoinformatics').
has_part_s__of_the_class('geomatics', 'geoinformatics').
has_part_s__of_the_class('geomatics', 'surveying').
has_part_s__of_the_class('big_tech', 'technology_company').
replaced_by('geomatics', 'spatial_science').
replaced_by('big_tech', 'magnificent_seven').
replaced_by('geomatics', 'spatial_science').
replaced_by('big_tech', 'magnificent_seven').
replaced_by('geomatics', 'spatial_science').
replaced_by('big_tech', 'magnificent_seven').
has_part_s_('geomatics', 'study_of_geomatics').
has_part_s_('alt_tech', 'telegram').
has_part_s_('big_tech', 'microsoft').
has_part_s_('big_tech', 'google').
has_part_s_('big_tech', 'big_tech__web_').
has_part_s_('big_tech', 'amazon').
has_part_s_('big_tech', 'meta_platforms').
has_part_s_('big_tech', 'apple').
has_part_s_('big_tech', 'x').
has_part_s_('big_tech', 'tiktok').
has_part_s_('big_tech', 'snapchat').
has_part_s_('big_tech', 'discord').
has_part_s_('big_tech', 'alphabet_inc_').
has_part_s_('big_tech', 'facebook').
has_part_s_('geomatics', 'study_of_geomatics').
has_part_s_('alt_tech', 'telegram').
has_part_s_('big_tech', 'microsoft').
has_part_s_('big_tech', 'google').
has_part_s_('big_tech', 'big_tech__web_').
has_part_s_('big_tech', 'amazon').
has_part_s_('big_tech', 'meta_platforms').
has_part_s_('big_tech', 'apple').
has_part_s_('big_tech', 'x').
has_part_s_('big_tech', 'tiktok').
has_part_s_('big_tech', 'snapchat').
has_part_s_('big_tech', 'discord').
has_part_s_('big_tech', 'alphabet_inc_').
has_part_s_('big_tech', 'facebook').
has_part_s_('geomatics', 'study_of_geomatics').
has_part_s_('alt_tech', 'telegram').
has_part_s_('big_tech', 'microsoft').
has_part_s_('big_tech', 'google').
has_part_s_('big_tech', 'big_tech__web_').
has_part_s_('big_tech', 'amazon').
has_part_s_('big_tech', 'snapchat').
has_part_s_('big_tech', 'discord').
has_part_s_('big_tech', 'meta_platforms').
has_part_s_('big_tech', 'x').
has_part_s_('big_tech', 'tiktok').
has_part_s_('big_tech', 'apple').
has_part_s_('big_tech', 'alphabet_inc_').
has_part_s_('big_tech', 'facebook').
is_the_study_of('science_and_technology_studies', 'science_and_technology').
is_the_study_of('sociotechnology', 'technology').
is_the_study_of('science_and_technology_studies', 'science_and_technology').
is_the_study_of('sociotechnology', 'technology').
is_the_study_of('science_and_technology_studies', 'science_and_technology').
is_the_study_of('sociotechnology', 'technology').
form_of_creative_work('across_the_universe__message_', 'song').
form_of_creative_work('across_the_universe__message_', 'song').
form_of_creative_work('across_the_universe__message_', 'song').
performer('across_the_universe__message_', 'the_beatles').
performer('across_the_universe__message_', 'the_beatles').
performer('across_the_universe__message_', 'the_beatles').
follows('age_of_artificial_intelligence', 'digital_revolution').
follows('age_of_artificial_intelligence', 'digital_revolution').
follows('age_of_artificial_intelligence', 'digital_revolution').
uses('agricultural_technology', 'agricultural_science').
uses('agricultural_technology', 'agronomy').
uses('agricultural_technology', 'agricultural_science').
uses('agricultural_technology', 'agronomy').
uses('agricultural_technology', 'agricultural_science').
uses('agricultural_technology', 'agronomy').
uses('cosmic_call', 'evpatoria_observatory').
location('anti_nuclear_movement_in_australia', 'australia').
location('arecibo_message', 'messier_13').
location('arecibo_message', 'arecibo_radio_telescope').
location('anti_nuclear_movement_in_australia', 'australia').
location('arecibo_message', 'messier_13').
location('arecibo_message', 'arecibo_radio_telescope').
location('anti_nuclear_movement_in_australia', 'australia').
location('arecibo_message', 'arecibo_radio_telescope').
location('arecibo_message', 'messier_13').
in_opposition_to('anti_nuclear_protests', 'nuclear_technology').
in_opposition_to('anti_nuclear_protests', 'nuclear_technology').
in_opposition_to('anti_nuclear_protests', 'nuclear_technology').
has_use('arecibo_message', 'communication_with_extraterrestrial_intelligence').
has_use('arecibo_message', 'communication_with_extraterrestrial_intelligence').
has_use('arecibo_message', 'communication_with_extraterrestrial_intelligence').
height('arecibo_message', '73').
height('arecibo_message', '73').
height('arecibo_message', '73').
width('arecibo_message', '23').
width('arecibo_message', '23').
width('arecibo_message', '23').
creator('arecibo_message', 'frank_drake').
creator('arecibo_message', 'carl_sagan').
creator('arecibo_message', 'frank_drake').
creator('arecibo_message', 'carl_sagan').
creator('arecibo_message', 'frank_drake').
creator('arecibo_message', 'carl_sagan').
located_in_the_administrative_territorial_entity('arecibo_message', 'arecibo').
located_in_the_administrative_territorial_entity('arecibo_message', 'arecibo').
located_in_the_administrative_territorial_entity('arecibo_message', 'arecibo').
occupation('nick_bilton', 'journalist').
occupation('nick_bilton', 'writer').
occupation('nick_bilton', 'film_director').
occupation('nick_bilton', 'film_screenwriter').
occupation('nick_bilton', 'film_producer').
occupation('nick_bilton', 'television_producer').
occupation('christopher_fabian', 'engineer').
occupation('yannik_heinze', 'business_executive').
occupation('ellis_horowitz', 'computer_scientist').
occupation('boon_thau_loo', 'writer').
occupation('clement_ogaja', 'surveyor').
occupation('charles_l__perkins', 'engineer').
occupation('jason_pontin', 'journalist').
occupation('jason_pontin', 'venture_capitalist').
occupation('sheizaf_rafaeli', 'computer_scientist').
occupation('sheizaf_rafaeli', 'researcher').
occupation('sheizaf_rafaeli', 'columnist').
occupation('sheizaf_rafaeli', 'journalist').
occupation('sartaj_sahni', 'computer_scientist').
occupation('sartaj_sahni', 'engineer').
occupation('bright_simons', 'engineer').
occupation('bright_simons', 'writer').
occupation('jason_cranford_teague', 'engineer').
occupation('clive_thompson__journalist_', 'journalist').
occupation('clive_thompson__journalist_', 'writer').
occupation('clive_thompson__journalist_', 'blogger').
occupation('peter_wayner', 'writer').
occupation('nick_zhang', 'businessperson').
occupation('nick_zhang', 'computer_scientist').
occupation('nick_zhang', 'artificial_intelligence_researcher').
occupation('nick_zhang', 'writer').
field_of_work('nick_bilton', 'literary_activity').
field_of_work('nick_bilton', 'journalism').
field_of_work('ellis_horowitz', 'data_structure').
field_of_work('sheizaf_rafaeli', 'virtual_learning_environment').
field_of_work('clive_thompson__journalist_', 'literature').
field_of_work('clive_thompson__journalist_', 'journalism').
educated_at('nick_bilton', 'marjory_stoneman_douglas_high_school').
educated_at('christopher_fabian', 'trinity_college_dublin').
educated_at('christopher_fabian', 'the_american_university_in_cairo').
educated_at('ellis_horowitz', 'brooklyn_college').
educated_at('ellis_horowitz', 'james_madison_high_school').
educated_at('ellis_horowitz', 'university_of_wisconsin_madison').
educated_at('boon_thau_loo', 'university_of_california__berkeley').
educated_at('boon_thau_loo', 'stanford_university').
educated_at('clement_ogaja', 'university_of_new_south_wales').
educated_at('clement_ogaja', 'university_of_nairobi').
educated_at('jason_pontin', 'keble_college').
educated_at('jason_pontin', 'harrow_school').
educated_at('sheizaf_rafaeli', 'stanford_university').
educated_at('sheizaf_rafaeli', 'ohio_state_university').
educated_at('sheizaf_rafaeli', 'university_of_haifa').
educated_at('sartaj_sahni', 'cornell_university').
educated_at('sartaj_sahni', 'indian_institute_of_technology_kanpur').
educated_at('bright_simons', 'presbyterian_boys__senior_high_school').
educated_at('clive_thompson__journalist_', 'university_of_toronto').
educated_at('nick_zhang', 'university_of_massachusetts_amherst').
country_of_citizenship('nick_bilton', 'united_states').
country_of_citizenship('christopher_fabian', 'united_states').
country_of_citizenship('ellis_horowitz', 'united_states').
country_of_citizenship('jason_pontin', 'united_states').
country_of_citizenship('sheizaf_rafaeli', 'israel').
country_of_citizenship('sartaj_sahni', 'united_states').
country_of_citizenship('bright_simons', 'ghana').
country_of_citizenship('clive_thompson__journalist_', 'canada').
sex_or_gender('nick_bilton', 'male').
sex_or_gender('christopher_fabian', 'male').
sex_or_gender('yannik_heinze', 'male').
sex_or_gender('ellis_horowitz', 'male').
sex_or_gender('boon_thau_loo', 'male').
sex_or_gender('clement_ogaja', 'male').
sex_or_gender('charles_l__perkins', 'male').
sex_or_gender('jason_pontin', 'male').
sex_or_gender('sheizaf_rafaeli', 'male').
sex_or_gender('bright_simons', 'male').
sex_or_gender('jason_cranford_teague', 'male').
sex_or_gender('clive_thompson__journalist_', 'male').
sex_or_gender('peter_wayner', 'male').
sex_or_gender('nick_zhang', 'male').
place_of_birth('nick_bilton', 'darlington').
place_of_birth('christopher_fabian', 'new_york_city').
place_of_birth('ellis_horowitz', 'new_york_city').
place_of_birth('boon_thau_loo', 'singapore').
place_of_birth('clement_ogaja', 'kenya').
place_of_birth('jason_pontin', 'london').
place_of_birth('sheizaf_rafaeli', 'israel').
place_of_birth('sartaj_sahni', 'pune').
place_of_birth('clive_thompson__journalist_', 'canada').
languages_spoken__written_or_signed('nick_bilton', 'english').
languages_spoken__written_or_signed('sheizaf_rafaeli', 'hebrew').
languages_spoken__written_or_signed('clive_thompson__journalist_', 'english').
residence('nick_bilton', 'los_angeles').
residence('ellis_horowitz', 'pacific_palisades').
residence('jason_pontin', 'boston').
social_media_followers('nick_bilton', '255716').
social_media_followers('nick_bilton', '250175').
social_media_followers('nick_bilton', '245162').
social_media_followers('christopher_fabian', '10651').
social_media_followers('christopher_fabian', '10974').
social_media_followers('christopher_fabian', '10094').
social_media_followers('jason_pontin', '28358').
social_media_followers('jason_pontin', '27937').
social_media_followers('jason_pontin', '28605').
social_media_followers('jason_pontin', '28985').
social_media_followers('clive_thompson__journalist_', '41450').
social_media_followers('clive_thompson__journalist_', '15106').
social_media_followers('clive_thompson__journalist_', '38907').
social_media_followers('clive_thompson__journalist_', '39400').
social_media_followers('clive_thompson__journalist_', '42067').
social_media_followers('clive_thompson__journalist_', '14931').
social_media_followers('clive_thompson__journalist_', '15047').
social_media_followers('change_org', '1606140').
social_media_followers('change_org', '1606032').
social_media_followers('coding_it_forward', '2627').
social_media_followers('coding_it_forward', '10205').
social_media_followers('coding_it_forward', '14607').
social_media_followers('coding_it_forward', '6429').
work_location('nick_bilton', 'san_francisco').
work_location('sheizaf_rafaeli', 'jerusalem').
work_location('sheizaf_rafaeli', 'haifa').
family_name('nick_bilton', 'bilton').
family_name('christopher_fabian', 'fabian').
family_name('ellis_horowitz', 'horowitz').
family_name('charles_l__perkins', 'perkins').
family_name('jason_pontin', 'pontin').
family_name('bright_simons', 'simons').
family_name('clive_thompson__journalist_', 'thompson').
family_name('nick_zhang', 'zhang').
given_name('nick_bilton', 'nick').
given_name('christopher_fabian', 'christopher').
given_name('ellis_horowitz', 'ellis').
given_name('clement_ogaja', 'clement').
given_name('charles_l__perkins', 'charles').
given_name('jason_pontin', 'jason').
given_name('jason_cranford_teague', 'jason').
given_name('clive_thompson__journalist_', 'clive').
given_name('peter_wayner', 'peter').
given_name('nick_zhang', 'nick').
employer('christopher_fabian', 'unicef').
employer('ellis_horowitz', 'university_of_southern_california').
employer('boon_thau_loo', 'university_of_pennsylvania').
employer('clement_ogaja', 'california_state_university__fresno').
employer('clement_ogaja', 'geoscience_australia').
employer('clement_ogaja', 'national_oceanic_and_atmospheric_administration').
employer('jason_pontin', 'mit_technology_review').
employer('sheizaf_rafaeli', 'university_of_haifa').
employer('sheizaf_rafaeli', 'shenkar_college_of_engineering_and_design').
employer('sheizaf_rafaeli', 'university_of_michigan').
employer('sartaj_sahni', 'university_of_minnesota').
employer('sartaj_sahni', 'university_of_florida').
doctoral_advisor('ellis_horowitz', 'george_e__collins').
doctoral_advisor('sartaj_sahni', 'ellis_horowitz').
doctoral_student('ellis_horowitz', 'sartaj_sahni').
doctoral_student('sartaj_sahni', 'srijit_kamath').
doctoral_student('sartaj_sahni', 'jin_woon_woo').
doctoral_student('sartaj_sahni', 'seonghun_cho').
doctoral_student('sartaj_sahni', 'venkat_narayan_thanvantri').
doctoral_student('sartaj_sahni', 'edward_yu_cheuk_cheng').
doctoral_student('sartaj_sahni', 'kam_hoi_cheng').
doctoral_student('sartaj_sahni', 'youngju_won').
doctoral_student('sartaj_sahni', 'keumog_lim_ahn').
doctoral_student('sartaj_sahni', 'sanjay_ranka').
doctoral_student('sartaj_sahni', 'wencheng_lu').
doctoral_student('sartaj_sahni', 'madhusudan_nigam').
doctoral_student('sartaj_sahni', 'doowon_paik').
doctoral_student('sartaj_sahni', 'kun_suk_kim').
doctoral_student('sartaj_sahni', 'james_patrick_cohoon').
doctoral_student('sartaj_sahni', 'patrick_leo_jarvis').
doctoral_student('sartaj_sahni', 'wing_ning_li').
doctoral_student('sartaj_sahni', 'haibin_lu').
doctoral_student('sartaj_sahni', 'teofilo_f__gonzalez').
doctoral_student('sartaj_sahni', 'meongchul_song').
doctoral_student('sartaj_sahni', 'dinesh_prakash_mehta').
doctoral_student('sartaj_sahni', 'surendra_nahar').
doctoral_student('sartaj_sahni', 'rajiv_dattatrava_kane').
doctoral_student('sartaj_sahni', 'jayaram_bhasker').
doctoral_student('sartaj_sahni', 'san_yuan_wu').
doctoral_student('sartaj_sahni', 'andrew_leong_chye_lim').
doctoral_student('sartaj_sahni', 'joonseok_park').
doctoral_student('sartaj_sahni', 'chih_fang_wang').
doctoral_student('sartaj_sahni', 'mario_alberto_lopez').
doctoral_student('sartaj_sahni', 'eliezer_dekel').
doctoral_student('sartaj_sahni', 'jing_fu_jenq').
doctoral_student('sartaj_sahni', 'jong_chang_lee').
doctoral_student('sartaj_sahni', 'ten_hwang_lai').
doctoral_student('sartaj_sahni', 'david_nassimi').
genre('mac_the_knife', 'computer_magazine').
genre('dead_internet_theory', 'social_criticism').
genre('dead_internet_theory', 'computational_sociology').
has_written_for('jason_pontin', 'wired').
has_written_for('jason_pontin', 'the_new_york_times').
has_written_for('clive_thompson__journalist_', 'slate').
spouse('sheizaf_rafaeli', 'anat_rafaeli').
spouse('clive_thompson__journalist_', 'emily_nussbaum').
father('sheizaf_rafaeli', 'eliezer_rafaeli').
sibling('sheizaf_rafaeli', 'eshkol_rafaeli').
award_received('sartaj_sahni', 'ieee_fellow').
award_received('sartaj_sahni', 'fellow_of_the_american_association_for_the_advancement_of_science').
award_received('change_org', 'bigbrotherawards').
participant_in('bright_simons', 'world_economic_forum_annual_meeting_2013').
described_by_source('jason_cranford_teague', 'ob_lky_knih').
described_by_source('crowdfunding', 'open_science_thesaurus').
defendant('asian_news_international_vs__wikimedia_foundation', 'wikimedia_foundation').
court('asian_news_international_vs__wikimedia_foundation', 'delhi_high_court').
plaintiff('asian_news_international_vs__wikimedia_foundation', 'ani_media_private_limited').
founded_by('brigade_media', 'matt_mahan').
founded_by('change_org', 'ben_rattray').
headquarters_location('change_org', 'flatiron_building').
legal_form('change_org', 'eingetragener_verein').
country_of_origin('the_cool_stuff_collective', 'united_kingdom').
number_of_seasons('the_cool_stuff_collective', '3').
cast_member('the_cool_stuff_collective', 'sy_thomas').
number_of_episodes('the_cool_stuff_collective', '39').
original_broadcaster('the_cool_stuff_collective', 'itv').
intended_public('cosmic_call', 'extraterrestrial_intelligence').
has_spin_off('crisis_camp', 'random_hacks_of_kindness').
participant('crowdfunding', 'sponsor').
participant('crowdfunding', 'project').
based_on('de_mail', 'email').
main_regulatory_text('de_mail', 'q1179431').
movement('dead_internet_theory', 'pseudophilosophy').
movement('dead_internet_theory', 'pseudoskepticism').
movement('dead_internet_theory', 'pseudohistory').
movement('dead_internet_theory', 'popular_belief').
published_in('dead_internet_theory', '_x_').
main_subject('dead_internet_theory', 'world_wide_web').
main_subject('dead_internet_theory', 'artificial_intelligence').
main_subject('dead_internet_theory', 'disinformation').
