instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('aesthetics', 'branch_of_philosophy').
instance_of('aesthetics', 'field_of_study').
instance_of('aesthetics', 'field_of_study').
instance_of('area_studies', 'academic_discipline').
instance_of('art_history', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('literary_nonsense', 'literary_genre').
instance_of('media_studies', 'academic_major').
instance_of('media_studies', 'academic_discipline').
instance_of('national_postdoctoral_association', 'regulatory_college').
instance_of('national_postdoctoral_association', '501_c__3__organization').
instance_of('national_postdoctoral_association', 'professional_association').
instance_of('parergon', 'philosophical_concept').
instance_of('public_humanities', 'academic_discipline').
instance_of('romance_studies', 'academic_discipline').
instance_of('romance_studies', 'particular_linguistics').
instance_of('satire', 'art_genre').
instance_of('spatial_turn', 'paradigm_shift').
instance_of('tragedy', 'theatrical_genre').
instance_of('tragicomedy', 'theatrical_genre').
instance_of('tragicomedy', 'literary_genre').
instance_of('accelerationism', 'philosophical_movement').
instance_of('accelerationism', 'political_theory').
instance_of('accelerationism', 'political_strategy').
instance_of('after_capitalism', 'written_work').
instance_of('agents_of_social_change', 'organization').
instance_of('bertelsmann_transformation_index', 'index_number').
instance_of('castigat_ridendo_mores', 'latin_phrase').
instance_of('common_impact', 'nonprofit_organization').
instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('aesthetics', 'branch_of_philosophy').
instance_of('aesthetics', 'field_of_study').
instance_of('aesthetics', 'field_of_study').
instance_of('area_studies', 'academic_discipline').
instance_of('art_history', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('literary_nonsense', 'literary_genre').
instance_of('media_studies', 'academic_major').
instance_of('media_studies', 'academic_discipline').
instance_of('national_postdoctoral_association', 'regulatory_college').
instance_of('national_postdoctoral_association', '501_c__3__organization').
instance_of('national_postdoctoral_association', 'professional_association').
instance_of('parergon', 'philosophical_concept').
instance_of('public_humanities', 'academic_discipline').
instance_of('romance_studies', 'academic_discipline').
instance_of('romance_studies', 'particular_linguistics').
instance_of('satire', 'art_genre').
instance_of('spatial_turn', 'paradigm_shift').
instance_of('tragedy', 'theatrical_genre').
instance_of('tragicomedy', 'theatrical_genre').
instance_of('tragicomedy', 'literary_genre').
instance_of('accelerationism', 'philosophical_movement').
instance_of('accelerationism', 'political_theory').
instance_of('accelerationism', 'political_strategy').
instance_of('after_capitalism', 'written_work').
instance_of('agents_of_social_change', 'organization').
instance_of('bertelsmann_transformation_index', 'index_number').
instance_of('castigat_ridendo_mores', 'latin_phrase').
instance_of('common_impact', 'nonprofit_organization').
instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('aesthetics', 'branch_of_philosophy').
instance_of('aesthetics', 'field_of_study').
instance_of('aesthetics', 'field_of_study').
instance_of('area_studies', 'academic_discipline').
instance_of('art_history', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('aesthetics', 'branch_of_philosophy').
instance_of('aesthetics', 'field_of_study').
instance_of('aesthetics', 'field_of_study').
instance_of('area_studies', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('aesthetics', 'branch_of_philosophy').
instance_of('aesthetics', 'field_of_study').
instance_of('aesthetics', 'field_of_study').
instance_of('area_studies', 'academic_discipline').
instance_of('art_history', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('aesthetics', 'branch_of_philosophy').
instance_of('aesthetics', 'field_of_study').
instance_of('aesthetics', 'field_of_study').
instance_of('area_studies', 'academic_discipline').
instance_of('art_history', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('wahkohtowin', 'canadian_indigenous_law').
instance_of('humanities', 'academic_discipline').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'field_of_study').
instance_of('humanities', 'class').
instance_of('humanities', 'academic_major').
instance_of('humanities_indicators', 'organization').
instance_of('outline_of_the_humanities', 'wikimedia_outline_article').
instance_of('area_studies', 'academic_discipline').
instance_of('art_history', 'academic_discipline').
instance_of('the_arts', 'academic_discipline').
instance_of('the_arts', 'economic_sector').
instance_of('change_and_continuity', 'dichotomy').
instance_of('chorography', 'literary_genre').
instance_of('classics', 'academic_major').
instance_of('classics', 'academic_discipline').
instance_of('critical_theory', 'branch_of_sociology').
instance_of('german_studies', 'field_of_study').
instance_of('german_studies', 'academic_discipline').
instance_of('literary_nonsense', 'literary_genre').
instance_of('media_studies', 'academic_major').
instance_of('media_studies', 'academic_discipline').
instance_of('national_postdoctoral_association', 'regulatory_college').
instance_of('national_postdoctoral_association', '501_c__3__organization').
instance_of('national_postdoctoral_association', 'professional_association').
instance_of('parergon', 'philosophical_concept').
instance_of('public_humanities', 'academic_discipline').
instance_of('romance_studies', 'academic_discipline').
instance_of('romance_studies', 'particular_linguistics').
instance_of('satire', 'art_genre').
instance_of('spatial_turn', 'paradigm_shift').
instance_of('tragicomedy', 'theatrical_genre').
instance_of('tragicomedy', 'literary_genre').
instance_of('blasphemy_day', 'event').
instance_of('blasphemy_day', 'day').
instance_of('chester_ronning_centre_for_the_study_of_religion_and_public_life', 'research_center').
instance_of('colloquium_on_violence___religion', 'learned_society').
instance_of('confessionalism__politics_', 'form_of_state').
instance_of('confessionalism__politics_', 'form_of_government').
instance_of('secularity', 'quality').
instance_of('spiritual_left', 'political_ideology').
instance_of('tony_blair_faith_foundation', 'organization').
instance_of('outline_of_society', 'wikimedia_outline_article').
instance_of('outline_of_adoption', 'wikimedia_outline_article').
instance_of('outline_of_agriculture', 'wikimedia_outline_article').
instance_of('outline_of_alchemy', 'wikimedia_outline_article').
instance_of('outline_of_anthropology', 'wikimedia_outline_article').
instance_of('outline_of_bdsm', 'wikimedia_outline_article').
instance_of('outline_of_british_pornography', 'wikimedia_outline_article').
instance_of('outline_of_childhood', 'wikimedia_list_article').
instance_of('outline_of_communication', 'wikimedia_outline_article').
instance_of('outline_of_community', 'wikimedia_outline_article').
instance_of('outline_of_culture', 'wikimedia_outline_article').
instance_of('outline_of_environmental_journalism', 'wikimedia_outline_article').
instance_of('outline_of_environmentalism', 'wikimedia_outline_article').
instance_of('outline_of_firefighting', 'wikimedia_outline_article').
instance_of('outline_of_the_fishing_industry', 'wikimedia_outline_article').
instance_of('outline_of_food_preparation', 'wikimedia_list_article').
instance_of('outline_of_forgery', 'wikimedia_outline_article').
instance_of('outline_of_globalization', 'wikimedia_outline_article').
instance_of('outline_of_green_politics', 'wikimedia_outline_article').
instance_of('outline_of_human_intelligence', 'wikimedia_outline_article').
instance_of('outline_of_human_sexuality', 'wikimedia_outline_article').
instance_of('outline_of_human_sexuality', 'wikimedia_list_article').
instance_of('outline_of_humans', 'wikimedia_outline_article').
instance_of('outline_of_journalism', 'wikimedia_outline_article').
instance_of('outline_of_transgender_topics', 'wikimedia_list_article').
instance_of('outline_of_lgbtq_topics', 'wikimedia_outline_article').
instance_of('outline_of_linguistics', 'wikimedia_outline_article').
instance_of('outline_of_manufacturing', 'wikimedia_outline_article').
instance_of('outline_of_marketing', 'wikimedia_list_article').
instance_of('outline_of_the_metric_system', 'wikimedia_outline_article').
instance_of('outline_of_organic_gardening_and_farming', 'wikimedia_list_article').
instance_of('outline_of_parapsychology', 'wikimedia_outline_article').
instance_of('outline_of_poker', 'wikimedia_outline_article').
culture('wahkohtowin', 'cree').
culture('wahkohtowin', 'cree').
culture('wahkohtowin', 'cree').
culture('wahkohtowin', 'cree').
culture('wahkohtowin', 'cree').
culture('wahkohtowin', 'cree').
culture('wahkohtowin', 'cree').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('humanities', 'social_studies').
partially_coincident_with('humanities', 'geisteswissenschaften').
partially_coincident_with('humanities', 'social_science').
partially_coincident_with('secularity', 'laicity').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('humanities', 'philosophy').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('media_studies', 'newspaper_studies').
has_part_s_('philosophy', 'aesthetics').
has_part_s_('philosophy', 'metaphysics').
has_part_s_('philosophy', 'ontology').
has_part_s_('philosophy', 'philosophy_of_science').
has_part_s_('philosophy', 'moral_philosophy').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('humanities', 'philosophy').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('media_studies', 'newspaper_studies').
has_part_s_('philosophy', 'aesthetics').
has_part_s_('philosophy', 'metaphysics').
has_part_s_('philosophy', 'ontology').
has_part_s_('philosophy', 'philosophy_of_science').
has_part_s_('philosophy', 'moral_philosophy').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('humanities', 'philosophy').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('humanities', 'philosophy').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('humanities', 'philosophy').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('humanities', 'philosophy').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('humanities', 'religious_studies').
has_part_s_('humanities', 'literary_theory').
has_part_s_('humanities', 'linguistics').
has_part_s_('humanities', 'political_philosophy').
has_part_s_('humanities', 'anthropology').
has_part_s_('humanities', 'archaeology').
has_part_s_('the_arts', 'art').
has_part_s_('change_and_continuity', 'change').
has_part_s_('change_and_continuity', 'continuity').
has_part_s_('classics', 'classical_philology').
has_part_s_('media_studies', 'newspaper_studies').
has_part_s_('outline_of_human_sexuality', 'list_of_gender_identities').
has_part_s_('outline_of_human_sexuality', 'list_of_sexual_orientations').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('humanities', 'art').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('art_history', 'work_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('media_studies', 'mass_media').
is_the_study_of('romance_studies', 'romance_languages').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('humanities', 'art').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('art_history', 'work_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('media_studies', 'mass_media').
is_the_study_of('romance_studies', 'romance_languages').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('humanities', 'art').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('art_history', 'work_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('humanities', 'art').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('art_history', 'work_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('humanities', 'art').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('art_history', 'work_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('humanities', 'art').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('art_history', 'work_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('humanities', 'history_of_philosophy').
is_the_study_of('humanities', 'language').
is_the_study_of('humanities', 'literature').
is_the_study_of('humanities', 'history').
is_the_study_of('art_history', 'history_of_art').
is_the_study_of('caucasology', 'languages_of_the_caucasus').
is_the_study_of('caucasology', 'caucasus').
is_the_study_of('classics', 'ancient_greek').
is_the_study_of('classics', 'latin').
is_the_study_of('german_studies', 'german_language_literature').
is_the_study_of('german_studies', 'german').
is_the_study_of('media_studies', 'mass_media').
is_the_study_of('romance_studies', 'romance_languages').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('media_studies', 'media_science').
said_to_be_the_same_as('world_community', 'civilization').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('media_studies', 'media_science').
said_to_be_the_same_as('world_community', 'civilization').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('humanities', 'human_science').
said_to_be_the_same_as('area_studies', 'domestic_studies').
said_to_be_the_same_as('media_studies', 'media_science').
said_to_be_the_same_as('world_community', 'civilization').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('media_studies', 'template_media_studies').
topic_s_main_template('philosophy', 'template_philosophy_topics').
topic_s_main_template('philosophy', 'template_philosophy_sidebar').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('literature', 'template_literature').
topic_s_main_template('media_studies', 'template_media_studies').
topic_s_main_template('philosophy', 'template_philosophy_topics').
topic_s_main_template('philosophy', 'template_philosophy_sidebar').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('humanities', 'template_humanities').
topic_s_main_template('aesthetics', 'template_aesthetics').
topic_s_main_template('critical_theory', 'template_critical_theory').
topic_s_main_template('history', 'template_history_of_science_and_technology_in_the_united_states').
topic_s_main_template('literature', 'template_literature').
topic_s_main_template('media_studies', 'template_media_studies').
topic_s_main_template('outline_of_human_sexuality', 'template_gender_and_sexual_identities').
subclass_of('humanities', 'social_sciences_and_humanities').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('art_history', 'geisteswissenschaften').
subclass_of('the_arts', 'group').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('german_studies', 'germanic_philology').
subclass_of('literary_nonsense', 'humor').
subclass_of('media_studies', 'social_science').
subclass_of('public_humanities', 'humanities').
subclass_of('romance_studies', 'european_studies').
subclass_of('romance_studies', 'modern_philology').
subclass_of('satire', 'humor').
subclass_of('tragedy', 'drama').
subclass_of('tragedy', 'theatre').
subclass_of('tragicomedy', 'tragedy').
subclass_of('tragicomedy', 'comedy').
subclass_of('transparency__behavior_', 'quality').
subclass_of('social_change', 'culture_change').
subclass_of('accelerating_change', 'technological_change').
subclass_of('accelerationism', 'technological_utopianism').
subclass_of('the_arts_and_politics', 'relation').
subclass_of('humanities', 'social_sciences_and_humanities').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('art_history', 'geisteswissenschaften').
subclass_of('the_arts', 'group').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('german_studies', 'germanic_philology').
subclass_of('literary_nonsense', 'humor').
subclass_of('literature', 'class').
subclass_of('media_studies', 'social_science').
subclass_of('public_humanities', 'humanities').
subclass_of('romance_studies', 'european_studies').
subclass_of('romance_studies', 'modern_philology').
subclass_of('satire', 'humor').
subclass_of('tragedy', 'drama').
subclass_of('tragedy', 'theatre').
subclass_of('tragicomedy', 'tragedy').
subclass_of('tragicomedy', 'comedy').
subclass_of('transparency__behavior_', 'quality').
subclass_of('social_change', 'culture_change').
subclass_of('accelerating_change', 'technological_change').
subclass_of('accelerationism', 'technological_utopianism').
subclass_of('the_arts_and_politics', 'relation').
subclass_of('humanities', 'social_sciences_and_humanities').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('art_history', 'geisteswissenschaften').
subclass_of('the_arts', 'intentional_human_activity').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('german_studies', 'germanic_philology').
subclass_of('humanities', 'social_sciences_and_humanities').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('art_history', 'geisteswissenschaften').
subclass_of('the_arts', 'intentional_human_activity').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('german_studies', 'germanic_philology').
subclass_of('humanities', 'social_sciences_and_humanities').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('art_history', 'geisteswissenschaften').
subclass_of('the_arts', 'intentional_human_activity').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('german_studies', 'germanic_philology').
subclass_of('humanities', 'social_sciences_and_humanities').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('art_history', 'geisteswissenschaften').
subclass_of('the_arts', 'intentional_human_activity').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('german_studies', 'germanic_philology').
subclass_of('aesthetics', 'philosophy').
subclass_of('area_studies', 'interdisciplinary_science').
subclass_of('area_studies', 'area__ethnic__cultural__gender__and_group_studies').
subclass_of('area_studies', 'cultural_studies').
subclass_of('art_history', 'humanities').
subclass_of('art_history', 'visual_art_education').
subclass_of('the_arts', 'intentional_human_activity').
subclass_of('the_arts', 'humanities').
subclass_of('caucasology', 'asian_studies').
subclass_of('caucasology', 'european_studies').
subclass_of('caucasology', 'area_studies').
subclass_of('chorography', 'history_book').
subclass_of('chorography', 'cartography').
subclass_of('classics', 'area_studies').
subclass_of('classics', 'classical_studies').
subclass_of('critical_theory', 'sociological_methodology').
subclass_of('critical_theory', 'normative_sociology').
subclass_of('critical_theory', 'marxist_philosophy').
subclass_of('critical_theory', 'critical_social_theory').
subclass_of('critical_theory', 'sociological_theory').
subclass_of('german_studies', 'germanic_philology').
subclass_of('history', 'chain_of_events').
subclass_of('literary_nonsense', 'humor').
subclass_of('literature', 'class').
subclass_of('media_studies', 'social_science').
subclass_of('public_humanities', 'humanities').
subclass_of('romance_studies', 'european_studies').
subclass_of('romance_studies', 'modern_philology').
subclass_of('tragicomedy', 'tragedy').
subclass_of('tragicomedy', 'comedy').
subclass_of('transparency__behavior_', 'quality').
subclass_of('confessionalism__politics_', 'state_system').
subclass_of('faith_community_nursing', 'religious_organization').
subclass_of('faith_community_nursing', 'community_health_nursing').
subclass_of('nudity_in_religion', 'nudity').
subclass_of('religion_and_agriculture', 'relation').
subclass_of('religion_and_agriculture', 'religion_and_society').
subclass_of('religion_in_scouting', 'religion').
subclass_of('religious_exclusivism', 'religious_doctrine').
subclass_of('religious_exemption', 'exemption').
subclass_of('religious_identity', 'identity').
subclass_of('religious_intolerance', 'social_issue').
subclass_of('religious_intolerance', 'bigotry').
subclass_of('religious_offense', 'transgression').
subclass_of('religious_offense', 'hate_crime').
subclass_of('religious_offense', 'religious_crime').
subclass_of('religious_tolerance', 'toleration').
subclass_of('religious_views_on_smoking', 'religious_view').
subclass_of('secularity', 'isolation').
subclass_of('spiritual_left', 'left_wing').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'early_modern_chorographies').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('history', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('parergon', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('philosophy', 'q2041543').
described_by_source('philosophy', 'the_nuttall_encyclop_dia').
described_by_source('philosophy', 'catholic_encyclopedia').
described_by_source('philosophy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('philosophy', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('satire', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('satire', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('satire', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('satire', 'armenian_soviet_encyclopedia').
described_by_source('satire', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('satire', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('tragedy', 'real_nyj_slovar__klassicheskih_drevnostej_po_ljubkeru').
described_by_source('tragedy', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragedy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'early_modern_chorographies').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('history', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('literature', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('literature', 'gujin_tushu_jicheng').
described_by_source('literature', 'q2041543').
described_by_source('literature', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('literature', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('parergon', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('philosophy', 'q2041543').
described_by_source('philosophy', 'the_nuttall_encyclop_dia').
described_by_source('philosophy', 'catholic_encyclopedia').
described_by_source('philosophy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('philosophy', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('satire', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('satire', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('satire', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('satire', 'armenian_soviet_encyclopedia').
described_by_source('satire', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('satire', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('tragedy', 'real_nyj_slovar__klassicheskih_drevnostej_po_ljubkeru').
described_by_source('tragedy', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragedy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'early_modern_chorographies').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'early_modern_chorographies').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'early_modern_chorographies').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('history', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'early_modern_chorographies').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('history', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('aesthetics', 'encyclop_dia_britannica_11th_edition').
described_by_source('aesthetics', 'the_new_student_s_reference_work').
described_by_source('aesthetics', 'the_nuttall_encyclop_dia').
described_by_source('aesthetics', 'desktop_encyclopedic_dictionary').
described_by_source('aesthetics', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('aesthetics', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('aesthetics', 'q2041543').
described_by_source('art_history', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('the_arts', 'armenian_soviet_encyclopedia__vol__2').
described_by_source('the_arts', 'the_domestic_encyclop_dia__or__a_dictionary_of_facts__and_useful_knowledge').
described_by_source('the_arts', 'lean_logic').
described_by_source('the_arts', 'the_nuttall_encyclop_dia').
described_by_source('caucasology', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('chorography', 'encyclop_dia_britannica_11th_edition').
described_by_source('chorography', 'q105726199').
described_by_source('classics', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('critical_theory', 'encyclopedia_of_political_theory').
described_by_source('history', 'granat_encyclopedic_dictionary').
described_by_source('history', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('history', 'encyclop_dia_britannica_11th_edition').
described_by_source('literature', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('literature', 'gujin_tushu_jicheng').
described_by_source('literature', 'q2041543').
described_by_source('literature', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('literature', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('parergon', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('satire', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('satire', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('satire', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('satire', 'armenian_soviet_encyclopedia').
described_by_source('satire', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('satire', 'encyclop_dia_britannica_11th_edition').
described_by_source('tragedy', 'real_nyj_slovar__klassi_eskih_drevnostej_po_l_bkeru').
described_by_source('tragedy', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragedy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('tragicomedy', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('secularity', 'encyclop_dia_britannica_11th_edition').
part_of('aesthetics', 'axiology').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('literary_nonsense', 'absurdism').
part_of('somatic_theory', 'psychology_terminology').
part_of('social_change', 'political_economy_and_social_change').
part_of('aesthetics', 'axiology').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('literary_nonsense', 'absurdism').
part_of('literature', 'language_arts').
part_of('somatic_theory', 'psychology_terminology').
part_of('social_change', 'political_economy_and_social_change').
part_of('aesthetics', 'axiology').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('aesthetics', 'axiology').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('aesthetics', 'axiology').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('aesthetics', 'axiology').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('aesthetics', 'axiology').
part_of('art_history', 'q113296040').
part_of('the_arts', 'culture').
part_of('classics', 'history').
part_of('classics', 'ancient_literature').
part_of('critical_theory', 'social_conflict_theory').
part_of('critical_theory', 'marxist_sociology').
part_of('critical_theory', 'frankfurt_school').
part_of('literary_nonsense', 'absurdism').
part_of('literature', 'language_arts').
part_of('somatic_theory', 'psychology_terminology').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'category_art_history').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('media_studies', 'category_media_studies').
topic_s_main_category('philosophy', 'category_philosophy').
topic_s_main_category('romance_studies', 'category_romance_studies').
topic_s_main_category('satire', 'category_satire').
topic_s_main_category('tragedy', 'category_tragedy').
topic_s_main_category('tragicomedy', 'category_tragicomedy').
topic_s_main_category('transparency__behavior_', 'category_transparency__behavior_').
topic_s_main_category('social_change', 'category_social_change').
topic_s_main_category('the_arts_and_politics', 'category_the_arts_and_politics').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'category_art_history').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('literature', 'category_literature').
topic_s_main_category('media_studies', 'category_media_studies').
topic_s_main_category('philosophy', 'category_philosophy').
topic_s_main_category('romance_studies', 'category_romance_studies').
topic_s_main_category('satire', 'category_satire').
topic_s_main_category('tragedy', 'category_tragedy').
topic_s_main_category('tragicomedy', 'category_tragicomedy').
topic_s_main_category('transparency__behavior_', 'category_transparency__behavior_').
topic_s_main_category('social_change', 'category_social_change').
topic_s_main_category('the_arts_and_politics', 'category_the_arts_and_politics').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'category_art_history').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'category_art_history').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'category_art_history').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('history', 'category_history').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'category_art_history').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('history', 'category_history').
topic_s_main_category('aesthetics', 'category_aesthetics').
topic_s_main_category('aesthetics', 'category_theories_of_aesthetics').
topic_s_main_category('area_studies', 'category_area_studies').
topic_s_main_category('art_history', 'q9560932').
topic_s_main_category('the_arts', 'category_the_arts').
topic_s_main_category('caucasology', 'category_caucasology').
topic_s_main_category('chorography', 'category_chorographies').
topic_s_main_category('classics', 'category_classical_studies').
topic_s_main_category('critical_theory', 'category_critical_theory').
topic_s_main_category('german_studies', 'category_germanic_philology').
topic_s_main_category('history', 'category_history').
topic_s_main_category('literature', 'category_literature').
topic_s_main_category('media_studies', 'category_media_studies').
topic_s_main_category('romance_studies', 'category_romance_studies').
topic_s_main_category('satire', 'category_satire').
topic_s_main_category('tragicomedy', 'category_tragicomedy').
topic_s_main_category('transparency__behavior_', 'category_transparency__behavior_').
topic_s_main_category('nudity_in_religion', 'category_nudity_in_religion').
topic_s_main_category('religious_identity', 'category_religious_identity').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'art').
different_from('the_arts', 'work_of_art').
different_from('history', 'study_of_history').
different_from('media_studies', 'media_industry_studies').
different_from('media_studies', 'communication_studies').
different_from('romance_studies', 'q99976367').
different_from('satire', 'satir').
different_from('tragedy', 'tragicomedy').
different_from('tragicomedy', 'tragedy').
different_from('tragicomedy', 'comedy').
different_from('tragicomedy', 'comedy').
different_from('tragicomedy', 'comedy_drama').
different_from('agents_of_social_change', 'agents_of_change').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'art').
different_from('the_arts', 'work_of_art').
different_from('history', 'study_of_history').
different_from('media_studies', 'media_industry_studies').
different_from('media_studies', 'communication_studies').
different_from('romance_studies', 'q99976367').
different_from('satire', 'satir').
different_from('tragedy', 'tragicomedy').
different_from('tragicomedy', 'tragedy').
different_from('tragicomedy', 'comedy').
different_from('tragicomedy', 'comedy').
different_from('tragicomedy', 'comedy_drama').
different_from('agents_of_social_change', 'agents_of_change').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'art').
different_from('the_arts', 'work_of_art').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'art').
different_from('the_arts', 'work_of_art').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'art').
different_from('the_arts', 'work_of_art').
different_from('history', 'study_of_history').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'art').
different_from('the_arts', 'work_of_art').
different_from('history', 'study_of_history').
different_from('aesthetics', 'art').
different_from('area_studies', 'regional_science').
different_from('art_history', 'history_of_art').
different_from('art_history', 'art_practice').
different_from('art_history', 'curatorial_studies').
different_from('the_arts', 'art').
different_from('the_arts', 'portal_arts').
different_from('the_arts', 'work_of_art').
different_from('history', 'study_of_history').
different_from('media_studies', 'media_industry_studies').
different_from('media_studies', 'communication_studies').
different_from('romance_studies', 'q99976367').
different_from('satire', 'satir').
different_from('tragedy', 'tragicomedy').
different_from('tragicomedy', 'comedy').
different_from('tragicomedy', 'comedy_drama').
different_from('tragicomedy', 'tragedy').
different_from('tragicomedy', 'comedy').
different_from('secularity', 'atheism').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('media_studies', 'media_scholar').
practiced_by('philosophy', 'philosopher').
practiced_by('philosophy', 'professor_of_philosophy').
practiced_by('romance_studies', 'romanist').
practiced_by('satire', 'satirist').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('media_studies', 'media_scholar').
practiced_by('philosophy', 'philosopher').
practiced_by('philosophy', 'professor_of_philosophy').
practiced_by('romance_studies', 'romanist').
practiced_by('satire', 'satirist').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('area_studies', 'scholar_of_area_studies').
practiced_by('art_history', 'art_historian').
practiced_by('art_history', 'art_history_teacher').
practiced_by('caucasology', 'caucasologist').
practiced_by('classics', 'classical_scholar').
practiced_by('german_studies', 'germanist').
practiced_by('media_studies', 'media_scholar').
practiced_by('romance_studies', 'romanist').
practiced_by('satire', 'satirist').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('media_studies', 'media_history').
history_of_topic('philosophy', 'history_of_philosophy').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('media_studies', 'media_history').
history_of_topic('philosophy', 'history_of_philosophy').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('the_arts', 'history_of_art').
history_of_topic('media_studies', 'media_history').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
discoverer_or_inventor('critical_theory', 'max_horkheimer').
used_by('critical_theory', 'social_conflict_theory').
used_by('critical_theory', 'social_conflict_theory').
used_by('critical_theory', 'social_conflict_theory').
used_by('critical_theory', 'social_conflict_theory').
used_by('critical_theory', 'social_conflict_theory').
used_by('critical_theory', 'social_conflict_theory').
used_by('critical_theory', 'social_conflict_theory').
has_part_s__of_the_class('history', 'oral_tradition').
has_part_s__of_the_class('history', 'oral_tradition').
has_part_s__of_the_class('literature', 'literary_work').
has_part_s__of_the_class('history', 'oral_tradition').
has_part_s__of_the_class('history', 'oral_tradition').
has_part_s__of_the_class('history', 'oral_tradition').
has_part_s__of_the_class('history', 'historical_event').
has_part_s__of_the_class('literature', 'literary_work').
permanent_duplicated_item('history', 'q58237100').
permanent_duplicated_item('history', 'q20829341').
permanent_duplicated_item('philosophy', 'q12960900').
permanent_duplicated_item('history', 'q58237100').
permanent_duplicated_item('history', 'q20829341').
permanent_duplicated_item('literature', 'q27131939').
permanent_duplicated_item('philosophy', 'q12960900').
permanent_duplicated_item('history', 'q58237100').
permanent_duplicated_item('history', 'q20829341').
permanent_duplicated_item('history', 'q58237100').
permanent_duplicated_item('history', 'q20829341').
permanent_duplicated_item('history', 'q58237100').
permanent_duplicated_item('history', 'q20829341').
permanent_duplicated_item('literature', 'q27131939').
facet_of('history', 'past').
facet_of('spatial_turn', 'social_science').
facet_of('spatial_turn', 'cultural_studies').
facet_of('transparency__behavior_', 'openness').
facet_of('history', 'past').
facet_of('spatial_turn', 'social_science').
facet_of('spatial_turn', 'cultural_studies').
facet_of('transparency__behavior_', 'openness').
facet_of('history', 'past').
facet_of('history', 'past').
facet_of('history', 'past').
facet_of('spatial_turn', 'social_science').
facet_of('spatial_turn', 'cultural_studies').
facet_of('transparency__behavior_', 'openness').
facet_of('religion_and_agriculture', 'agriculture').
facet_of('religion_and_agriculture', 'religion').
facet_of('religion_and_peacebuilding', 'religion').
facet_of('religion_and_peacebuilding', 'peace').
facet_of('religious_exemption', 'religious_law').
facet_of('religious_tolerance', 'religion').
facet_of('religious_views_on_smoking', 'smoking').
facet_of('outline_of_food_preparation', 'food_and_drink_preparation').
facet_of('outline_of_food_preparation', 'cooking').
studied_in('history', 'study_of_history').
studied_in('social_change', 'cultural_evolution').
studied_in('social_change', 'sociocultural_evolution').
studied_in('history', 'study_of_history').
studied_in('literature', 'literary_criticism').
studied_in('social_change', 'cultural_evolution').
studied_in('social_change', 'sociocultural_evolution').
country('humanities_in_the_united_states', 'united_states').
country('national_postdoctoral_association', 'united_states').
country('school_of_letters', 'united_states').
country('humanities_in_the_united_states', 'united_states').
country('national_postdoctoral_association', 'united_states').
country('school_of_letters', 'united_states').
country('humanities_in_the_united_states', 'united_states').
country('humanities_in_the_united_states', 'united_states').
country('humanities_in_the_united_states', 'united_states').
country('national_postdoctoral_association', 'united_states').
country('school_of_letters', 'united_states').
country('center_for_the_study_of_religion_and_society', 'united_states').
country('chester_ronning_centre_for_the_study_of_religion_and_public_life', 'canada').
country('faith_and_globalisation_initiative', 'united_states').
social_media_followers('literature', '2009425').
social_media_followers('national_postdoctoral_association', '14986').
social_media_followers('national_postdoctoral_association', '13197').
social_media_followers('national_postdoctoral_association', '16387').
social_media_followers('national_postdoctoral_association', '14986').
social_media_followers('national_postdoctoral_association', '13197').
social_media_followers('national_postdoctoral_association', '16387').
social_media_followers('national_postdoctoral_association', '16387').
social_media_followers('national_postdoctoral_association', '14986').
social_media_followers('national_postdoctoral_association', '13197').
significant_person('media_studies', 'marshall_mcluhan').
significant_person('media_studies', 'marshall_mcluhan').
significant_person('media_studies', 'marshall_mcluhan').
located_in_the_administrative_territorial_entity('national_postdoctoral_association', 'washington__d_c_').
located_in_the_administrative_territorial_entity('national_postdoctoral_association', 'washington__d_c_').
located_in_the_administrative_territorial_entity('national_postdoctoral_association', 'washington__d_c_').
located_in_the_administrative_territorial_entity('chester_ronning_centre_for_the_study_of_religion_and_public_life', 'camrose').
depicted_by('tragedy', 'la_tragedia').
depicted_by('tragedy', 'la_tragedia').
depicted_by('tragedy', 'la_tragedia').
has_use('transparency__behavior_', 'oversight').
has_use('transparency__behavior_', 'accountability').
has_use('transparency__behavior_', 'oversight').
has_use('transparency__behavior_', 'accountability').
has_use('transparency__behavior_', 'accountability').
has_use('transparency__behavior_', 'oversight').
opposite_of('transparency__behavior_', 'secrecy').
opposite_of('transparency__behavior_', 'secrecy').
opposite_of('transparency__behavior_', 'secrecy').
opposite_of('religious_exclusivism', 'religious_liberalism').
opposite_of('religious_exclusivism', 'inclusivism').
opposite_of('secularity', 'affiliation').
has_cause('transparency__behavior_', 'communication').
has_cause('transparency__behavior_', 'accountability').
has_cause('transparency__behavior_', 'communication').
has_cause('transparency__behavior_', 'accountability').
has_cause('transparency__behavior_', 'communication').
has_cause('transparency__behavior_', 'accountability').
has_effect('social_change', 'social_structure').
has_effect('social_change', 'social_structure').
country_of_origin('after_capitalism', 'united_states').
country_of_origin('after_capitalism', 'united_states').
author('after_capitalism', 'dada_maheshvarananda').
author('after_capitalism', 'dada_maheshvarananda').
genre('after_capitalism', 'non_fiction').
genre('after_capitalism', 'non_fiction').
language_of_work_or_name('after_capitalism', 'english').
language_of_work_or_name('after_capitalism', 'english').
has_edition_or_translation('after_capitalism', 'q133248405').
has_edition_or_translation('after_capitalism', 'q133248405').
copyright_holder('bertelsmann_transformation_index', 'bertelsmann_stiftung').
copyright_holder('bertelsmann_transformation_index', 'bertelsmann_stiftung').
headquarters_location('common_impact', 'boston').
headquarters_location('common_impact', 'boston').
total_revenue('common_impact', '3780610').
total_revenue('common_impact', '3225585').
total_revenue('common_impact', '3780610').
total_revenue('common_impact', '3225585').
total_revenue('tony_blair_faith_foundation', '2971000').
total_revenue('tony_blair_faith_foundation', '2621000').
total_revenue('tony_blair_faith_foundation', '4067000').
total_revenue('tony_blair_faith_foundation', '4440000').
total_revenue('tony_blair_faith_foundation', '1618000').
donations('common_impact', '171964').
donations('common_impact', '378284').
donations('common_impact', '171964').
donations('common_impact', '378284').
donations('tony_blair_faith_foundation', '1596000').
donations('tony_blair_faith_foundation', '4059000').
donations('tony_blair_faith_foundation', '4413000').
donations('tony_blair_faith_foundation', '2459000').
donations('tony_blair_faith_foundation', '2965000').
total_assets('common_impact', '4111651').
total_assets('common_impact', '4223654').
total_assets('common_impact', '4111651').
total_assets('common_impact', '4223654').
has_characteristic('literature', 'literary_genre').
has_characteristic('literature', 'mode').
has_characteristic('literature', 'literary_genre').
has_characteristic('literature', 'mode').
studied_by('history', 'study_of_history').
studied_by('history', 'study_of_history').
studied_by('history', 'historiography').
studied_by('history', 'study_of_history').
studied_by('literature', 'literary_criticism').
studied_by('literature', 'sociology_of_literature').
studied_by('religious_offense', 'religious_studies').
union_of('literature', 'list_of_values_as_qualifiers').
day_in_year_for_periodic_occurrence('blasphemy_day', 'september_30').
named_after('chester_ronning_centre_for_the_study_of_religion_and_public_life', 'chester_ronning').
location('chester_ronning_centre_for_the_study_of_religion_and_public_life', 'university_of_alberta_augustana_campus').
owned_by('chester_ronning_centre_for_the_study_of_religion_and_public_life', 'university_of_alberta').
manifestation_of('religious_identity', 'religious_belief').
employees('tony_blair_faith_foundation', '27').
employees('tony_blair_faith_foundation', '30').
employees('tony_blair_faith_foundation', '39').
employees('tony_blair_faith_foundation', '33').
legal_form('tony_blair_faith_foundation', 'foundation').
is_a_list_of('outline_of_food_preparation', 'food_and_drink_preparation').
is_a_list_of('outline_of_human_sexuality', 'gender_identity').
is_a_list_of('outline_of_human_sexuality', 'gender_expression').
is_a_list_of('outline_of_human_sexuality', 'sexual_orientation').
is_a_list_of('outline_of_human_sexuality', 'sexual_identity').
category_related_to_list('outline_of_human_sexuality', 'category_human_gender_and_sexuality').
main_subject('outline_of_lgbtq_topics', 'lgbtq').
