instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('imprisonment', 'punishment').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'need').
instance_of('autobesity', 'condition').
instance_of('condition', 'concept').
instance_of('autobesity', 'condition').
instance_of('condition', 'first_order_class').
instance_of('built_environment', 'field_of_study').
instance_of('field_of_study', 'knowledge_classification').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_crisis', 'public_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_crisis', 'type_of_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('disease', 'class_of_disease').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('disease', 'variable_order_class').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('imprisonment', 'punishment').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'need').
instance_of('autobesity', 'condition').
instance_of('condition', 'concept').
instance_of('autobesity', 'condition').
instance_of('condition', 'first_order_class').
instance_of('built_environment', 'field_of_study').
instance_of('field_of_study', 'knowledge_classification').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_crisis', 'public_health').
instance_of('kvikk_case', 'health_crisis').
instance_of('health_crisis', 'type_of_crisis').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('disease', 'class_of_disease').
instance_of('health_effects_of_pesticides', 'disease').
instance_of('disease', 'variable_order_class').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('imprisonment', 'punishment').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'need').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('imprisonment', 'punishment').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'need').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_joe_biden', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_joe_biden', 'health').
instance_of('health', 'need').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'goods').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_charles_darwin', 'health').
instance_of('health', 'need').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'goods').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_adolf_hitler', 'health').
instance_of('health', 'need').
instance_of('mental_health_of_jesus', 'mental_health').
instance_of('mental_health', 'mental_state').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'goods').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'field_of_study').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'academic_discipline').
instance_of('health_of_pope_john_paul_ii', 'health').
instance_of('health', 'need').
instance_of('asylum_confinement_of_christopher_smart', 'imprisonment').
instance_of('imprisonment', 'punishment').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'type_of_conflict').
instance_of('age_and_health_concerns_about_donald_trump', 'political_conflict').
instance_of('political_conflict', 'political_term').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'goods').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'field_of_study').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'academic_discipline').
instance_of('age_and_health_concerns_about_donald_trump', 'health').
instance_of('health', 'need').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', 'timeline_of_the_presidencies_of_donald_trump').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', '2024_united_states_presidential_election').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', 'timeline_of_the_presidencies_of_donald_trump').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', '2024_united_states_presidential_election').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', 'timeline_of_the_presidencies_of_donald_trump').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', '2024_united_states_presidential_election').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', 'timeline_of_the_presidencies_of_donald_trump').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', '2024_united_states_presidential_election').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_presidential_campaign__2020').
part_of('joe_biden_presidential_campaign__2020', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_joe_biden', 'joe_biden_2024_presidential_campaign').
part_of('joe_biden_2024_presidential_campaign', 'timeline_of_the_joe_biden_presidency').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', 'timeline_of_the_presidencies_of_donald_trump').
part_of('age_and_health_concerns_about_donald_trump', 'donald_trump_2024_presidential_campaign').
part_of('donald_trump_2024_presidential_campaign', '2024_united_states_presidential_election').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
has_effect('age_and_health_concerns_about_joe_biden', 'withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election').
has_effect('withdrawal_of_joe_biden_from_the_2024_united_states_presidential_election', 'kamala_harris_2024_presidential_campaign').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('united_states', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('united_states', 'united_states').
country('effects_of_climate_change_on_health_in_the_united_kingdom', 'united_kingdom').
country('united_kingdom', 'united_kingdom').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_joe_biden', 'united_states').
country('united_states', 'united_states').
country('age_and_health_concerns_about_donald_trump', 'united_states').
country('united_states', 'united_states').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
facet_of('health_effect', 'health_risk').
facet_of('health_risk', 'health').
facet_of('autobesity', 'automotive_industry').
facet_of('automotive_industry', 'transportation_industry').
facet_of('effects_of_overtime', 'overtime').
facet_of('overtime', 'work_life_balance').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
facet_of('health_effect', 'health_risk').
facet_of('health_risk', 'health').
facet_of('autobesity', 'automotive_industry').
facet_of('automotive_industry', 'transportation_industry').
facet_of('effects_of_overtime', 'overtime').
facet_of('overtime', 'work_life_balance').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
facet_of('mental_health_of_jesus', 'psychopathy').
facet_of('psychopathy', 'psychopath').
subclass_of('health_effect', 'effect').
subclass_of('effect', 'phenomenon').
subclass_of('health_effect', 'effect').
subclass_of('effect', 'occurrence').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('mode_of_transport', 'method').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('mode_of_transport', 'type').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('intoxication', 'toxic_injury').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('intoxication', 'disease').
subclass_of('benefits_of_physical_activity', 'health_effects_of_physical_activity').
subclass_of('health_effects_of_physical_activity', 'athletics').
subclass_of('built_environment', 'environment').
subclass_of('environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('human_settlement', 'group_of_structures_or_buildings').
subclass_of('built_environment', 'human_settlement').
subclass_of('human_settlement', 'populated_place').
subclass_of('built_environment', 'human_settlement').
subclass_of('human_settlement', 'geographical_feature').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('intoxication', 'toxic_injury').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('intoxication', 'disease').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('climate_change_in_the_united_kingdom', 'climate_change').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('public_health', 'health_sciences').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('environmental_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('determinants_of_health', 'cause').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('public_health', 'social_science').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('global_health', 'public_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('radiation_damage', 'damage').
subclass_of('electromagnetic_radiation_and_health', 'determinants_of_health').
subclass_of('determinants_of_health', 'cause').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('human_impact_on_the_environment', 'anthropogenic_hazard').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('human_impact_on_the_environment', 'external_risk').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('human_impact_on_the_environment', 'environmental_change').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('environmental_effects', 'environmental_issue').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('environmental_effects', 'phenomenon').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('external_causes_of_illness_and_death', 'external_risk').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('external_causes_of_illness_and_death', 'cause').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('determinants_of_health', 'cause').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('external_causes_of_illness_and_death', 'etiology').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('environmental_impact_of_pesticides', 'environmental_effects').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('intoxication', 'toxic_injury').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('intoxication', 'disease').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('environmental_impact_of_pesticides', 'environmental_impact_of_agriculture').
subclass_of('health_effect', 'effect').
subclass_of('effect', 'phenomenon').
subclass_of('health_effect', 'effect').
subclass_of('effect', 'occurrence').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('mode_of_transport', 'method').
subclass_of('active_mobility', 'mode_of_transport').
subclass_of('mode_of_transport', 'type').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('intoxication', 'toxic_injury').
subclass_of('health_impact_of_asbestos', 'intoxication').
subclass_of('intoxication', 'disease').
subclass_of('built_environment', 'environment').
subclass_of('environment', 'environment').
subclass_of('built_environment', 'human_settlement').
subclass_of('human_settlement', 'group_of_structures_or_buildings').
subclass_of('built_environment', 'human_settlement').
subclass_of('human_settlement', 'populated_place').
subclass_of('built_environment', 'human_settlement').
subclass_of('human_settlement', 'geographical_feature').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('intoxication', 'toxic_injury').
subclass_of('health_effects_of_coal_ash', 'intoxication').
subclass_of('intoxication', 'disease').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'climate_change_in_the_united_kingdom').
subclass_of('climate_change_in_the_united_kingdom', 'climate_change').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change_on_health_in_the_united_kingdom', 'effects_of_climate_change_on_human_health').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('public_health', 'health_sciences').
subclass_of('effects_of_climate_change_on_human_health', 'effects_of_climate_change').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('effects_of_climate_change_on_human_health', 'environmental_health').
subclass_of('environmental_health', 'public_health').
subclass_of('effects_of_climate_change_on_human_health', 'determinants_of_health').
subclass_of('determinants_of_health', 'cause').
subclass_of('effects_of_climate_change_on_human_health', 'public_health').
subclass_of('public_health', 'social_science').
subclass_of('effects_of_climate_change_on_human_health', 'global_health').
subclass_of('global_health', 'public_health').
subclass_of('effects_of_nuclear_explosions_on_human_health', 'radiation_damage').
subclass_of('radiation_damage', 'damage').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('human_impact_on_the_environment', 'anthropogenic_hazard').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('human_impact_on_the_environment', 'external_risk').
subclass_of('effects_of_climate_change', 'human_impact_on_the_environment').
subclass_of('human_impact_on_the_environment', 'environmental_change').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('environmental_effects', 'environmental_issue').
subclass_of('health_and_environmental_impact_of_the_petroleum_industry', 'environmental_effects').
subclass_of('environmental_effects', 'phenomenon').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('external_causes_of_illness_and_death', 'external_risk').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('external_causes_of_illness_and_death', 'cause').
subclass_of('health_effects_from_noise', 'determinants_of_health').
subclass_of('determinants_of_health', 'cause').
subclass_of('health_effects_from_noise', 'external_causes_of_illness_and_death').
subclass_of('external_causes_of_illness_and_death', 'etiology').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('environmental_impact_of_pesticides', 'environmental_effects').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('intoxication', 'toxic_injury').
subclass_of('health_effects_of_pesticides', 'intoxication').
subclass_of('intoxication', 'disease').
subclass_of('health_effects_of_pesticides', 'environmental_impact_of_pesticides').
subclass_of('environmental_impact_of_pesticides', 'environmental_impact_of_agriculture').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('asbestos_exposure', 'asbestos').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('global_warming', 'greenhouse_gas_emissions').
has_cause('health_impact_of_asbestos', 'asbestos_exposure').
has_cause('asbestos_exposure', 'asbestos').
has_cause('effects_of_climate_change', 'global_warming').
has_cause('global_warming', 'greenhouse_gas_emissions').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('radiation_burden', 'exposure_to_radiation').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('wireless_device_radiation_and_health', 'environmental_impact_of_telecommunications').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('wireless_device_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('electromagnetic_radiation_and_health', 'wireless_device_radiation_and_health').
different_from('wireless_device_radiation_and_health', 'mobile_phones_and_cancer').
different_from('electromagnetic_radiation_and_health', 'wireless_electronic_devices_and_health').
different_from('wireless_electronic_devices_and_health', 'wireless_device_radiation_and_health').
different_from('effects_of_nuclear_explosions_on_human_health', 'radiation_burden').
different_from('radiation_burden', 'exposure_to_radiation').
studied_in('health_effects_from_noise', 'audiology').
studied_in('audiology', 'audiology').
studied_in('health_effects_from_noise', 'audiology').
studied_in('audiology', 'audiology').
