http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'basic_research').
http___www_wikidata_org_prop_direct_p279('basic_research', 'research').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'work').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'procedure').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'software').
http___www_wikidata_org_prop_direct_p279('highly_composite_number', 'composite_number').
http___www_wikidata_org_prop_direct_p279('composite_number', 'positive_integer').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'weighted_sum').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'operation_result').
http___www_wikidata_org_prop_direct_p279('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
http___www_wikidata_org_prop_direct_p279('uniform_tiling', 'uniform_tessellation').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'researcher').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'scholar').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'basic_research').
http___www_wikidata_org_prop_direct_p279('basic_research', 'research').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'work').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'procedure').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'software').
http___www_wikidata_org_prop_direct_p279('highly_composite_number', 'composite_number').
http___www_wikidata_org_prop_direct_p279('composite_number', 'positive_integer').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'weighted_sum').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'operation_result').
http___www_wikidata_org_prop_direct_p279('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
http___www_wikidata_org_prop_direct_p279('uniform_tiling', 'uniform_tessellation').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'researcher').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'scholar').
http___www_wikidata_org_prop_direct_p31('pure_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
http___www_wikidata_org_prop_direct_p31('comparison', 'method').
http___www_wikidata_org_prop_direct_p31('table_of_divisors', 'table').
http___www_wikidata_org_prop_direct_p31('table', 'data_visualization').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation_group_according_to_isco_08').
http___www_wikidata_org_prop_direct_p31('occupation_group_according_to_isco_08', 'job_classification_system').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'concept').
http___www_wikidata_org_prop_direct_p31('nicholas_a__m__monk', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('harold_ramkissoon', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('pure_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
http___www_wikidata_org_prop_direct_p31('comparison', 'method').
http___www_wikidata_org_prop_direct_p31('table_of_divisors', 'table').
http___www_wikidata_org_prop_direct_p31('table', 'data_visualization').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation_group_according_to_isco_08').
http___www_wikidata_org_prop_direct_p31('occupation_group_according_to_isco_08', 'job_classification_system').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'concept').
http___www_wikidata_org_prop_direct_p31('nicholas_a__m__monk', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('harold_ramkissoon', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'lisa_willis').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'mae_woods').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'trevor_graham').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'christopher_hornsby').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'lisa_willis').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'mae_woods').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'trevor_graham').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'christopher_hornsby').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'michael_fisher').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'cyril_domb').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'michael_fisher').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'cyril_domb').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'mathematician').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'woman').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'mathematician').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'woman').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'software').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'software').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'software').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('highly_composite_number', 'positive_integer').
subclass_of('positive_integer', 'non_negative_integer').
subclass_of('highly_composite_number', 'positive_integer').
subclass_of('positive_integer', 'positive_real_number').
subclass_of('sums_of_powers', 'sum').
subclass_of('sum', 'weighted_sum').
subclass_of('sums_of_powers', 'sum').
subclass_of('sum', 'operation_result').
subclass_of('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
subclass_of('uniform_tiling', 'uniform_tessellation').
subclass_of('mathematician', 'scientist').
subclass_of('scientist', 'researcher').
subclass_of('mathematician', 'scientist').
subclass_of('scientist', 'scholar').
subclass_of('krieger_nelson_prize', 'award_honoring_women').
subclass_of('award_honoring_women', 'award').
subclass_of('ruth_lyttle_satter_prize_in_mathematics', 'award_honoring_women').
subclass_of('award_honoring_women', 'award').
subclass_of('women_in_stem', 'group_of_humans').
subclass_of('group_of_humans', 'group_of_persons').
subclass_of('women_in_stem', 'group_of_humans').
subclass_of('group_of_humans', 'group_or_class_of_humans').
subclass_of('anamorphosis', 'image').
subclass_of('image', 'artificial_object').
subclass_of('anamorphosis', 'image').
subclass_of('image', 'two_dimensional_object').
subclass_of('anamorphosis', 'projection').
subclass_of('projection', 'visual_artwork').
subclass_of('mathematical_beauty', 'beauty').
subclass_of('beauty', 'convention').
subclass_of('mathematical_beauty', 'beauty').
subclass_of('beauty', 'value').
subclass_of('mathematics_of_paper_folding', 'mathematics').
subclass_of('mathematics', 'natural_science').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('highly_composite_number', 'type_of_integer').
instance_of('type_of_integer', 'second_order_class').
instance_of('karp_s_21_np_complete_problems', 'set').
instance_of('set', 'mathematical_concept').
instance_of('mathematician', 'occupation_group_according_to_isco_08').
instance_of('occupation_group_according_to_isco_08', 'job_classification_system').
instance_of('mathematician', 'occupation').
instance_of('occupation', 'second_order_class').
instance_of('mathematician', 'profession').
instance_of('profession', 'metaclass').
instance_of('mathematician', 'profession').
instance_of('profession', 'second_order_class').
instance_of('mathematician', 'occupation').
instance_of('occupation', 'concept').
instance_of('hideki_omori', 'human').
instance_of('human', 'organisms_known_by_a_particular_common_name').
instance_of('timeline_of_women_in_mathematics_in_the_united_states', 'aspect_in_a_geographic_region').
instance_of('aspect_in_a_geographic_region', 'metaclass').
instance_of('african_women_in_mathematics_association', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('african_women_in_mathematics_association', 'women_s_organization').
instance_of('women_s_organization', 'type_of_organization').
instance_of('anne_bennett_prize', 'mathematics_award').
instance_of('mathematics_award', 'type_of_award').
instance_of('association_for_women_in_mathematics', 'professional_association').
instance_of('professional_association', 'type_of_organization').
instance_of('association_for_women_in_mathematics', 'women_s_organization').
instance_of('women_s_organization', 'type_of_organization').
instance_of('association_for_women_in_mathematics_newsletter', 'scientific_journal').
instance_of('scientific_journal', 'magazine_genre').
instance_of('caucus_for_women_in_statistics_and_data_science', 'regulatory_college').
instance_of('regulatory_college', 'type_of_organization').
instance_of('complexities__women_in_mathematics', 'version__edition_or_translation').
instance_of('version__edition_or_translation', 'item').
instance_of('complexities__women_in_mathematics', 'version__edition_or_translation').
instance_of('version__edition_or_translation', 'second_order_class').
instance_of('european_women_in_mathematics', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('femmes_et_math_matiques', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('graduate_women_in_science', '501_c__3__organization').
instance_of('501_c__3__organization', 'legal_form').
instance_of('graduate_women_in_science', '501_c__3__organization').
instance_of('501_c__3__organization', 'tax_status').
instance_of('graduate_women_in_science', 'women_s_organization').
instance_of('women_s_organization', 'type_of_organization').
instance_of('hidden_figures__book_', 'non_fiction_novel').
instance_of('non_fiction_novel', 'novel_genre').
instance_of('krieger_nelson_prize', 'award').
instance_of('award', 'first_order_class').
instance_of('krieger_nelson_prize', 'science_award').
instance_of('science_award', 'type_of_award').
instance_of('noether_lecture', 'named_lecture').
instance_of('named_lecture', 'convention').
instance_of('noether_lecture', 'named_lecture').
instance_of('named_lecture', 'lecture').
instance_of('noether_lecture', 'mathematics_award').
instance_of('mathematics_award', 'type_of_award').
instance_of('noether_lecture', 'lecture_series').
instance_of('lecture_series', 'type_of_award').
instance_of('pioneering_women_in_american_mathematics', 'written_work').
instance_of('written_work', 'collective_noun').
instance_of('power_in_numbers__the_rebel_women_of_mathematics', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('power_in_numbers__the_rebel_women_of_mathematics', 'book').
instance_of('book', 'type_of_publication').
instance_of('ruth_lyttle_satter_prize_in_mathematics', 'mathematics_award').
instance_of('mathematics_award', 'type_of_award').
instance_of('women_in_mathematics__book_', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('women_in_mathematics__book_', 'book').
instance_of('book', 'type_of_publication').
instance_of('trisatika', 'written_work').
instance_of('written_work', 'collective_noun').
instance_of('mathematics_and_art', 'relation').
instance_of('relation', 'type_of_property').
instance_of('mathematics_and_art', 'relation').
instance_of('relation', 'type_of_object').
instance_of('sarah_marie_belcastro', 'human').
instance_of('human', 'organisms_known_by_a_particular_common_name').
instance_of('the_bridges_organization', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('equals_pi', 'painting').
instance_of('painting', 'type_of_work_of_art').
instance_of('fourth_dimension_in_art', 'art_genre').
instance_of('art_genre', 'metaclass').
instance_of('golden_ratio', 'metallic_ratio').
instance_of('metallic_ratio', 'sequence_of_real_numbers').
instance_of('golden_ratio', 'irrational_number').
instance_of('irrational_number', 'type_of_number').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('periodical', 'type_of_mass_media').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('periodical', 'type_of_publication').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('periodical', 'form_of_creative_work').
instance_of('mathemalchemy', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('a_new_kind_of_science', 'written_work').
instance_of('written_work', 'collective_noun').
sibling('hideki_omori', 'akemi__mori').
sibling('akemi__mori', 'rei__mori').
sibling('hideki_omori', 'rei__mori').
sibling('rei__mori', 'akemi__mori').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('women_in_mathematics', 'mathematician').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('women_in_mathematics', 'woman').
facet_of('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
facet_of('women_in_mathematics', 'mathematician').
facet_of('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
facet_of('women_in_mathematics', 'woman').
facet_of('women_in_stem', 'occupational_segregation').
facet_of('occupational_segregation', 'gender_role').
facet_of('mathematical_beauty', 'mathematics').
facet_of('mathematics', 'mathematics_education').
country('timeline_of_women_in_mathematics_in_the_united_states', 'united_states').
country('united_states', 'united_states').
country('association_for_women_in_mathematics', 'united_states').
country('united_states', 'united_states').
country('center_for_women_in_mathematics', 'united_states').
country('united_states', 'united_states').
country('european_women_in_mathematics', 'finland').
country('finland', 'finland').
country('femmes_et_math_matiques', 'france').
country('france', 'france').
country('graduate_women_in_science', 'united_states').
country('united_states', 'united_states').
country('krieger_nelson_prize', 'canada').
country('canada', 'canada').
country('noether_lecture', 'united_states').
country('united_states', 'united_states').
located_in_the_administrative_territorial_entity('association_for_women_in_mathematics', 'fairfax').
located_in_the_administrative_territorial_entity('fairfax', 'virginia').
located_in_the_administrative_territorial_entity('graduate_women_in_science', 'minneapolis').
located_in_the_administrative_territorial_entity('minneapolis', 'hennepin_county').
member_of('european_women_in_mathematics', 'european_mathematical_society').
member_of('european_mathematical_society', 'european_open_science_cloud_association').
distributed_by('hidden_figures', 'netflix').
distributed_by('netflix', 'app_store').
distributed_by('hidden_figures', 'netflix').
distributed_by('netflix', 'google_play').
distributed_by('hidden_figures', 'itunes').
distributed_by('itunes', 'microsoft_store').
named_after('fermat_kitchen', 'fermat_s_last_theorem').
named_after('fermat_s_last_theorem', 'pierre_de_fermat').
intended_public('fermat_kitchen', 'sh_nen').
intended_public('sh_nen', 'boy').
intended_public('science_fell_in_love__so_i_tried_to_prove_it', 'seinen').
intended_public('seinen', 'teenager').
intended_public('s_gaku_golden', 'seinen').
intended_public('seinen', 'teenager').
intended_public('s_ji_de_asobo', 'josei').
intended_public('josei', 'woman').
doctoral_advisor('sarah_marie_belcastro', 'igor_dolgachev').
doctoral_advisor('igor_dolgachev', 'igor_shafarevich').
different_from('golden_ratio', 'golden_rule').
different_from('golden_rule', 'lei__urea').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'beauty').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'delicacy').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'simplicity').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'parsimony').
