country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('united_states', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('united_states', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('outline_of_joseph_smith', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_hillary_clinton', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_bobby_fischer', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_herbert_hoover', 'united_states').
country('united_states', 'united_states').
country('bibliography_of_james_monroe', 'united_states').
country('united_states', 'united_states').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('book', 'type_of_publication').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('book', 'type_of_publication').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_adams', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_john_quincy_adams', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_gianni_berengo_gardin', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_subhas_chandra_bose', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_winston_churchill', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_winston_churchill', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_winston_churchill', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('habib_bourguiba_bibliography', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('a_golden_anniversary_bibliography_of_edgar_rice_burroughs', 'written_work').
instance_of('written_work', 'collective_noun').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_george_h__w__bush', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_jimmy_carter', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_whittaker_chambers', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_bill_clinton', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_works_on_davy_crockett', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_abdul_majid_daryabadi', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_duwamish__tribe_', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_dwight_d__eisenhower', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_works_on_ulysses_s__grant', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_works_on_che_guevara', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_haile_selassie', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_stephen_harper', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_stephen_harper', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_stephen_harper', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('iowa_authors_and_their_works', 'book').
instance_of('book', 'type_of_publication').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_andrew_jackson', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('pope_john_paul_ii_bibliography', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_andrew_johnson', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_lyndon_b__johnson', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_kal_kaua', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_john_f__kennedy', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_stanis_aw_lem', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_stanis_aw_lem', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_stanis_aw_lem', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_lili_uokalani', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_lili_uokalani', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_lili_uokalani', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_abraham_lincoln', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_abraham_lincoln', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_abraham_lincoln', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_james_madison', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_james_madison', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_madonna', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_works_on_madonna', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_works_on_madonna', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_william_mckinley', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_william_mckinley', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_william_mckinley', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_works_on_adolfas_mekas', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_works_on_adolfas_mekas', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_works_on_adolfas_mekas', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('hayao_miyazaki_bibliography', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('hayao_miyazaki_bibliography', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('hayao_miyazaki_bibliography', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_abul_hasan_ali_hasani_nadwi', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('bibliography_of_abul_hasan_ali_hasani_nadwi', 'book').
instance_of('book', 'type_of_publication').
instance_of('bibliography_of_napoleon', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_napoleon', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_napoleon', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_richard_nixon', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_richard_nixon', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_richard_nixon', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_shibli_nomani', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('bibliography_of_shibli_nomani', 'book').
instance_of('book', 'type_of_publication').
instance_of('bibliography_of_louis_joseph_papineau', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_louis_joseph_papineau', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_louis_joseph_papineau', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_harold_pinter', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_harold_pinter', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_harold_pinter', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_pope_pius_xii', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_pope_pius_xii', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_pope_pius_xii', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_ramakrishna', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_ramakrishna', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_ramakrishna', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_ayn_rand_and_objectivism', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_ayn_rand_and_objectivism', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_ayn_rand_and_objectivism', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_ronald_reagan', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_ronald_reagan', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_ronald_reagan', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_jacques_rivette', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_jacques_rivette', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_jane_roberts', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_jane_roberts', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_jane_roberts', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_eleanor_roosevelt', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_eleanor_roosevelt', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_eleanor_roosevelt', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_franklin_d__roosevelt', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_franklin_d__roosevelt', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_franklin_d__roosevelt', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_theodore_roosevelt', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_theodore_roosevelt', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_works_on_shakira', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_works_on_shakira', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_works_on_shakira', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_william_howard_taft', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_william_howard_taft', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_william_howard_taft', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_margaret_thatcher', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_margaret_thatcher', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_margaret_thatcher', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_justin_trudeau', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_justin_trudeau', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_justin_trudeau', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_harry_s__truman', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_harry_s__truman', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_harry_s__truman', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_united_states_presidential_spouses_and_first_ladies', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_martin_van_buren', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_martin_van_buren', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_martin_van_buren', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_swami_vivekananda', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_swami_vivekananda', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_swami_vivekananda', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_george_washington', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_george_washington', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_george_washington', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_orson_welles', 'bibliography').
instance_of('bibliography', 'genre').
instance_of('bibliography_of_orson_welles', 'bibliography').
instance_of('bibliography', 'literary_form').
instance_of('bibliography_of_orson_welles', 'bibliography').
instance_of('bibliography', 'metaclass').
instance_of('bibliography_of_woodrow_wilson', 'bibliography').
instance_of('bibliography', 'field_of_study').
instance_of('bibliography_of_woodrow_wilson', 'bibliography').
instance_of('bibliography', 'academic_discipline').
instance_of('bibliography_of_zakariyya_kandhlawi', 'human').
instance_of('human', 'organisms_known_by_a_particular_common_name').
instance_of('biography', 'art_genre_by_arts_form').
instance_of('art_genre_by_arts_form', 'metaclass').
instance_of('biography', 'literary_genre').
instance_of('literary_genre', 'metaclass').
instance_of('biography', 'field_of_work').
instance_of('field_of_work', 'metaclass').
instance_of('autobiografiction', 'genre').
instance_of('genre', 'metaclass').
instance_of('autobiography', 'literary_genre').
instance_of('literary_genre', 'metaclass').
instance_of('autobiography', 'book_form').
instance_of('book_form', 'metaclass').
part_of('biography', 'study_of_history').
part_of('study_of_history', 'social_sciences_and_humanities').
part_of('biography', 'study_of_history').
part_of('study_of_history', 'history__heritage_and_archaeology').
different_from('biography', 'vita').
different_from('vita', 'vita').
different_from('biography', 'personal_history').
different_from('personal_history', 'memoir').
different_from('biography', 'biographer').
different_from('biographer', 'personal_historian').
different_from('biography', 'personal_history').
different_from('personal_history', 'personal_history').
different_from('biography', 'personal_history').
different_from('personal_history', 'autobiography').
different_from('autobiography', 'personal_history').
different_from('personal_history', 'memoir').
different_from('autobiography', 'memoir').
different_from('memoir', 'personal_history').
different_from('autobiography', 'personal_history').
different_from('personal_history', 'personal_history').
different_from('autobiography', 'personal_history').
different_from('personal_history', 'biography').
subclass_of('biography', 'literature').
subclass_of('literature', 'literary_work').
subclass_of('biography', 'literature').
subclass_of('literature', 'class').
subclass_of('biography', 'literature').
subclass_of('literature', 'art').
subclass_of('biography', 'non_fiction_work').
subclass_of('non_fiction_work', 'publication').
subclass_of('biography', 'biographical_work').
subclass_of('biographical_work', 'non_fiction').
subclass_of('biography', 'non_fiction_work').
subclass_of('non_fiction_work', 'literary_work').
subclass_of('autobiography', 'biography').
subclass_of('biography', 'literature').
subclass_of('autobiography', 'personal_narrative').
subclass_of('personal_narrative', 'genre').
subclass_of('autobiography', 'personal_narrative').
subclass_of('personal_narrative', 'narrative').
subclass_of('autobiography', 'personal_narrative').
subclass_of('personal_narrative', 'report').
subclass_of('autobiography', 'personal_narrative').
subclass_of('personal_narrative', 'historical_source').
subclass_of('autobiography', 'biography').
subclass_of('biography', 'non_fiction_work').
subclass_of('autobiography', 'biography').
subclass_of('biography', 'biographical_work').
subclass_of('biographical_criticism', 'literary_studies').
subclass_of('literary_studies', 'humanities').
subclass_of('biographical_criticism', 'literary_criticism').
subclass_of('literary_criticism', 'criticism').
subclass_of('biographical_criticism', 'literary_studies').
subclass_of('literary_studies', 'philology').
described_by_source('biography', 'american_medical_biographies').
described_by_source('american_medical_biographies', 'american_medical_biographies').
has_part_s_('autobiografiction', 'fiction').
has_part_s_('fiction', 'work_of_fiction').
