http___www_wikidata_org_prop_direct_p279('ancient_greek_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('inca_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('medieval_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('prehistoric_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('renaissance_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('alternative_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('animal_technology', 'animal_care').
http___www_wikidata_org_prop_direct_p279('animal_care', 'animal_care').
http___www_wikidata_org_prop_direct_p279('animal_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('architectural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'planned_process').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'process').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'economic_activity').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'intellectual_activity').
http___www_wikidata_org_prop_direct_p279('electrical_engineering_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('enabling_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('high_tech', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('industrial_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('low_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('marine_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('microtechnology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('open_source_appropriate_technology', 'appropriate_technology').
http___www_wikidata_org_prop_direct_p279('appropriate_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('open_source_appropriate_technology', 'open_source_technology').
http___www_wikidata_org_prop_direct_p279('open_source_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('subsea_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('geographic_information_science', 'information_science').
http___www_wikidata_org_prop_direct_p279('information_science', 'science').
http___www_wikidata_org_prop_direct_p279('geographic_information_science', 'geoinformation_science').
http___www_wikidata_org_prop_direct_p279('geoinformation_science', 'geospatial_science').
http___www_wikidata_org_prop_direct_p279('geomatics', 'computer_science').
http___www_wikidata_org_prop_direct_p279('computer_science', 'formal_science').
http___www_wikidata_org_prop_direct_p279('geomatics', 'spatial_science').
http___www_wikidata_org_prop_direct_p279('spatial_science', 'earth_science').
http___www_wikidata_org_prop_direct_p279('sociotechnology', 'sociology').
http___www_wikidata_org_prop_direct_p279('sociology', 'social_science').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('message', 'information').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('message', 'object').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'applied_science').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'botany').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'management').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement_in_australia', 'anti_nuclear_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement', 'social_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement_in_germany', 'anti_nuclear_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement', 'social_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'conflict').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'occurrence').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'activity').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'message').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'demonstration_or_protest').
http___www_wikidata_org_prop_direct_p279('ancient_greek_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('inca_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('medieval_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('prehistoric_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('renaissance_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('alternative_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('animal_technology', 'animal_care').
http___www_wikidata_org_prop_direct_p279('animal_care', 'animal_care').
http___www_wikidata_org_prop_direct_p279('animal_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('architectural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'planned_process').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'process').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'economic_activity').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'intellectual_activity').
http___www_wikidata_org_prop_direct_p279('electrical_engineering_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('enabling_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('high_tech', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('industrial_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('low_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('marine_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('microtechnology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('open_source_appropriate_technology', 'appropriate_technology').
http___www_wikidata_org_prop_direct_p279('appropriate_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('open_source_appropriate_technology', 'open_source_technology').
http___www_wikidata_org_prop_direct_p279('open_source_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('subsea_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('geographic_information_science', 'information_science').
http___www_wikidata_org_prop_direct_p279('information_science', 'science').
http___www_wikidata_org_prop_direct_p279('geographic_information_science', 'geoinformation_science').
http___www_wikidata_org_prop_direct_p279('geoinformation_science', 'geospatial_science').
http___www_wikidata_org_prop_direct_p279('geomatics', 'computer_science').
http___www_wikidata_org_prop_direct_p279('computer_science', 'formal_science').
http___www_wikidata_org_prop_direct_p279('geomatics', 'spatial_science').
http___www_wikidata_org_prop_direct_p279('spatial_science', 'earth_science').
http___www_wikidata_org_prop_direct_p279('sociotechnology', 'sociology').
http___www_wikidata_org_prop_direct_p279('sociology', 'social_science').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('message', 'information').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('message', 'object').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'applied_science').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'botany').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'management').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement_in_australia', 'anti_nuclear_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement', 'social_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement_in_germany', 'anti_nuclear_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement', 'social_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'conflict').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'occurrence').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'activity').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'message').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'demonstration_or_protest').
http___www_wikidata_org_prop_direct_p279('inca_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('prehistoric_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('architectural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('electrical_engineering_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('enabling_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('ancient_greek_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('inca_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('medieval_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('prehistoric_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('renaissance_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('alternative_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('animal_technology', 'animal_care').
http___www_wikidata_org_prop_direct_p279('animal_care', 'animal_care').
http___www_wikidata_org_prop_direct_p279('animal_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('architectural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'planned_process').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'intellectual_activity').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'process').
http___www_wikidata_org_prop_direct_p279('disruptive_innovation', 'innovation').
http___www_wikidata_org_prop_direct_p279('innovation', 'economic_activity').
http___www_wikidata_org_prop_direct_p279('electrical_engineering_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('enabling_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('high_tech', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('industrial_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('low_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('marine_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('microtechnology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('open_source_appropriate_technology', 'open_source_technology').
http___www_wikidata_org_prop_direct_p279('open_source_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('open_source_appropriate_technology', 'appropriate_technology').
http___www_wikidata_org_prop_direct_p279('appropriate_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('subsea_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('geographic_information_science', 'geoinformation_science').
http___www_wikidata_org_prop_direct_p279('geoinformation_science', 'geospatial_science').
http___www_wikidata_org_prop_direct_p279('geographic_information_science', 'information_science').
http___www_wikidata_org_prop_direct_p279('information_science', 'science').
http___www_wikidata_org_prop_direct_p279('geomatics', 'computer_science').
http___www_wikidata_org_prop_direct_p279('computer_science', 'formal_science').
http___www_wikidata_org_prop_direct_p279('geomatics', 'spatial_science').
http___www_wikidata_org_prop_direct_p279('spatial_science', 'earth_science').
http___www_wikidata_org_prop_direct_p279('sociotechnology', 'sociology').
http___www_wikidata_org_prop_direct_p279('sociology', 'social_science').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('message', 'object').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('message', 'information').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'technology').
http___www_wikidata_org_prop_direct_p279('technology', 'science_and_technology').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'management').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'applied_science').
http___www_wikidata_org_prop_direct_p279('agricultural_technology', 'agricultural_science').
http___www_wikidata_org_prop_direct_p279('agricultural_science', 'botany').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement_in_australia', 'anti_nuclear_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement', 'social_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement_in_germany', 'anti_nuclear_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_movement', 'social_movement').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'demonstration_or_protest').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'conflict').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'message').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'occurrence').
http___www_wikidata_org_prop_direct_p279('anti_nuclear_protests', 'protest').
http___www_wikidata_org_prop_direct_p279('protest', 'activity').
http___www_wikidata_org_prop_direct_p279('civic_application', 'application').
http___www_wikidata_org_prop_direct_p279('application', 'software').
http___www_wikidata_org_prop_direct_p279('communication_with_extraterrestrial_intelligence', 'communication').
http___www_wikidata_org_prop_direct_p279('communication', 'information_exchange').
http___www_wikidata_org_prop_direct_p279('cosmic_call', 'active_seti').
http___www_wikidata_org_prop_direct_p279('active_seti', 'message').
http___www_wikidata_org_prop_direct_p279('crisis_camp', 'barcamp').
http___www_wikidata_org_prop_direct_p279('barcamp', 'unconference').
http___www_wikidata_org_prop_direct_p279('crowdfunding', 'funding').
http___www_wikidata_org_prop_direct_p279('funding', 'income').
http___www_wikidata_org_prop_direct_p279('crowdfunding', 'funding').
http___www_wikidata_org_prop_direct_p279('funding', 'financial_services').
http___www_wikidata_org_prop_direct_p279('crowdfunding', 'capital_procurement').
http___www_wikidata_org_prop_direct_p279('capital_procurement', 'procurement').
http___www_wikidata_org_prop_direct_p279('crowdfunding', 'ai').
http___www_wikidata_org_prop_direct_p279('ai', 'model').
http___www_wikidata_org_prop_direct_p279('crowdfunding', 'sharing_economy').
http___www_wikidata_org_prop_direct_p279('sharing_economy', 'economic_activity').
http___www_wikidata_org_prop_direct_p279('crowdfunding', 'crowdsourcing').
http___www_wikidata_org_prop_direct_p279('crowdsourcing', 'human_resource_management').
http___www_wikidata_org_prop_direct_p279('cultural_lag', 'social_phenomenon').
http___www_wikidata_org_prop_direct_p279('social_phenomenon', 'phenomenon').
http___www_wikidata_org_prop_direct_p279('cyber_dissident', 'activist').
http___www_wikidata_org_prop_direct_p279('activist', 'person').
http___www_wikidata_org_prop_direct_p279('de_mail', 'message_traffic').
http___www_wikidata_org_prop_direct_p279('message_traffic', 'communication').
http___www_wikidata_org_prop_direct_p279('digital_anthropology', 'anthropology').
http___www_wikidata_org_prop_direct_p279('anthropology', 'social_science').
http___www_wikidata_org_prop_direct_p279('digital_journalism', 'web_writing').
http___www_wikidata_org_prop_direct_p279('web_writing', 'content_creation').
http___www_wikidata_org_prop_direct_p279('digital_journalism', 'web_writing').
http___www_wikidata_org_prop_direct_p279('web_writing', 'writing').
http___www_wikidata_org_prop_direct_p279('digital_journalism', 'journalism').
http___www_wikidata_org_prop_direct_p279('journalism', 'activity').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'education').
http___www_wikidata_org_prop_direct_p279('education', 'knowledge_sharing').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'educational_activity').
http___www_wikidata_org_prop_direct_p279('educational_activity', 'intentional_human_activity').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'educational_activity').
http___www_wikidata_org_prop_direct_p279('educational_activity', 'helping_behavior').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'education').
http___www_wikidata_org_prop_direct_p279('education', 'service').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'outsourcing').
http___www_wikidata_org_prop_direct_p279('outsourcing', 'activity').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'education').
http___www_wikidata_org_prop_direct_p279('education', 'social_process').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'educational_activity').
http___www_wikidata_org_prop_direct_p279('educational_activity', 'learning').
http___www_wikidata_org_prop_direct_p279('education_by_algorithm', 'outsourcing').
http___www_wikidata_org_prop_direct_p279('outsourcing', 'business_process').
http___www_wikidata_org_prop_direct_p31('inca_technology', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('prehistoric_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('animal_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('architectural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('creative_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('high_tech', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('industrial_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('low_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('microtechnology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('open_source_appropriate_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('subsea_technology', 'industry').
http___www_wikidata_org_prop_direct_p31('industry', 'economic_concept').
http___www_wikidata_org_prop_direct_p31('geographic_information_science', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geographic_information_science', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geomatics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('science_and_technology_studies', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'field_of_work').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('across_the_universe__message_', 'musical_work_composition').
http___www_wikidata_org_prop_direct_p31('musical_work_composition', 'metaclass').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('alt_tech', 'group').
http___www_wikidata_org_prop_direct_p31('group', 'metaclass').
http___www_wikidata_org_prop_direct_p31('anti_nuclear_movement_in_australia', 'aspect_in_a_geographic_region').
http___www_wikidata_org_prop_direct_p31('aspect_in_a_geographic_region', 'metaclass').
http___www_wikidata_org_prop_direct_p31('inca_technology', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('prehistoric_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('animal_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('architectural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('creative_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('high_tech', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('industrial_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('low_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('microtechnology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('open_source_appropriate_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('subsea_technology', 'industry').
http___www_wikidata_org_prop_direct_p31('industry', 'economic_concept').
http___www_wikidata_org_prop_direct_p31('geographic_information_science', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geographic_information_science', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geomatics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('science_and_technology_studies', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'field_of_work').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('across_the_universe__message_', 'musical_work_composition').
http___www_wikidata_org_prop_direct_p31('musical_work_composition', 'metaclass').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('alt_tech', 'group').
http___www_wikidata_org_prop_direct_p31('group', 'metaclass').
http___www_wikidata_org_prop_direct_p31('anti_nuclear_movement_in_australia', 'aspect_in_a_geographic_region').
http___www_wikidata_org_prop_direct_p31('aspect_in_a_geographic_region', 'metaclass').
http___www_wikidata_org_prop_direct_p31('inca_technology', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('prehistoric_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('architectural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('creative_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('inca_technology', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('prehistoric_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
http___www_wikidata_org_prop_direct_p31('aspect_of_history', 'metaclass').
http___www_wikidata_org_prop_direct_p31('animal_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('architectural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('architectural_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('creative_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('entertainment_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('entertainment_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('high_tech', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('industrial_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('low_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('microtechnology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('open_source_appropriate_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('subsea_technology', 'industry').
http___www_wikidata_org_prop_direct_p31('industry', 'economic_concept').
http___www_wikidata_org_prop_direct_p31('nick_bilton', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('christopher_fabian', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('yannik_heinze', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('ellis_horowitz', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('boon_thau_loo', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('mac_the_knife', 'magazine').
http___www_wikidata_org_prop_direct_p31('magazine', 'type_of_publication').
http___www_wikidata_org_prop_direct_p31('mac_the_knife', 'magazine').
http___www_wikidata_org_prop_direct_p31('magazine', 'type_of_mass_media').
http___www_wikidata_org_prop_direct_p31('clement_ogaja', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('charles_l__perkins', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('jason_pontin', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('sheizaf_rafaeli', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('sartaj_sahni', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('bright_simons', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('jason_cranford_teague', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('clive_thompson__journalist_', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('peter_wayner', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('nick_zhang', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('geographic_information_science', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geographic_information_science', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geomatics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('electrical_polarity', 'quality').
http___www_wikidata_org_prop_direct_p31('quality', 'type_of_property').
http___www_wikidata_org_prop_direct_p31('electrical_polarity', 'quality').
http___www_wikidata_org_prop_direct_p31('quality', 'philosophical_concept').
http___www_wikidata_org_prop_direct_p31('science_and_technology_studies', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('sociotechnology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('across_the_universe__message_', 'musical_work_composition').
http___www_wikidata_org_prop_direct_p31('musical_work_composition', 'metaclass').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('agricultural_technology', 'type_of_technology').
http___www_wikidata_org_prop_direct_p31('type_of_technology', 'metaclass').
http___www_wikidata_org_prop_direct_p31('anti_nuclear_movement_in_australia', 'aspect_in_a_geographic_region').
http___www_wikidata_org_prop_direct_p31('aspect_in_a_geographic_region', 'metaclass').
http___www_wikidata_org_prop_direct_p31('change_org', 'organization').
http___www_wikidata_org_prop_direct_p31('organization', 'social_science_concept').
http___www_wikidata_org_prop_direct_p31('change_org', 'website').
http___www_wikidata_org_prop_direct_p31('website', 'type_of_website').
http___www_wikidata_org_prop_direct_p31('coding_it_forward', 'nonprofit_organization').
http___www_wikidata_org_prop_direct_p31('nonprofit_organization', 'industry').
http___www_wikidata_org_prop_direct_p31('coding_it_forward', 'nonprofit_organization').
http___www_wikidata_org_prop_direct_p31('nonprofit_organization', 'legal_form').
http___www_wikidata_org_prop_direct_p31('coding_it_forward', 'nonprofit_organization').
http___www_wikidata_org_prop_direct_p31('nonprofit_organization', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('the_cool_stuff_collective', 'television_series').
http___www_wikidata_org_prop_direct_p31('television_series', 'type_of_television_program').
http___www_wikidata_org_prop_direct_p31('critical_code_studies', 'branch_of_science').
http___www_wikidata_org_prop_direct_p31('branch_of_science', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('criticism_of_technology', 'political_ideology').
http___www_wikidata_org_prop_direct_p31('political_ideology', 'type_of_world_view').
http___www_wikidata_org_prop_direct_p31('current__financial_services_company_', 'company').
http___www_wikidata_org_prop_direct_p31('company', 'legal_form').
http___www_wikidata_org_prop_direct_p31('current__financial_services_company_', 'company').
http___www_wikidata_org_prop_direct_p31('company', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('dead_internet_theory', 'conspiracy_theory').
http___www_wikidata_org_prop_direct_p31('conspiracy_theory', 'reductionism').
http___www_wikidata_org_prop_direct_p31('digital_anthropology', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('digital_anthropology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('digital_anthropology', 'branch_of_anthropology').
http___www_wikidata_org_prop_direct_p31('branch_of_anthropology', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('digital_anthropology', 'field_of_work').
http___www_wikidata_org_prop_direct_p31('field_of_work', 'metaclass').
http___www_wikidata_org_prop_direct_p1269('renaissance_technology', 'history_of_technology').
http___www_wikidata_org_prop_direct_p1269('history_of_technology', 'technology').
http___www_wikidata_org_prop_direct_p1269('enabling_technology', 'strategic_planning').
http___www_wikidata_org_prop_direct_p1269('strategic_planning', 'strategic_management').
http___www_wikidata_org_prop_direct_p1269('ai_boom', 'artificial_intelligence').
http___www_wikidata_org_prop_direct_p1269('artificial_intelligence', 'computer_science').
http___www_wikidata_org_prop_direct_p1269('ai_boom', 'artificial_intelligence').
http___www_wikidata_org_prop_direct_p1269('artificial_intelligence', 'cognitive_science').
http___www_wikidata_org_prop_direct_p1269('renaissance_technology', 'history_of_technology').
http___www_wikidata_org_prop_direct_p1269('history_of_technology', 'technology').
http___www_wikidata_org_prop_direct_p1269('enabling_technology', 'strategic_planning').
http___www_wikidata_org_prop_direct_p1269('strategic_planning', 'strategic_management').
http___www_wikidata_org_prop_direct_p1269('ai_boom', 'artificial_intelligence').
http___www_wikidata_org_prop_direct_p1269('artificial_intelligence', 'computer_science').
http___www_wikidata_org_prop_direct_p1269('ai_boom', 'artificial_intelligence').
http___www_wikidata_org_prop_direct_p1269('artificial_intelligence', 'cognitive_science').
http___www_wikidata_org_prop_direct_p1269('enabling_technology', 'strategic_planning').
http___www_wikidata_org_prop_direct_p1269('strategic_planning', 'strategic_management').
http___www_wikidata_org_prop_direct_p1269('renaissance_technology', 'history_of_technology').
http___www_wikidata_org_prop_direct_p1269('history_of_technology', 'technology').
http___www_wikidata_org_prop_direct_p1269('enabling_technology', 'strategic_planning').
http___www_wikidata_org_prop_direct_p1269('strategic_planning', 'strategic_management').
http___www_wikidata_org_prop_direct_p1269('ai_boom', 'artificial_intelligence').
http___www_wikidata_org_prop_direct_p1269('artificial_intelligence', 'computer_science').
http___www_wikidata_org_prop_direct_p1269('ai_boom', 'artificial_intelligence').
http___www_wikidata_org_prop_direct_p1269('artificial_intelligence', 'cognitive_science').
http___www_wikidata_org_prop_direct_p1269('digital_media_use_and_mental_health', 'mental_health').
http___www_wikidata_org_prop_direct_p1269('mental_health', 'well_being').
http___www_wikidata_org_prop_direct_p1269('digital_media_use_and_mental_health', 'mental_health').
http___www_wikidata_org_prop_direct_p1269('mental_health', 'quality_of_life').
http___www_wikidata_org_prop_direct_p1269('digital_media_use_and_mental_health', 'mental_health').
http___www_wikidata_org_prop_direct_p1269('mental_health', 'health_risk').
http___www_wikidata_org_prop_direct_p1542('disruptive_innovation', 'disruption').
http___www_wikidata_org_prop_direct_p1542('disruption', 'change').
http___www_wikidata_org_prop_direct_p1542('disruptive_innovation', 'disruption').
http___www_wikidata_org_prop_direct_p1542('disruption', 'delay').
http___www_wikidata_org_prop_direct_p1542('disruptive_innovation', 'disruption').
http___www_wikidata_org_prop_direct_p1542('disruption', 'change').
http___www_wikidata_org_prop_direct_p1542('disruptive_innovation', 'disruption').
http___www_wikidata_org_prop_direct_p1542('disruption', 'delay').
http___www_wikidata_org_prop_direct_p1542('disruptive_innovation', 'disruption').
http___www_wikidata_org_prop_direct_p1542('disruption', 'change').
http___www_wikidata_org_prop_direct_p1542('disruptive_innovation', 'disruption').
http___www_wikidata_org_prop_direct_p1542('disruption', 'delay').
http___www_wikidata_org_prop_direct_p527('geomatics', 'study_of_geomatics').
http___www_wikidata_org_prop_direct_p527('study_of_geomatics', 'bachelor_s_degree').
http___www_wikidata_org_prop_direct_p527('geomatics', 'study_of_geomatics').
http___www_wikidata_org_prop_direct_p527('study_of_geomatics', 'masters_program').
http___www_wikidata_org_prop_direct_p527('alt_tech', 'telegram').
http___www_wikidata_org_prop_direct_p527('telegram', 'mtproto').
http___www_wikidata_org_prop_direct_p527('alt_tech', 'telegram').
http___www_wikidata_org_prop_direct_p527('telegram', 'mtproxy').
http___www_wikidata_org_prop_direct_p527('big_tech', 'tiktok').
http___www_wikidata_org_prop_direct_p527('tiktok', 'tiktok_video').
http___www_wikidata_org_prop_direct_p527('big_tech', 'amazon').
http___www_wikidata_org_prop_direct_p527('amazon', 'merch_by_amazon').
http___www_wikidata_org_prop_direct_p527('big_tech', 'tiktok').
http___www_wikidata_org_prop_direct_p527('tiktok', 'tiktoker').
http___www_wikidata_org_prop_direct_p527('geomatics', 'study_of_geomatics').
http___www_wikidata_org_prop_direct_p527('study_of_geomatics', 'bachelor_s_degree').
http___www_wikidata_org_prop_direct_p527('geomatics', 'study_of_geomatics').
http___www_wikidata_org_prop_direct_p527('study_of_geomatics', 'masters_program').
http___www_wikidata_org_prop_direct_p527('alt_tech', 'telegram').
http___www_wikidata_org_prop_direct_p527('telegram', 'mtproto').
http___www_wikidata_org_prop_direct_p527('alt_tech', 'telegram').
http___www_wikidata_org_prop_direct_p527('telegram', 'mtproxy').
http___www_wikidata_org_prop_direct_p527('big_tech', 'tiktok').
http___www_wikidata_org_prop_direct_p527('tiktok', 'tiktok_video').
http___www_wikidata_org_prop_direct_p527('big_tech', 'amazon').
http___www_wikidata_org_prop_direct_p527('amazon', 'merch_by_amazon').
http___www_wikidata_org_prop_direct_p527('big_tech', 'tiktok').
http___www_wikidata_org_prop_direct_p527('tiktok', 'tiktoker').
http___www_wikidata_org_prop_direct_p527('geomatics', 'study_of_geomatics').
http___www_wikidata_org_prop_direct_p527('study_of_geomatics', 'bachelor_s_degree').
http___www_wikidata_org_prop_direct_p527('geomatics', 'study_of_geomatics').
http___www_wikidata_org_prop_direct_p527('study_of_geomatics', 'masters_program').
http___www_wikidata_org_prop_direct_p527('alt_tech', 'telegram').
http___www_wikidata_org_prop_direct_p527('telegram', 'mtproxy').
http___www_wikidata_org_prop_direct_p527('alt_tech', 'telegram').
http___www_wikidata_org_prop_direct_p527('telegram', 'mtproto').
http___www_wikidata_org_prop_direct_p527('big_tech', 'tiktok').
http___www_wikidata_org_prop_direct_p527('tiktok', 'tiktoker').
http___www_wikidata_org_prop_direct_p527('big_tech', 'tiktok').
http___www_wikidata_org_prop_direct_p527('tiktok', 'tiktok_video').
http___www_wikidata_org_prop_direct_p527('big_tech', 'amazon').
http___www_wikidata_org_prop_direct_p527('amazon', 'merch_by_amazon').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p138('geoinformatics', 'informatics').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geomatic').
http___www_wikidata_org_prop_direct_p138('geomatic', 'geographical').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p138('geoinformatics', 'geoinformation').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'arecibo').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'james_gregory').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'william_e__gordon').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p138('geoinformatics', 'informatics').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geomatic').
http___www_wikidata_org_prop_direct_p138('geomatic', 'geographical').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p138('geoinformatics', 'geoinformation').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'arecibo').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'james_gregory').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'william_e__gordon').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geomatic').
http___www_wikidata_org_prop_direct_p138('geomatic', 'geographic').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p138('geoinformatics', 'geoinformation').
http___www_wikidata_org_prop_direct_p138('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p138('geoinformatics', 'informatics').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'james_gregory').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'arecibo').
http___www_wikidata_org_prop_direct_p138('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p138('arecibo_radio_telescope', 'william_e__gordon').
http___www_wikidata_org_prop_direct_p1366('geomatics', 'spatial_science').
http___www_wikidata_org_prop_direct_p1366('spatial_science', 'geospatial_science').
http___www_wikidata_org_prop_direct_p1366('geomatics', 'spatial_science').
http___www_wikidata_org_prop_direct_p1366('spatial_science', 'geospatial_science').
http___www_wikidata_org_prop_direct_p1366('geomatics', 'spatial_science').
http___www_wikidata_org_prop_direct_p1366('spatial_science', 'geospatial_science').
http___www_wikidata_org_prop_direct_p1889('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p1889('geoinformatics', 'gis_science').
http___www_wikidata_org_prop_direct_p1889('technology_and_society', 'interdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('interdisciplinarity', 'transdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('technology_and_society', 'interdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('interdisciplinarity', 'multidisciplinarity').
http___www_wikidata_org_prop_direct_p1889('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p1889('geoinformatics', 'gis_science').
http___www_wikidata_org_prop_direct_p1889('technology_and_society', 'interdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('interdisciplinarity', 'transdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('technology_and_society', 'interdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('interdisciplinarity', 'multidisciplinarity').
http___www_wikidata_org_prop_direct_p1889('geomatics', 'geoinformatics').
http___www_wikidata_org_prop_direct_p1889('geoinformatics', 'gis_science').
http___www_wikidata_org_prop_direct_p1889('geomatics', 'geomatics_engineering').
http___www_wikidata_org_prop_direct_p1889('geomatics_engineering', 'geodetic_engineering').
http___www_wikidata_org_prop_direct_p1889('technology_and_society', 'interdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('interdisciplinarity', 'transdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('technology_and_society', 'interdisciplinarity').
http___www_wikidata_org_prop_direct_p1889('interdisciplinarity', 'multidisciplinarity').
http___www_wikidata_org_prop_direct_p361('sociotechnology', 'technology_assessment').
http___www_wikidata_org_prop_direct_p361('technology_assessment', 'philosophy_of_technology').
http___www_wikidata_org_prop_direct_p361('sociotechnology', 'technology_assessment').
http___www_wikidata_org_prop_direct_p361('technology_assessment', 'philosophy_of_technology').
http___www_wikidata_org_prop_direct_p361('sociotechnology', 'technology_assessment').
http___www_wikidata_org_prop_direct_p361('technology_assessment', 'philosophy_of_technology').
http___www_wikidata_org_prop_direct_p361('crowdfunding', 'sharing_economy').
http___www_wikidata_org_prop_direct_p361('sharing_economy', 'circular_economy').
http___www_wikidata_org_prop_direct_p2578('sociotechnology', 'technology').
http___www_wikidata_org_prop_direct_p2578('technology', 'technique').
http___www_wikidata_org_prop_direct_p2578('sociotechnology', 'technology').
http___www_wikidata_org_prop_direct_p2578('technology', 'technique').
http___www_wikidata_org_prop_direct_p2578('sociotechnology', 'technology').
http___www_wikidata_org_prop_direct_p2578('technology', 'technique').
http___www_wikidata_org_prop_direct_p155('age_of_artificial_intelligence', 'digital_revolution').
http___www_wikidata_org_prop_direct_p155('digital_revolution', 'second_industrial_revolution').
http___www_wikidata_org_prop_direct_p155('age_of_artificial_intelligence', 'digital_revolution').
http___www_wikidata_org_prop_direct_p155('digital_revolution', 'second_industrial_revolution').
http___www_wikidata_org_prop_direct_p155('age_of_artificial_intelligence', 'digital_revolution').
http___www_wikidata_org_prop_direct_p155('digital_revolution', 'second_industrial_revolution').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('age_of_artificial_intelligence', 'http___www_wikidata_org_prop_novalue_p582').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('http___www_wikidata_org_prop_novalue_p582', 'http___www_w3_org_2002_07_owl_class').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('age_of_artificial_intelligence', 'http___www_wikidata_org_prop_novalue_p582').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('http___www_wikidata_org_prop_novalue_p582', 'http___www_w3_org_2002_07_owl_class').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('age_of_artificial_intelligence', 'http___www_wikidata_org_prop_novalue_p582').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('http___www_wikidata_org_prop_novalue_p582', 'http___www_w3_org_2002_07_owl_class').
http___www_wikidata_org_prop_direct_p460('agricultural_technology', 'agricultural_technology').
http___www_wikidata_org_prop_direct_p460('agricultural_technology', 'agricultural_engineering').
http___www_wikidata_org_prop_direct_p460('agricultural_technology', 'agricultural_technology').
http___www_wikidata_org_prop_direct_p460('agricultural_technology', 'agricultural_engineering').
http___www_wikidata_org_prop_direct_p460('agricultural_technology', 'agricultural_technology').
http___www_wikidata_org_prop_direct_p460('agricultural_technology', 'agricultural_engineering').
http___www_wikidata_org_prop_direct_p17('anti_nuclear_movement_in_australia', 'australia').
http___www_wikidata_org_prop_direct_p17('australia', 'australia').
http___www_wikidata_org_prop_direct_p17('anti_nuclear_movement_in_germany', 'germany').
http___www_wikidata_org_prop_direct_p17('germany', 'germany').
http___www_wikidata_org_prop_direct_p17('arecibo_message', 'puerto_rico').
http___www_wikidata_org_prop_direct_p17('puerto_rico', 'united_states').
http___www_wikidata_org_prop_direct_p17('anti_nuclear_movement_in_australia', 'australia').
http___www_wikidata_org_prop_direct_p17('australia', 'australia').
http___www_wikidata_org_prop_direct_p17('anti_nuclear_movement_in_germany', 'germany').
http___www_wikidata_org_prop_direct_p17('germany', 'germany').
http___www_wikidata_org_prop_direct_p17('arecibo_message', 'puerto_rico').
http___www_wikidata_org_prop_direct_p17('puerto_rico', 'united_states').
http___www_wikidata_org_prop_direct_p17('anti_nuclear_movement_in_australia', 'australia').
http___www_wikidata_org_prop_direct_p17('australia', 'australia').
http___www_wikidata_org_prop_direct_p17('anti_nuclear_movement_in_germany', 'germany').
http___www_wikidata_org_prop_direct_p17('germany', 'germany').
http___www_wikidata_org_prop_direct_p17('arecibo_message', 'puerto_rico').
http___www_wikidata_org_prop_direct_p17('puerto_rico', 'united_states').
http___www_wikidata_org_prop_direct_p17('asian_news_international_vs__wikimedia_foundation', 'india').
http___www_wikidata_org_prop_direct_p17('india', 'india').
http___www_wikidata_org_prop_direct_p17('change_org', 'united_states').
http___www_wikidata_org_prop_direct_p17('united_states', 'united_states').
http___www_wikidata_org_prop_direct_p17('de_mail', 'germany').
http___www_wikidata_org_prop_direct_p17('germany', 'germany').
http___www_wikidata_org_prop_direct_p131('arecibo_message', 'arecibo').
http___www_wikidata_org_prop_direct_p131('arecibo', 'puerto_rico').
http___www_wikidata_org_prop_direct_p131('arecibo_message', 'arecibo').
http___www_wikidata_org_prop_direct_p131('arecibo', 'puerto_rico').
http___www_wikidata_org_prop_direct_p131('arecibo_message', 'arecibo').
http___www_wikidata_org_prop_direct_p131('arecibo', 'puerto_rico').
http___www_wikidata_org_prop_direct_p276('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p276('arecibo_radio_telescope', 'esperanza').
http___www_wikidata_org_prop_direct_p276('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p276('arecibo_radio_telescope', 'esperanza').
http___www_wikidata_org_prop_direct_p276('arecibo_message', 'arecibo_radio_telescope').
http___www_wikidata_org_prop_direct_p276('arecibo_radio_telescope', 'esperanza').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('inca_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('medieval_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('alternative_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_care', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('architectural_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('inca_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('medieval_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('alternative_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_care', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('architectural_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('inca_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('medieval_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('alternative_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_care', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('architectural_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'planned_process').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'process').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'economic_activity').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'intellectual_activity').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('enabling_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('high_tech', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('ancient_greek_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('inca_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('medieval_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('prehistoric_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('renaissance_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('alternative_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('animal_technology', 'animal_care').
subclass_of('animal_care', 'animal_care').
subclass_of('animal_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('architectural_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'planned_process').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'process').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'economic_activity').
subclass_of('disruptive_innovation', 'innovation').
subclass_of('innovation', 'intellectual_activity').
subclass_of('electrical_engineering_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('enabling_technology', 'technology').
subclass_of('technology', 'science_and_technology').
subclass_of('high_tech', 'technology').
subclass_of('technology', 'science_and_technology').
instance_of('inca_technology', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('type_of_technology', 'metaclass').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('animal_technology', 'field_of_study').
instance_of('field_of_study', 'knowledge_classification').
instance_of('architectural_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('creative_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('inca_technology', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('type_of_technology', 'metaclass').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('animal_technology', 'field_of_study').
instance_of('field_of_study', 'knowledge_classification').
instance_of('architectural_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('creative_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('inca_technology', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('type_of_technology', 'metaclass').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('animal_technology', 'field_of_study').
instance_of('field_of_study', 'knowledge_classification').
instance_of('architectural_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('creative_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('high_tech', 'type_of_technology').
instance_of('type_of_technology', 'metaclass').
instance_of('inca_technology', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('prehistoric_technology', 'type_of_technology').
instance_of('type_of_technology', 'metaclass').
instance_of('history_of_timekeeping_devices_in_egypt', 'aspect_of_history').
instance_of('aspect_of_history', 'metaclass').
instance_of('animal_technology', 'field_of_study').
instance_of('field_of_study', 'knowledge_classification').
instance_of('architectural_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('creative_technology', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('high_tech', 'type_of_technology').
instance_of('type_of_technology', 'metaclass').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('history_of_technology', 'technology').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('history_of_technology', 'technology').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('history_of_technology', 'technology').
facet_of('enabling_technology', 'strategic_planning').
facet_of('strategic_planning', 'strategic_management').
facet_of('renaissance_technology', 'history_of_technology').
facet_of('history_of_technology', 'technology').
facet_of('enabling_technology', 'strategic_planning').
facet_of('strategic_planning', 'strategic_management').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruption', 'change').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruption', 'delay').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruption', 'change').
has_effect('disruptive_innovation', 'disruption').
has_effect('disruption', 'delay').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'mario_alberto_lopez').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'dinesh_prakash_mehta').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'srijit_kamath').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'andrew_leong_chye_lim').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'david_nassimi').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'eliezer_dekel').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'chih_fang_wang').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'doowon_paik').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'edward_yu_cheuk_cheng').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'james_patrick_cohoon').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'jayaram_bhasker').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'haejae_jung').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'jin_woon_woo').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'haibin_lu').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'kam_hoi_cheng').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'jong_chang_lee').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'jing_fu_jenq').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'li_shin_lin').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'keumog_lim_ahn').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'kyunrak_chong').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'joonseok_park').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'madhusudan_nigam').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'kun_suk_kim').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'kevin_w__mccullen').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'patrick_leo_jarvis').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'meongchul_song').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'raghunath_raghavan').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'rajiv_dattatrava_kane').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sangyong_han').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'san_yuan_wu').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'ten_hwang_lai').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'surendra_nahar').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'seonghun_cho').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'yookun_cho').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'wing_ning_li').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'youngju_won').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'venkat_narayan_thanvantri').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'wencheng_lu').
http___www_wikidata_org_prop_direct_p185('ellis_horowitz', 'sartaj_sahni').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'mario_alberto_lopez').
http___www_wikidata_org_prop_direct_p185('mario_alberto_lopez', 'peter_tamas_breznay').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'mario_alberto_lopez').
http___www_wikidata_org_prop_direct_p185('mario_alberto_lopez', 'kirk_boyer').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'yookun_cho').
http___www_wikidata_org_prop_direct_p185('yookun_cho', 'junyoung_heo').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'yookun_cho').
http___www_wikidata_org_prop_direct_p185('yookun_cho', 'yoo_jin_chung').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'dinesh_prakash_mehta').
http___www_wikidata_org_prop_direct_p185('dinesh_prakash_mehta', 'yan_feng').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'dinesh_prakash_mehta').
http___www_wikidata_org_prop_direct_p185('dinesh_prakash_mehta', 'sahar_idwan').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'dinesh_prakash_mehta').
http___www_wikidata_org_prop_direct_p185('dinesh_prakash_mehta', 'john_crabtree').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'dinesh_prakash_mehta').
http___www_wikidata_org_prop_direct_p185('dinesh_prakash_mehta', 'steven_stoddard').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'linda_faye_mccalla').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'arturo_gonzalez_gutierrez').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'f__david__frank__serena').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'kurki_gowdara_shashishekhar').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'mohammadreza_razzazi').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'si_qing_zheng').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'sing_ling_lee').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'teofilo_f__gonzalez').
http___www_wikidata_org_prop_direct_p185('teofilo_f__gonzalez', 'amit_m__bhosle').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'anand_rangachari').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'chau_wei_ou').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'david_koester').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'harpal_s__maini').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'jhy_chun_wang').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'jang_sun_lee').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'm__c__yang').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'maher_kaddoura').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'hankil_yoon').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'ibraheem_al_furaih').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'khaled_alsabti').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'ravi_shankar').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'todd_heywood').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'seungjo_bae').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'yeh_chin_chung').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'scott_winterstein').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'yankil_hoon').
http___www_wikidata_org_prop_direct_p185('sartaj_sahni', 'sanjay_ranka').
http___www_wikidata_org_prop_direct_p185('sanjay_ranka', 'srijit_kamath').
http___www_wikidata_org_prop_direct_p184('ellis_horowitz', 'george_e__collins').
http___www_wikidata_org_prop_direct_p184('george_e__collins', 'j__barkley_rosser').
http___www_wikidata_org_prop_direct_p184('sartaj_sahni', 'ellis_horowitz').
http___www_wikidata_org_prop_direct_p184('ellis_horowitz', 'george_e__collins').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'datacite').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'association_for_computing_machinery').
http___www_wikidata_org_prop_direct_p463('association_for_computing_machinery', 'society_publishers__coalition').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'world_federation_of_engineering_organizations').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'association_for_computing_machinery').
http___www_wikidata_org_prop_direct_p463('association_for_computing_machinery', 'chorus').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'association_for_computing_machinery').
http___www_wikidata_org_prop_direct_p463('association_for_computing_machinery', 'international_federation_for_information_processing').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'chorus').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'association_for_computing_machinery').
http___www_wikidata_org_prop_direct_p463('association_for_computing_machinery', 'orcid__inc_').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'association_for_computing_machinery').
http___www_wikidata_org_prop_direct_p463('association_for_computing_machinery', 'committee_on_publication_ethics').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'association_for_computing_machinery').
http___www_wikidata_org_prop_direct_p463('association_for_computing_machinery', 'international_association_of_scientific__technical__and_medical_publishers').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'association_of_learned_and_professional_society_publishers').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'orcid__inc_').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'committee_on_publication_ethics').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'ieee_industry_standards_and_technology_organization').
http___www_wikidata_org_prop_direct_p463('sartaj_sahni', 'institute_of_electrical_and_electronics_engineers').
http___www_wikidata_org_prop_direct_p463('institute_of_electrical_and_electronics_engineers', 'international_association_of_scientific__technical__and_medical_publishers').
