http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'basic_research').
http___www_wikidata_org_prop_direct_p279('basic_research', 'research').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'work').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'procedure').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'software').
http___www_wikidata_org_prop_direct_p279('highly_composite_number', 'composite_number').
http___www_wikidata_org_prop_direct_p279('composite_number', 'positive_integer').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'weighted_sum').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'operation_result').
http___www_wikidata_org_prop_direct_p279('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
http___www_wikidata_org_prop_direct_p279('uniform_tiling', 'uniform_tessellation').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'researcher').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'scholar').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'basic_research').
http___www_wikidata_org_prop_direct_p279('basic_research', 'research').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'work').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'procedure').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'software').
http___www_wikidata_org_prop_direct_p279('highly_composite_number', 'composite_number').
http___www_wikidata_org_prop_direct_p279('composite_number', 'positive_integer').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'weighted_sum').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'operation_result').
http___www_wikidata_org_prop_direct_p279('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
http___www_wikidata_org_prop_direct_p279('uniform_tiling', 'uniform_tessellation').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'researcher').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'scholar').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('pure_mathematics', 'basic_research').
http___www_wikidata_org_prop_direct_p279('basic_research', 'research').
http___www_wikidata_org_prop_direct_p279('applied_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('abstract_family_of_languages', 'language_family').
http___www_wikidata_org_prop_direct_p279('language_family', 'language_group').
http___www_wikidata_org_prop_direct_p279('abstract_family_of_languages', 'language_family').
http___www_wikidata_org_prop_direct_p279('language_family', 'languoid').
http___www_wikidata_org_prop_direct_p279('actuarial_notation', 'mathematical_notation').
http___www_wikidata_org_prop_direct_p279('mathematical_notation', 'mathematical_convention').
http___www_wikidata_org_prop_direct_p279('actuarial_notation', 'mathematical_notation').
http___www_wikidata_org_prop_direct_p279('mathematical_notation', 'notation').
http___www_wikidata_org_prop_direct_p279('applicable_mathematics', 'applied_mathematics').
http___www_wikidata_org_prop_direct_p279('applied_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('cartesian_tensor', 'tensor').
http___www_wikidata_org_prop_direct_p279('tensor', 'mathematical_object').
http___www_wikidata_org_prop_direct_p279('cartesian_tensor', 'tensor').
http___www_wikidata_org_prop_direct_p279('tensor', 'multilinear_map').
http___www_wikidata_org_prop_direct_p279('computational_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('computational_mathematics', 'computational_science').
http___www_wikidata_org_prop_direct_p279('computational_science', 'applied_mathematics').
http___www_wikidata_org_prop_direct_p279('computational_mathematics', 'computational_science').
http___www_wikidata_org_prop_direct_p279('computational_science', 'computer_science').
http___www_wikidata_org_prop_direct_p279('computational_science', 'applied_mathematics').
http___www_wikidata_org_prop_direct_p279('applied_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('computational_science', 'computer_science').
http___www_wikidata_org_prop_direct_p279('computer_science', 'formal_science').
http___www_wikidata_org_prop_direct_p279('counting', 'quantification').
http___www_wikidata_org_prop_direct_p279('quantification', 'planned_process').
http___www_wikidata_org_prop_direct_p279('counting', 'finding').
http___www_wikidata_org_prop_direct_p279('finding', 'occurrence').
http___www_wikidata_org_prop_direct_p279('counting', 'finding').
http___www_wikidata_org_prop_direct_p279('finding', 'activity').
http___www_wikidata_org_prop_direct_p279('cryptanalysis', 'applied_mathematics').
http___www_wikidata_org_prop_direct_p279('applied_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('cryptography', 'technique').
http___www_wikidata_org_prop_direct_p279('technique', 'method').
http___www_wikidata_org_prop_direct_p279('cryptography', 'technique').
http___www_wikidata_org_prop_direct_p279('technique', 'activity').
http___www_wikidata_org_prop_direct_p279('cryptography', 'security_engineering').
http___www_wikidata_org_prop_direct_p279('security_engineering', 'engineering').
http___www_wikidata_org_prop_direct_p279('cryptography', 'security_engineering').
http___www_wikidata_org_prop_direct_p279('security_engineering', 'computer_science').
http___www_wikidata_org_prop_direct_p279('engineering_mathematics', 'engineering').
http___www_wikidata_org_prop_direct_p279('engineering', 'applied_science').
http___www_wikidata_org_prop_direct_p279('engineering_mathematics', 'applied_mathematics').
http___www_wikidata_org_prop_direct_p279('applied_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('geodesy', 'earth_science').
http___www_wikidata_org_prop_direct_p279('earth_science', 'natural_science').
http___www_wikidata_org_prop_direct_p279('integrable_algorithm', 'integrable_system').
http___www_wikidata_org_prop_direct_p279('integrable_system', 'mathematical_problem').
http___www_wikidata_org_prop_direct_p279('integrable_algorithm', 'integrable_system').
http___www_wikidata_org_prop_direct_p279('integrable_system', 'physical_system').
http___www_wikidata_org_prop_direct_p279('integrable_algorithm', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'work').
http___www_wikidata_org_prop_direct_p279('integrable_algorithm', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'procedure').
http___www_wikidata_org_prop_direct_p279('k_mer', 'n_gram').
http___www_wikidata_org_prop_direct_p279('n_gram', 'string').
http___www_wikidata_org_prop_direct_p279('least_squares_spectral_analysis', 'harmonic_analysis').
http___www_wikidata_org_prop_direct_p279('harmonic_analysis', 'data_analysis').
http___www_wikidata_org_prop_direct_p279('mathematical_engineering', 'engineering').
http___www_wikidata_org_prop_direct_p279('engineering', 'applied_science').
http___www_wikidata_org_prop_direct_p279('mathematical_linguistics', 'linguistics').
http___www_wikidata_org_prop_direct_p279('linguistics', 'social_science').
http___www_wikidata_org_prop_direct_p279('mathematical_linguistics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematics', 'natural_science').
http___www_wikidata_org_prop_direct_p279('mathematical_linguistics', 'linguistics').
http___www_wikidata_org_prop_direct_p279('linguistics', 'humanities').
http___www_wikidata_org_prop_direct_p279('mathematical_methods_in_electronics', 'applied_mathematics').
http___www_wikidata_org_prop_direct_p279('applied_mathematics', 'mathematics').
http___www_wikidata_org_prop_direct_p279('mathematical_methods_in_electronics', 'method').
http___www_wikidata_org_prop_direct_p279('method', 'means').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'model').
http___www_wikidata_org_prop_direct_p279('model', 'information').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'intellectual_work').
http___www_wikidata_org_prop_direct_p279('intellectual_work', 'work').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'conceptual_model').
http___www_wikidata_org_prop_direct_p279('conceptual_model', 'knowledge_organization_system').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'scientific_model').
http___www_wikidata_org_prop_direct_p279('scientific_model', 'conceptual_model').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'mathematical_object').
http___www_wikidata_org_prop_direct_p279('mathematical_object', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'model').
http___www_wikidata_org_prop_direct_p279('model', 'artificial_object').
http___www_wikidata_org_prop_direct_p279('mathematical_model', 'mathematical_object').
http___www_wikidata_org_prop_direct_p279('mathematical_object', 'abstract_entity').
http___www_wikidata_org_prop_direct_p279('mathematical_psychology', 'psychology').
http___www_wikidata_org_prop_direct_p279('psychology', 'behavioral_sciences').
http___www_wikidata_org_prop_direct_p279('mathematical_psychology', 'psychology').
http___www_wikidata_org_prop_direct_p279('psychology', 'health_sciences').
http___www_wikidata_org_prop_direct_p279('mathematical_psychology', 'psychology').
http___www_wikidata_org_prop_direct_p279('psychology', 'human_science').
http___www_wikidata_org_prop_direct_p279('mathematical_sciences', 'academic_discipline').
http___www_wikidata_org_prop_direct_p279('academic_discipline', 'field_of_study').
http___www_wikidata_org_prop_direct_p279('numerical_weather_prediction', 'computer_simulation').
http___www_wikidata_org_prop_direct_p279('computer_simulation', 'simulation').
http___www_wikidata_org_prop_direct_p279('numerical_weather_prediction', 'numerical_simulation').
http___www_wikidata_org_prop_direct_p279('numerical_simulation', 'computer_simulation').
http___www_wikidata_org_prop_direct_p279('overfitting', 'curve_fitting').
http___www_wikidata_org_prop_direct_p279('curve_fitting', 'approximation').
http___www_wikidata_org_prop_direct_p279('overfitting', 'error').
http___www_wikidata_org_prop_direct_p279('error', 'error').
http___www_wikidata_org_prop_direct_p279('overfitting', 'error').
http___www_wikidata_org_prop_direct_p279('error', 'human_activity').
http___www_wikidata_org_prop_direct_p279('patterns_in_nature', 'scientific_law').
http___www_wikidata_org_prop_direct_p279('scientific_law', 'universal_law').
http___www_wikidata_org_prop_direct_p279('patterns_in_nature', 'pattern').
http___www_wikidata_org_prop_direct_p279('pattern', 'regularity').
http___www_wikidata_org_prop_direct_p279('phase_boundary', 'physical_interface').
http___www_wikidata_org_prop_direct_p279('physical_interface', 'interface').
http___www_wikidata_org_prop_direct_p279('phase_boundary', 'physical_interface').
http___www_wikidata_org_prop_direct_p279('physical_interface', 'concrete_object').
http___www_wikidata_org_prop_direct_p279('scale_analysis__mathematics_', 'estimation').
http___www_wikidata_org_prop_direct_p279('estimation', 'reasoning').
http___www_wikidata_org_prop_direct_p279('scale_analysis__mathematics_', 'estimation').
http___www_wikidata_org_prop_direct_p279('estimation', 'technique').
http___www_wikidata_org_prop_direct_p279('scale_analysis__mathematics_', 'estimation').
http___www_wikidata_org_prop_direct_p279('estimation', 'procedure').
http___www_wikidata_org_prop_direct_p279('scale_analysis__mathematics_', 'estimation').
http___www_wikidata_org_prop_direct_p279('estimation', 'finding').
http___www_wikidata_org_prop_direct_p279('scale_analysis__mathematics_', 'approximation').
http___www_wikidata_org_prop_direct_p279('approximation', 'method').
http___www_wikidata_org_prop_direct_p279('scale_analysis__mathematics_', 'approximation').
http___www_wikidata_org_prop_direct_p279('approximation', 'decimal_representation').
http___www_wikidata_org_prop_direct_p279('self_consistent_mean_field__biology_', 'mean_field_theory').
http___www_wikidata_org_prop_direct_p279('mean_field_theory', 'approximation_theory').
http___www_wikidata_org_prop_direct_p279('social_choice_theory', 'theory').
http___www_wikidata_org_prop_direct_p279('theory', 'idea').
http___www_wikidata_org_prop_direct_p279('spirangle', 'spiral').
http___www_wikidata_org_prop_direct_p279('spiral', 'curve').
http___www_wikidata_org_prop_direct_p279('spirangle', 'polygonal_chain').
http___www_wikidata_org_prop_direct_p279('polygonal_chain', 'geometric_shape').
http___www_wikidata_org_prop_direct_p279('system_equivalence', 'approximately_equal_to').
http___www_wikidata_org_prop_direct_p279('approximately_equal_to', 'binary_relation').
http___www_wikidata_org_prop_direct_p279('uncertainty_quantification', 'uncertainty_analysis').
http___www_wikidata_org_prop_direct_p279('uncertainty_analysis', 'analysis').
http___www_wikidata_org_prop_direct_p279('uncertainty_quantification', 'uncertainty_analysis').
http___www_wikidata_org_prop_direct_p279('uncertainty_analysis', 'risk_analysis').
http___www_wikidata_org_prop_direct_p279('vibration', 'periodic_motion').
http___www_wikidata_org_prop_direct_p279('periodic_motion', 'oscillation').
http___www_wikidata_org_prop_direct_p279('vibration', 'periodic_motion').
http___www_wikidata_org_prop_direct_p279('periodic_motion', 'motion').
http___www_wikidata_org_prop_direct_p279('vector_spherical_harmonics', 'special_function').
http___www_wikidata_org_prop_direct_p279('special_function', 'function').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'researcher').
http___www_wikidata_org_prop_direct_p279('mathematician', 'scientist').
http___www_wikidata_org_prop_direct_p279('scientist', 'scholar').
http___www_wikidata_org_prop_direct_p279('krieger_nelson_prize', 'award_honoring_women').
http___www_wikidata_org_prop_direct_p279('award_honoring_women', 'award').
http___www_wikidata_org_prop_direct_p279('ruth_lyttle_satter_prize_in_mathematics', 'award_honoring_women').
http___www_wikidata_org_prop_direct_p279('award_honoring_women', 'award').
http___www_wikidata_org_prop_direct_p279('women_in_stem', 'group_of_humans').
http___www_wikidata_org_prop_direct_p279('group_of_humans', 'group_or_class_of_humans').
http___www_wikidata_org_prop_direct_p279('women_in_stem', 'group_of_humans').
http___www_wikidata_org_prop_direct_p279('group_of_humans', 'group_of_persons').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'work').
http___www_wikidata_org_prop_direct_p279('divisibility_rule', 'algorithm').
http___www_wikidata_org_prop_direct_p279('algorithm', 'procedure').
http___www_wikidata_org_prop_direct_p279('highly_composite_number', 'positive_integer').
http___www_wikidata_org_prop_direct_p279('positive_integer', 'positive_real_number').
http___www_wikidata_org_prop_direct_p279('highly_composite_number', 'positive_integer').
http___www_wikidata_org_prop_direct_p279('positive_integer', 'non_negative_integer').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'operation_result').
http___www_wikidata_org_prop_direct_p279('sums_of_powers', 'sum').
http___www_wikidata_org_prop_direct_p279('sum', 'weighted_sum').
http___www_wikidata_org_prop_direct_p279('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
http___www_wikidata_org_prop_direct_p279('uniform_tiling', 'uniform_tessellation').
http___www_wikidata_org_prop_direct_p279('anamorphosis', 'image').
http___www_wikidata_org_prop_direct_p279('image', 'two_dimensional_object').
http___www_wikidata_org_prop_direct_p279('anamorphosis', 'projection').
http___www_wikidata_org_prop_direct_p279('projection', 'visual_artwork').
http___www_wikidata_org_prop_direct_p279('anamorphosis', 'image').
http___www_wikidata_org_prop_direct_p279('image', 'artificial_object').
http___www_wikidata_org_prop_direct_p31('pure_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
http___www_wikidata_org_prop_direct_p31('comparison', 'method').
http___www_wikidata_org_prop_direct_p31('table_of_divisors', 'table').
http___www_wikidata_org_prop_direct_p31('table', 'data_visualization').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation_group_according_to_isco_08').
http___www_wikidata_org_prop_direct_p31('occupation_group_according_to_isco_08', 'job_classification_system').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'concept').
http___www_wikidata_org_prop_direct_p31('nicholas_a__m__monk', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('harold_ramkissoon', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('pure_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
http___www_wikidata_org_prop_direct_p31('comparison', 'method').
http___www_wikidata_org_prop_direct_p31('table_of_divisors', 'table').
http___www_wikidata_org_prop_direct_p31('table', 'data_visualization').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation_group_according_to_isco_08').
http___www_wikidata_org_prop_direct_p31('occupation_group_according_to_isco_08', 'job_classification_system').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'concept').
http___www_wikidata_org_prop_direct_p31('nicholas_a__m__monk', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('harold_ramkissoon', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('pure_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('applied_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('asymptotology', 'mathematical_theory').
http___www_wikidata_org_prop_direct_p31('mathematical_theory', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('george_david_birkhoff_prize', 'award').
http___www_wikidata_org_prop_direct_p31('award', 'first_order_class').
http___www_wikidata_org_prop_direct_p31('computational_mathematics', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'classification_scheme').
http___www_wikidata_org_prop_direct_p31('computational_mathematics', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('cryptanalysis', 'field_of_study').
http___www_wikidata_org_prop_direct_p31('field_of_study', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('cryptography', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('discrete_calculus', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'classification_scheme').
http___www_wikidata_org_prop_direct_p31('discrete_calculus', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('engineering_mathematics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('engineering_mathematics', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'classification_scheme').
http___www_wikidata_org_prop_direct_p31('engineering_mathematics', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('geodesy', 'industry').
http___www_wikidata_org_prop_direct_p31('industry', 'economic_concept').
http___www_wikidata_org_prop_direct_p31('geodesy', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('geometric_calculus', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'classification_scheme').
http___www_wikidata_org_prop_direct_p31('geometric_calculus', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('german_tank_problem', 'mathematical_problem').
http___www_wikidata_org_prop_direct_p31('mathematical_problem', 'type_of_problem').
http___www_wikidata_org_prop_direct_p31('international_council_for_industrial_and_applied_mathematics', 'organization').
http___www_wikidata_org_prop_direct_p31('organization', 'social_science_concept').
http___www_wikidata_org_prop_direct_p31('journal_of_computational_and_applied_mathematics', 'scientific_journal').
http___www_wikidata_org_prop_direct_p31('scientific_journal', 'magazine_genre').
http___www_wikidata_org_prop_direct_p31('bart_kosko', 'human').
http___www_wikidata_org_prop_direct_p31('human', 'organisms_known_by_a_particular_common_name').
http___www_wikidata_org_prop_direct_p31('mathematical_engineering', 'branch_of_engineering').
http___www_wikidata_org_prop_direct_p31('branch_of_engineering', 'class_of_parts').
http___www_wikidata_org_prop_direct_p31('mathematical_engineering', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('mathematical_sociology', 'branch_of_sociology').
http___www_wikidata_org_prop_direct_p31('branch_of_sociology', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematical_sociology', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'classification_scheme').
http___www_wikidata_org_prop_direct_p31('mathematical_sociology', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematics_and_art', 'relation').
http___www_wikidata_org_prop_direct_p31('relation', 'type_of_property').
http___www_wikidata_org_prop_direct_p31('mathematics_and_art', 'relation').
http___www_wikidata_org_prop_direct_p31('relation', 'type_of_object').
http___www_wikidata_org_prop_direct_p31('mohr_coulomb_theory', 'failure_criterion').
http___www_wikidata_org_prop_direct_p31('failure_criterion', 'physical_law').
http___www_wikidata_org_prop_direct_p31('numerical_weather_prediction', 'meteorology').
http___www_wikidata_org_prop_direct_p31('meteorology', 'branch_of_science').
http___www_wikidata_org_prop_direct_p31('numerical_weather_prediction', 'meteorology').
http___www_wikidata_org_prop_direct_p31('meteorology', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('olga__technology_', 'software').
http___www_wikidata_org_prop_direct_p31('software', 'product_category').
http___www_wikidata_org_prop_direct_p31('olga__technology_', 'software').
http___www_wikidata_org_prop_direct_p31('software', 'type_of_tool').
http___www_wikidata_org_prop_direct_p31('overfitting', 'concept').
http___www_wikidata_org_prop_direct_p31('concept', 'variable_order_class').
http___www_wikidata_org_prop_direct_p31('postage_stamp_problem', 'mathematical_problem').
http___www_wikidata_org_prop_direct_p31('mathematical_problem', 'type_of_problem').
http___www_wikidata_org_prop_direct_p31('potterswheel', 'programming_language').
http___www_wikidata_org_prop_direct_p31('programming_language', 'computer_science_term').
http___www_wikidata_org_prop_direct_p31('probabilistic_numerics', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('scale_analysis__mathematics_', 'heuristic').
http___www_wikidata_org_prop_direct_p31('heuristic', 'problem_solving_approach').
http___www_wikidata_org_prop_direct_p31('social_choice_theory', 'academic_discipline').
http___www_wikidata_org_prop_direct_p31('academic_discipline', 'knowledge_classification').
http___www_wikidata_org_prop_direct_p31('subdivision_bifiltration', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('mathematical_concept', 'variable_order_class').
http___www_wikidata_org_prop_direct_p31('topological_data_analysis', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'classification_scheme').
http___www_wikidata_org_prop_direct_p31('topological_data_analysis', 'area_of_mathematics').
http___www_wikidata_org_prop_direct_p31('area_of_mathematics', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('weber_problem', 'mathematical_problem').
http___www_wikidata_org_prop_direct_p31('mathematical_problem', 'type_of_problem').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation_group_according_to_isco_08').
http___www_wikidata_org_prop_direct_p31('occupation_group_according_to_isco_08', 'job_classification_system').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'metaclass').
http___www_wikidata_org_prop_direct_p31('mathematician', 'profession').
http___www_wikidata_org_prop_direct_p31('profession', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('mathematician', 'occupation').
http___www_wikidata_org_prop_direct_p31('occupation', 'concept').
http___www_wikidata_org_prop_direct_p31('timeline_of_women_in_mathematics_in_the_united_states', 'aspect_in_a_geographic_region').
http___www_wikidata_org_prop_direct_p31('aspect_in_a_geographic_region', 'metaclass').
http___www_wikidata_org_prop_direct_p31('african_women_in_mathematics_association', 'women_s_organization').
http___www_wikidata_org_prop_direct_p31('women_s_organization', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('african_women_in_mathematics_association', 'organization').
http___www_wikidata_org_prop_direct_p31('organization', 'social_science_concept').
http___www_wikidata_org_prop_direct_p31('anne_bennett_prize', 'mathematics_award').
http___www_wikidata_org_prop_direct_p31('mathematics_award', 'type_of_award').
http___www_wikidata_org_prop_direct_p31('association_for_women_in_mathematics', 'women_s_organization').
http___www_wikidata_org_prop_direct_p31('women_s_organization', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('association_for_women_in_mathematics', 'professional_association').
http___www_wikidata_org_prop_direct_p31('professional_association', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('association_for_women_in_mathematics_newsletter', 'scientific_journal').
http___www_wikidata_org_prop_direct_p31('scientific_journal', 'magazine_genre').
http___www_wikidata_org_prop_direct_p31('caucus_for_women_in_statistics_and_data_science', 'regulatory_college').
http___www_wikidata_org_prop_direct_p31('regulatory_college', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('complexities__women_in_mathematics', 'version__edition_or_translation').
http___www_wikidata_org_prop_direct_p31('version__edition_or_translation', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('complexities__women_in_mathematics', 'version__edition_or_translation').
http___www_wikidata_org_prop_direct_p31('version__edition_or_translation', 'item').
http___www_wikidata_org_prop_direct_p31('european_women_in_mathematics', 'organization').
http___www_wikidata_org_prop_direct_p31('organization', 'social_science_concept').
http___www_wikidata_org_prop_direct_p31('femmes_et_math_matiques', 'organization').
http___www_wikidata_org_prop_direct_p31('organization', 'social_science_concept').
http___www_wikidata_org_prop_direct_p31('graduate_women_in_science', 'women_s_organization').
http___www_wikidata_org_prop_direct_p31('women_s_organization', 'type_of_organization').
http___www_wikidata_org_prop_direct_p31('graduate_women_in_science', '501_c__3__organization').
http___www_wikidata_org_prop_direct_p31('501_c__3__organization', 'tax_status').
http___www_wikidata_org_prop_direct_p31('graduate_women_in_science', '501_c__3__organization').
http___www_wikidata_org_prop_direct_p31('501_c__3__organization', 'legal_form').
http___www_wikidata_org_prop_direct_p31('hidden_figures__book_', 'non_fiction_novel').
http___www_wikidata_org_prop_direct_p31('non_fiction_novel', 'novel_genre').
http___www_wikidata_org_prop_direct_p31('krieger_nelson_prize', 'science_award').
http___www_wikidata_org_prop_direct_p31('science_award', 'type_of_award').
http___www_wikidata_org_prop_direct_p31('krieger_nelson_prize', 'award').
http___www_wikidata_org_prop_direct_p31('award', 'first_order_class').
http___www_wikidata_org_prop_direct_p31('noether_lecture', 'mathematics_award').
http___www_wikidata_org_prop_direct_p31('mathematics_award', 'type_of_award').
http___www_wikidata_org_prop_direct_p31('noether_lecture', 'named_lecture').
http___www_wikidata_org_prop_direct_p31('named_lecture', 'convention').
http___www_wikidata_org_prop_direct_p31('noether_lecture', 'named_lecture').
http___www_wikidata_org_prop_direct_p31('named_lecture', 'lecture').
http___www_wikidata_org_prop_direct_p31('noether_lecture', 'lecture_series').
http___www_wikidata_org_prop_direct_p31('lecture_series', 'type_of_award').
http___www_wikidata_org_prop_direct_p31('pioneering_women_in_american_mathematics', 'written_work').
http___www_wikidata_org_prop_direct_p31('written_work', 'collective_noun').
http___www_wikidata_org_prop_direct_p31('power_in_numbers__the_rebel_women_of_mathematics', 'written_work').
http___www_wikidata_org_prop_direct_p31('written_work', 'collective_noun').
http___www_wikidata_org_prop_direct_p31('ruth_lyttle_satter_prize_in_mathematics', 'mathematics_award').
http___www_wikidata_org_prop_direct_p31('mathematics_award', 'type_of_award').
http___www_wikidata_org_prop_direct_p31('women_in_mathematics__book_', 'book').
http___www_wikidata_org_prop_direct_p31('book', 'type_of_mass_media').
http___www_wikidata_org_prop_direct_p31('women_in_mathematics__book_', 'book').
http___www_wikidata_org_prop_direct_p31('book', 'type_of_publication').
http___www_wikidata_org_prop_direct_p31('trisatika', 'written_work').
http___www_wikidata_org_prop_direct_p31('written_work', 'collective_noun').
http___www_wikidata_org_prop_direct_p31('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
http___www_wikidata_org_prop_direct_p31('comparison', 'method').
http___www_wikidata_org_prop_direct_p31('table_of_divisors', 'table').
http___www_wikidata_org_prop_direct_p31('table', 'data_visualization').
http___www_wikidata_org_prop_direct_p31('highly_composite_number', 'type_of_integer').
http___www_wikidata_org_prop_direct_p31('type_of_integer', 'second_order_class').
http___www_wikidata_org_prop_direct_p31('karp_s_21_np_complete_problems', 'set').
http___www_wikidata_org_prop_direct_p31('set', 'mathematical_concept').
http___www_wikidata_org_prop_direct_p31('mathematics_and_art', 'relation').
http___www_wikidata_org_prop_direct_p31('relation', 'type_of_property').
http___www_wikidata_org_prop_direct_p31('mathematics_and_art', 'relation').
http___www_wikidata_org_prop_direct_p31('relation', 'type_of_object').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'lisa_willis').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'mae_woods').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'trevor_graham').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'christopher_hornsby').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'lisa_willis').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'mae_woods').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'trevor_graham').
http___www_wikidata_org_prop_direct_p185('nicholas_a__m__monk', 'karen_mary_page').
http___www_wikidata_org_prop_direct_p185('karen_mary_page', 'christopher_hornsby').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'michael_fisher').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'cyril_domb').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'michael_fisher').
http___www_wikidata_org_prop_direct_p184('nicholas_a__m__monk', 'basil_j__hiley').
http___www_wikidata_org_prop_direct_p184('basil_j__hiley', 'cyril_domb').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'mathematician').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'woman').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'mathematician').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'woman').
http___www_wikidata_org_prop_direct_p1269('mathematical_model', 'mathematics').
http___www_wikidata_org_prop_direct_p1269('mathematics', 'mathematics_education').
http___www_wikidata_org_prop_direct_p1269('patterns_in_nature', 'auto_organisation').
http___www_wikidata_org_prop_direct_p1269('auto_organisation', 'self_healing_material').
http___www_wikidata_org_prop_direct_p1269('patterns_in_nature', 'auto_organisation').
http___www_wikidata_org_prop_direct_p1269('auto_organisation', 'positive_feedback').
http___www_wikidata_org_prop_direct_p1269('patterns_in_nature', 'auto_organisation').
http___www_wikidata_org_prop_direct_p1269('auto_organisation', 'social_science').
http___www_wikidata_org_prop_direct_p1269('uncertainty_quantification', 'uncertainty').
http___www_wikidata_org_prop_direct_p1269('uncertainty', 'epistemology').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'mathematician').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'woman').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'mathematician').
http___www_wikidata_org_prop_direct_p1269('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
http___www_wikidata_org_prop_direct_p1269('women_in_mathematics', 'woman').
http___www_wikidata_org_prop_direct_p1269('women_in_stem', 'occupational_segregation').
http___www_wikidata_org_prop_direct_p1269('occupational_segregation', 'gender_role').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'software').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'software').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'software').
subclass_of('pure_mathematics', 'mathematics').
subclass_of('mathematics', 'natural_science').
subclass_of('pure_mathematics', 'basic_research').
subclass_of('basic_research', 'research').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'work').
subclass_of('divisibility_rule', 'algorithm').
subclass_of('algorithm', 'procedure').
subclass_of('highly_composite_number', 'positive_integer').
subclass_of('positive_integer', 'non_negative_integer').
subclass_of('highly_composite_number', 'positive_integer').
subclass_of('positive_integer', 'positive_real_number').
subclass_of('sums_of_powers', 'sum').
subclass_of('sum', 'weighted_sum').
subclass_of('sums_of_powers', 'sum').
subclass_of('sum', 'operation_result').
subclass_of('uniform_tilings_in_hyperbolic_plane', 'uniform_tiling').
subclass_of('uniform_tiling', 'uniform_tessellation').
subclass_of('mathematician', 'scientist').
subclass_of('scientist', 'researcher').
subclass_of('mathematician', 'scientist').
subclass_of('scientist', 'scholar').
subclass_of('krieger_nelson_prize', 'award_honoring_women').
subclass_of('award_honoring_women', 'award').
subclass_of('ruth_lyttle_satter_prize_in_mathematics', 'award_honoring_women').
subclass_of('award_honoring_women', 'award').
subclass_of('women_in_stem', 'group_of_humans').
subclass_of('group_of_humans', 'group_of_persons').
subclass_of('women_in_stem', 'group_of_humans').
subclass_of('group_of_humans', 'group_or_class_of_humans').
subclass_of('anamorphosis', 'image').
subclass_of('image', 'artificial_object').
subclass_of('anamorphosis', 'image').
subclass_of('image', 'two_dimensional_object').
subclass_of('anamorphosis', 'projection').
subclass_of('projection', 'visual_artwork').
subclass_of('mathematical_beauty', 'beauty').
subclass_of('beauty', 'convention').
subclass_of('mathematical_beauty', 'beauty').
subclass_of('beauty', 'value').
subclass_of('mathematics_of_paper_folding', 'mathematics').
subclass_of('mathematics', 'natural_science').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('pure_mathematics', 'academic_discipline').
instance_of('academic_discipline', 'knowledge_classification').
instance_of('comparison_of_vector_algebra_and_geometric_algebra', 'comparison').
instance_of('comparison', 'method').
instance_of('table_of_divisors', 'table').
instance_of('table', 'data_visualization').
instance_of('highly_composite_number', 'type_of_integer').
instance_of('type_of_integer', 'second_order_class').
instance_of('karp_s_21_np_complete_problems', 'set').
instance_of('set', 'mathematical_concept').
instance_of('mathematician', 'occupation_group_according_to_isco_08').
instance_of('occupation_group_according_to_isco_08', 'job_classification_system').
instance_of('mathematician', 'occupation').
instance_of('occupation', 'second_order_class').
instance_of('mathematician', 'profession').
instance_of('profession', 'metaclass').
instance_of('mathematician', 'profession').
instance_of('profession', 'second_order_class').
instance_of('mathematician', 'occupation').
instance_of('occupation', 'concept').
instance_of('hideki_omori', 'human').
instance_of('human', 'organisms_known_by_a_particular_common_name').
instance_of('timeline_of_women_in_mathematics_in_the_united_states', 'aspect_in_a_geographic_region').
instance_of('aspect_in_a_geographic_region', 'metaclass').
instance_of('african_women_in_mathematics_association', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('african_women_in_mathematics_association', 'women_s_organization').
instance_of('women_s_organization', 'type_of_organization').
instance_of('anne_bennett_prize', 'mathematics_award').
instance_of('mathematics_award', 'type_of_award').
instance_of('association_for_women_in_mathematics', 'professional_association').
instance_of('professional_association', 'type_of_organization').
instance_of('association_for_women_in_mathematics', 'women_s_organization').
instance_of('women_s_organization', 'type_of_organization').
instance_of('association_for_women_in_mathematics_newsletter', 'scientific_journal').
instance_of('scientific_journal', 'magazine_genre').
instance_of('caucus_for_women_in_statistics_and_data_science', 'regulatory_college').
instance_of('regulatory_college', 'type_of_organization').
instance_of('complexities__women_in_mathematics', 'version__edition_or_translation').
instance_of('version__edition_or_translation', 'item').
instance_of('complexities__women_in_mathematics', 'version__edition_or_translation').
instance_of('version__edition_or_translation', 'second_order_class').
instance_of('european_women_in_mathematics', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('femmes_et_math_matiques', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('graduate_women_in_science', '501_c__3__organization').
instance_of('501_c__3__organization', 'legal_form').
instance_of('graduate_women_in_science', '501_c__3__organization').
instance_of('501_c__3__organization', 'tax_status').
instance_of('graduate_women_in_science', 'women_s_organization').
instance_of('women_s_organization', 'type_of_organization').
instance_of('hidden_figures__book_', 'non_fiction_novel').
instance_of('non_fiction_novel', 'novel_genre').
instance_of('krieger_nelson_prize', 'award').
instance_of('award', 'first_order_class').
instance_of('krieger_nelson_prize', 'science_award').
instance_of('science_award', 'type_of_award').
instance_of('noether_lecture', 'named_lecture').
instance_of('named_lecture', 'convention').
instance_of('noether_lecture', 'named_lecture').
instance_of('named_lecture', 'lecture').
instance_of('noether_lecture', 'mathematics_award').
instance_of('mathematics_award', 'type_of_award').
instance_of('noether_lecture', 'lecture_series').
instance_of('lecture_series', 'type_of_award').
instance_of('pioneering_women_in_american_mathematics', 'written_work').
instance_of('written_work', 'collective_noun').
instance_of('power_in_numbers__the_rebel_women_of_mathematics', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('power_in_numbers__the_rebel_women_of_mathematics', 'book').
instance_of('book', 'type_of_publication').
instance_of('ruth_lyttle_satter_prize_in_mathematics', 'mathematics_award').
instance_of('mathematics_award', 'type_of_award').
instance_of('women_in_mathematics__book_', 'book').
instance_of('book', 'type_of_mass_media').
instance_of('women_in_mathematics__book_', 'book').
instance_of('book', 'type_of_publication').
instance_of('trisatika', 'written_work').
instance_of('written_work', 'collective_noun').
instance_of('mathematics_and_art', 'relation').
instance_of('relation', 'type_of_property').
instance_of('mathematics_and_art', 'relation').
instance_of('relation', 'type_of_object').
instance_of('sarah_marie_belcastro', 'human').
instance_of('human', 'organisms_known_by_a_particular_common_name').
instance_of('the_bridges_organization', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('equals_pi', 'painting').
instance_of('painting', 'type_of_work_of_art').
instance_of('fourth_dimension_in_art', 'art_genre').
instance_of('art_genre', 'metaclass').
instance_of('golden_ratio', 'metallic_ratio').
instance_of('metallic_ratio', 'sequence_of_real_numbers').
instance_of('golden_ratio', 'irrational_number').
instance_of('irrational_number', 'type_of_number').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('periodical', 'type_of_mass_media').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('periodical', 'type_of_publication').
instance_of('journal_of_mathematics_and_the_arts', 'periodical').
instance_of('periodical', 'form_of_creative_work').
instance_of('mathemalchemy', 'organization').
instance_of('organization', 'social_science_concept').
instance_of('a_new_kind_of_science', 'written_work').
instance_of('written_work', 'collective_noun').
instance_of('potterswheel', 'visual_programming_language').
instance_of('visual_programming_language', 'q116481801').
instance_of('potterswheel', 'visual_programming_language').
instance_of('visual_programming_language', 'q116481801').
sibling('hideki_omori', 'akemi__mori').
sibling('akemi__mori', 'rei__mori').
sibling('hideki_omori', 'rei__mori').
sibling('rei__mori', 'akemi__mori').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('women_in_mathematics', 'mathematician').
facet_of('timeline_of_women_in_mathematics', 'women_in_mathematics').
facet_of('women_in_mathematics', 'woman').
facet_of('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
facet_of('women_in_mathematics', 'mathematician').
facet_of('timeline_of_women_in_mathematics_in_the_united_states', 'women_in_mathematics').
facet_of('women_in_mathematics', 'woman').
facet_of('women_in_stem', 'occupational_segregation').
facet_of('occupational_segregation', 'gender_role').
facet_of('mathematical_beauty', 'mathematics').
facet_of('mathematics', 'mathematics_education').
facet_of('patterns_in_nature', 'auto_organisation').
facet_of('auto_organisation', 'q2377063').
facet_of('patterns_in_nature', 'auto_organisation').
facet_of('auto_organisation', 'q2377063').
country('timeline_of_women_in_mathematics_in_the_united_states', 'united_states').
country('united_states', 'united_states').
country('association_for_women_in_mathematics', 'united_states').
country('united_states', 'united_states').
country('center_for_women_in_mathematics', 'united_states').
country('united_states', 'united_states').
country('european_women_in_mathematics', 'finland').
country('finland', 'finland').
country('femmes_et_math_matiques', 'france').
country('france', 'france').
country('graduate_women_in_science', 'united_states').
country('united_states', 'united_states').
country('krieger_nelson_prize', 'canada').
country('canada', 'canada').
country('noether_lecture', 'united_states').
country('united_states', 'united_states').
located_in_the_administrative_territorial_entity('association_for_women_in_mathematics', 'fairfax').
located_in_the_administrative_territorial_entity('fairfax', 'virginia').
located_in_the_administrative_territorial_entity('graduate_women_in_science', 'minneapolis').
located_in_the_administrative_territorial_entity('minneapolis', 'hennepin_county').
member_of('european_women_in_mathematics', 'european_mathematical_society').
member_of('european_mathematical_society', 'european_open_science_cloud_association').
distributed_by('hidden_figures', 'netflix').
distributed_by('netflix', 'app_store').
distributed_by('hidden_figures', 'netflix').
distributed_by('netflix', 'google_play').
distributed_by('hidden_figures', 'itunes').
distributed_by('itunes', 'microsoft_store').
named_after('fermat_kitchen', 'fermat_s_last_theorem').
named_after('fermat_s_last_theorem', 'pierre_de_fermat').
intended_public('fermat_kitchen', 'sh_nen').
intended_public('sh_nen', 'boy').
intended_public('science_fell_in_love__so_i_tried_to_prove_it', 'seinen').
intended_public('seinen', 'teenager').
intended_public('s_gaku_golden', 'seinen').
intended_public('seinen', 'teenager').
intended_public('s_ji_de_asobo', 'josei').
intended_public('josei', 'woman').
doctoral_advisor('sarah_marie_belcastro', 'igor_dolgachev').
doctoral_advisor('igor_dolgachev', 'igor_shafarevich').
different_from('golden_ratio', 'golden_rule').
different_from('golden_rule', 'lei__urea').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'beauty').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'delicacy').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'simplicity').
partially_coincident_with('mathematical_beauty', 'elegance').
partially_coincident_with('elegance', 'parsimony').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'numerical_analysis').
http___www_wikidata_org_prop_direct_p527('numerical_analysis', 'validated_numerics').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'numerical_analysis').
http___www_wikidata_org_prop_direct_p527('numerical_analysis', 'integrable_algorithm').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'cryptology').
http___www_wikidata_org_prop_direct_p527('cryptology', 'cryptography').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'numerical_analysis').
http___www_wikidata_org_prop_direct_p527('numerical_analysis', 'mathematical_optimization').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'numerical_analysis').
http___www_wikidata_org_prop_direct_p527('numerical_analysis', 'eigenvalue_algorithm').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'numerical_analysis').
http___www_wikidata_org_prop_direct_p527('numerical_analysis', 'numerical_linear_algebra').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'numerical_analysis').
http___www_wikidata_org_prop_direct_p527('numerical_analysis', 'numerical_method_for_ordinary_differential_equations').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'cryptology').
http___www_wikidata_org_prop_direct_p527('cryptology', 'cryptanalysis').
http___www_wikidata_org_prop_direct_p527('applied_mathematics', 'graph_theory').
http___www_wikidata_org_prop_direct_p527('graph_theory', 'network_theory').
http___www_wikidata_org_prop_direct_p17('basque_center_for_applied_mathematics', 'spain').
http___www_wikidata_org_prop_direct_p17('spain', 'spain').
http___www_wikidata_org_prop_direct_p17('japan_society_for_industrial_and_applied_mathematics', 'japan').
http___www_wikidata_org_prop_direct_p17('japan', 'japan').
http___www_wikidata_org_prop_direct_p17('neuromat', 'brazil').
http___www_wikidata_org_prop_direct_p17('brazil', 'brazil').
http___www_wikidata_org_prop_direct_p17('seminar_for_applied_mathematics', 'switzerland').
http___www_wikidata_org_prop_direct_p17('switzerland', 'switzerland').
http___www_wikidata_org_prop_direct_p17('timeline_of_women_in_mathematics_in_the_united_states', 'united_states').
http___www_wikidata_org_prop_direct_p17('united_states', 'united_states').
http___www_wikidata_org_prop_direct_p17('association_for_women_in_mathematics', 'united_states').
http___www_wikidata_org_prop_direct_p17('united_states', 'united_states').
http___www_wikidata_org_prop_direct_p17('center_for_women_in_mathematics', 'united_states').
http___www_wikidata_org_prop_direct_p17('united_states', 'united_states').
http___www_wikidata_org_prop_direct_p17('european_women_in_mathematics', 'finland').
http___www_wikidata_org_prop_direct_p17('finland', 'finland').
http___www_wikidata_org_prop_direct_p17('femmes_et_math_matiques', 'france').
http___www_wikidata_org_prop_direct_p17('france', 'france').
http___www_wikidata_org_prop_direct_p17('graduate_women_in_science', 'united_states').
http___www_wikidata_org_prop_direct_p17('united_states', 'united_states').
http___www_wikidata_org_prop_direct_p17('krieger_nelson_prize', 'canada').
http___www_wikidata_org_prop_direct_p17('canada', 'canada').
http___www_wikidata_org_prop_direct_p17('noether_lecture', 'united_states').
http___www_wikidata_org_prop_direct_p17('united_states', 'united_states').
http___www_wikidata_org_prop_direct_p131('basque_center_for_applied_mathematics', 'bilbao').
http___www_wikidata_org_prop_direct_p131('bilbao', 'greater_bilbao').
http___www_wikidata_org_prop_direct_p131('association_for_women_in_mathematics', 'fairfax').
http___www_wikidata_org_prop_direct_p131('fairfax', 'virginia').
http___www_wikidata_org_prop_direct_p131('graduate_women_in_science', 'minneapolis').
http___www_wikidata_org_prop_direct_p131('minneapolis', 'hennepin_county').
http___www_wikidata_org_prop_direct_p463('basque_center_for_applied_mathematics', 'european_mathematical_society').
http___www_wikidata_org_prop_direct_p463('european_mathematical_society', 'european_open_science_cloud_association').
http___www_wikidata_org_prop_direct_p463('international_council_for_industrial_and_applied_mathematics', 'international_science_council').
http___www_wikidata_org_prop_direct_p463('international_science_council', 'unesco_global_open_science_partnership').
http___www_wikidata_org_prop_direct_p463('european_women_in_mathematics', 'european_mathematical_society').
http___www_wikidata_org_prop_direct_p463('european_mathematical_society', 'european_open_science_cloud_association').
http___www_wikidata_org_prop_direct_p1889('computational_science', 'computer_science').
http___www_wikidata_org_prop_direct_p1889('computer_science', 'information_theory').
http___www_wikidata_org_prop_direct_p1889('computational_science', 'computer_science').
http___www_wikidata_org_prop_direct_p1889('computer_science', 'informatics').
http___www_wikidata_org_prop_direct_p1889('computational_science', 'computer_science').
http___www_wikidata_org_prop_direct_p1889('computer_science', 'information_science').
http___www_wikidata_org_prop_direct_p1889('discretization', 'quantization').
http___www_wikidata_org_prop_direct_p1889('quantization', 'quantization').
http___www_wikidata_org_prop_direct_p460('counting', 'enumeration').
http___www_wikidata_org_prop_direct_p460('enumeration', 'enumeration').
http___www_wikidata_org_prop_direct_p361('counting', 'elementary_mathematics').
http___www_wikidata_org_prop_direct_p361('elementary_mathematics', 'mathematics_education').
http___www_wikidata_org_prop_direct_p361('cryptography', 'cryptology').
http___www_wikidata_org_prop_direct_p361('cryptology', 'computer_science').
http___www_wikidata_org_prop_direct_p361('overfitting', 'statistics').
http___www_wikidata_org_prop_direct_p361('statistics', 'mathematics').
http___www_wikidata_org_prop_direct_p361('overfitting', 'statistics').
http___www_wikidata_org_prop_direct_p361('statistics', 'economics').
http___www_wikidata_org_prop_direct_p361('seminar_for_applied_mathematics', 'eth_zurich').
http___www_wikidata_org_prop_direct_p361('eth_zurich', 'eth_domain').
http___www_wikidata_org_prop_direct_p2184('cryptography', 'history_of_cryptography').
http___www_wikidata_org_prop_direct_p2184('history_of_cryptography', 'timeline_of_cryptography').
http___www_wikidata_org_prop_direct_p138('german_tank_problem', 'tank').
http___www_wikidata_org_prop_direct_p138('tank', 'cistern').
http___www_wikidata_org_prop_direct_p138('fermat_kitchen', 'fermat_s_last_theorem').
http___www_wikidata_org_prop_direct_p138('fermat_s_last_theorem', 'pierre_de_fermat').
http___www_wikidata_org_prop_direct_p8875('journal_of_computational_and_applied_mathematics', 'science_citation_index_expanded').
http___www_wikidata_org_prop_direct_p8875('science_citation_index_expanded', 'latindex').
http___www_wikidata_org_prop_direct_p2283('least_squares_spectral_analysis', 'least_squares_method').
http___www_wikidata_org_prop_direct_p2283('least_squares_method', 'minimization').
http___www_wikidata_org_prop_direct_p828('patterns_in_nature', 'auto_organisation').
http___www_wikidata_org_prop_direct_p828('auto_organisation', 'physical_law').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('social_choice_theory', 'http___www_wikidata_org_prop_novalue_p3123').
http___www_w3_org_1999_02_22_rdf_syntax_ns_type('http___www_wikidata_org_prop_novalue_p3123', 'http___www_w3_org_2002_07_owl_class').
http___www_wikidata_org_prop_direct_p366('spectral_signal_to_noise_ratio', 'visualization').
http___www_wikidata_org_prop_direct_p366('visualization', 'science').
http___www_wikidata_org_prop_direct_p366('spectral_signal_to_noise_ratio', 'visualization').
http___www_wikidata_org_prop_direct_p366('visualization', 'statistics').
http___www_wikidata_org_prop_direct_p366('spectral_signal_to_noise_ratio', 'visualization').
http___www_wikidata_org_prop_direct_p366('visualization', 'computer_graphics').
http___www_wikidata_org_prop_direct_p750('hidden_figures', 'itunes').
http___www_wikidata_org_prop_direct_p750('itunes', 'microsoft_store').
http___www_wikidata_org_prop_direct_p2360('fermat_kitchen', 'sh_nen').
http___www_wikidata_org_prop_direct_p2360('sh_nen', 'boy').
http___www_wikidata_org_prop_direct_p2360('science_fell_in_love__so_i_tried_to_prove_it', 'seinen').
http___www_wikidata_org_prop_direct_p2360('seinen', 'teenager').
http___www_wikidata_org_prop_direct_p2360('s_gaku_golden', 'seinen').
http___www_wikidata_org_prop_direct_p2360('seinen', 'teenager').
http___www_wikidata_org_prop_direct_p2360('s_ji_de_asobo', 'josei').
http___www_wikidata_org_prop_direct_p2360('josei', 'woman').
